### ISSUE TITLE
Many lights on the station start off

### ISSUE THREAD

**Issue by Cairo283** [HippieStationArchive/HippieStation13-1#100]
Hey look another bug report; Lights around the station, most notably in the janitor's closet and the mech bay, start off, well, off, even if they are fully powered and the light switch is turned on. This doesn't always happen every round, but is rather frequent anyway. They can be fixed by simply removing the light tube and putting them back in the socket, or turning the light switch off and on again.

**Comment by Kokojos** [comment]
Feature.

**Comment by Crystalwarrior** [comment]
Is it really?

**Comment by Cairo283** [comment]
If it's a feature, then making it so that the light-switches are already off would make more sense.

On a very related note, using an emag on a light-replacer to put exploding lights into the light tubes in a room were this "bug" is occurring, _even if_ the lights are off, will explode the moment they are put in if the light-switch is turned "on". This can cause quite a bit of confusion, and headache when using the light-replacer like this, because you would _think_ that, since the lights are _off_, it would be safe to place the explosive lights in the frames, but it very much isn't safe to do so.

**Comment by ghost** [comment]
Doesn't sound like a feature.

-edit  STOP USING AN FOR EVERYTHING RAAA
~Meme

-edit STOP EDITING MUH COMMENTS

-edit I can to preserve everyone's sanity~
~Meme

**Comment by Kokojos** [comment]
These were implemented with crystalwarrior flickering lights, IIRC

**Comment by WhiteFox08** [comment]
I'm pretty sure this was a feature so the janitor actually had some work to do.

**Comment by collinxchu** [comment]
Not broken, off, whitefox.

**Comment by nalarmg** [comment]
Still an issue apparently.

**Comment by Chronitonity** [comment]
Its still a feature

**Comment by Nokington** [comment]
It shouldn't be a feature. Its dumb.

**Comment by Chronitonity** [comment]
You can literally just take them out to make them work again, it was implemented because the station is a shithole and would have broken off lights on. It's a pretty good feature.

**Comment by Kokojos** [comment]
No, the feature is ''some lights start off''

This is talking about some lights are ALWAYS off, AKA' janitor office at roundstart.

**Comment by Jaygriff** [comment]
I think its a mapping issue, right @Kokojos

**Comment by Jaygriff** [comment]
This has been addressed
