### ISSUE TITLE
Nex doesn't test their code

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#1000]
Major issue with no fix in sight

**Comment by Chronitonity** [comment]
Real talk though @nexendia and @everyone test your code please holy shit

**Comment by AliiTea** [comment]
Are you shitting me

**Comment by AliiTea** [comment]
YOU WASTED #1000 ON THIS
FUUUUUUUUUUUCK

I WANTED TO DO DILDOS FOR #1000 !!!!!!!

**Comment by blobbernaut** [comment]
guess they'll have to wait for #1000000

**Comment by AliiTea** [comment]
or #2000
