### ISSUE TITLE
Shocked grilles will sometimes repeatedly shock you until you die.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#1004]
I was disassembling a window at the bridge and suddenly out of no where the grille started shocking me and wouldn't stop shocking me until I had died. There wasn't even low/high pressure pulling me to the grille.
I've seen this happen to a couple other players too, but it's a very rare glitch and I don't think it can be reproduced easily.

**Comment by Cafaling** [comment]
This is a duplicate issue and is in the process of being handled already.

**Comment by blobbernaut** [comment]
I think if you touch it, while you are standing up with that shocking animation, it will hit you until you are dead if you move towards it at all. Happened to me as an alien sentinel.

**Comment by trifornt-tinfornt** [comment]
Also doesn't help that if you're a Wizard who uses Mutate/Hulk, if you touch a shocked grille it will shock you two times in a row and instantly deep crit you.

**Comment by Spacedong** [comment]
fuck this glitch, can confirm, happened to me in a moment of need. aaaaaaaa ;_;

**Comment by sp1d3rx** [comment]
test when 1835 gets merged

**Comment by Pyko1** [comment]
Should be fixed.
