### ISSUE TITLE
bones into slime people

### ISSUE THREAD

**Issue by SugarBooger** [HippieStationArchive/HippieStation13-1#1007]
its pretty simple if your a bag of bones you can't be a slime man

**Comment by ghost** [comment]
bones aren't a caste of humans, they are a caste of DNA themselves.
therefore, they could be re-arranged. there's a reason their bones are as strong as a full fleshy human

**Comment by danhibiki** [comment]
Just like why you can use bruisepacks on skeletons too. We're not going to make it impossible to go from  skeleton to slime.

**Comment by SugarBooger** [comment]
Then why can't I be a slime person when I'm a skeleton

**Comment by danhibiki** [comment]
Whats going on here?

**Comment by trifornt-tinfornt** [comment]
Skeletons can't turn into a slime if they get the slimetoxin from the black slime (and green slime, I believe) making it completely useless it you pick that race.
Still is a bug as I tried it a while ago and it didn't work.
