### ISSUE TITLE
Carp revived via Lazarus Injector are still hostile to other people

### ISSUE THREAD

**Issue by Cairo283** [HippieStationArchive/HippieStation13-1#101]
See title; Carp, normal, mega, and presumably magic, revived with a Lazarus Injector are hostile to everyone but the one who revived them, resulting in your ass getting sued and it getting euthanized when it bites a poor clown's face off.

While I do love the idea of creating a carp army to take over the station, other mobs, such as goliaths, basilisks, and hive lords, are compleatly docile to everyone, even if attacked (Though they still will attack a certain few other mobs, such as Russians ((RIP Pool Russian)), and carp).

**Comment by Kokojos** [comment]
Apparently fixed before I could work on it.

**Comment by Cairo283** [comment]
Perhaps before closing this and labeling it as a feature, maybe we could discuss if this really _should_ be counted as a feature. I have a feeling, as a non-antag, not many people want to get banned for unwittingly unleashing a horde of magi-carp on the station when they revive them. 

Perhaps making this happen _only_ if the injector is emagged, or even have traitor miners be able to order hacked lazarus injectors which make revived animals only loyal to them.
