### ISSUE TITLE
When putting someone in a deep fryer the action doesn't cancel if the person moves away.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1018]
You can be halfway across the station and get teleported to the deep fryer. It's really lame when it happens!

**Comment by trifornt-tinfornt** [comment]
Can confirm, a chef moved the deep frier out in the open and tried to put me in, I ran literally halfway across the station from him and hid in maint and was suddenly teleported inside of the deep frier.
You can also put people in the deep frier if you are restrained.
