### ISSUE TITLE
Sideways wall-pin sprite is bugged

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#1022]
http://i.imgur.com/wEmZrBX.jpg

http://i.imgur.com/XRqvYaF.jpg

**Comment by Chronitonity** [comment]
Rodguns also don't log @Carbonhello

**Comment by Carbonhell** [comment]
Do you have any clue about what caused those two guys to get their pixel_x and y resetted?

**Comment by Carbonhell** [comment]
Logging fixed, i need info on the main bug through

**Comment by Jaygriff** [comment]
This is a side effect of my shitty spriting cut and pastes and them being incompatable with the new wall blend system, primarily issues with 'chunks' of walls, such as 2x2 and 3x3 etc. We should look into recreating the wall sprites to be compatable.

**Comment by Carbonhell** [comment]
uh what? pinning just edits your pixel x and pixel y to move your char near the wall, how's that related with spriting. But noone experienced this bug anymore so i'm unsure how to fix it

**Comment by Jaygriff** [comment]
Oh shit i thought this was about the wall sprites themselves... My b.

**Comment by Pyko1** [comment]
Both of these issues seem to be fixed on current code, or at least cant seem to be able to reproduce.
Closing.
