### ISSUE TITLE
You can refund spell books that arn't yours on the ragin mages round type, allowing you to get all the spells.

### ISSUE THREAD

**Issue by killer653** [HippieStationArchive/HippieStation13-1#103]
http://puu.sh/hnjRk/d834e5bc23.png

Picture above shows all the spells I had at the end of the round. I spawned as a wiz halfway, and there were about 10 spell books sitting around. I refunded them all, then used all 50+ points to get spells.

Pretty bad bug. Needs fixing.

**Comment by lcass** [comment]
Ill have a look a bit later today , maybe make them possessions and a wiz that trys to steal it gets burnt or sommin.

**Comment by lcass** [comment]
Sorted , check out the pull requests
