### ISSUE TITLE
Swarmers can cause hull breaches on minign asteroid

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#1050]
http://i.imgur.com/XKCXj5e.jpg
http://i.imgur.com/GF6NDsu.jpg
Some walls can be removed and cause hull breaches. The one under disposals can't be removed

**Comment by Voratius** [comment]
not sure if related or not, random pipes under the walls? http://i.imgur.com/nNR5acg.jpg

**Comment by Pyko1** [comment]
more likely the issue lies in the asteroid tiles, and how it checks if it is external wall or not.
As the disposals wall has an actual tile of space next to it.

**Comment by TDcoolguy300** [comment]
Yeah it's a tile checking issue here

**Comment by danhibiki** [comment]
Fairly certain this was fixed?
