### ISSUE TITLE
Action UI Sprite for Shadowlings Dark Vision

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1054]
There wasn't one so I made it, can the sprite be added in since it's confusing as fuck where all the other abilities have an action sprite but dark vision or w/e it's called doesn't. (the one that lets you see in the dark, extremely important.)

Dropbox: https://www.dropbox.com/s/2iu2vwsogxdf5ce/dark_vision.dmi?dl=0

**Comment by Carbonhell** [comment]
I though this was added?I could add it if not

**Comment by ghost** [comment]
Nop, there's no sprite for it.

**Comment by danhibiki** [comment]
Lets get this pushed thru

**Comment by Chronitonity** [comment]
Arguably this should be on the trello or the fourms, the git issue section is for bugs

**Comment by ghost** [comment]
there was originally a sprite for it but it bugged out fam
