### ISSUE TITLE
Golems appear to show the "No Oxygen" symbol on their HUD when in a room without oxygen, but not while in space

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1055]
Not sure if this was a one time thing or it even matters, but as a golem the hud element saying that there isn't enough oxygen only shows up in rooms, not in space. Not a big issue in the slightest, but still a bit weird.

**Comment by Pyko1** [comment]
Humans seem to be missing the no oxygen symbol in the space as well.

**Comment by danhibiki** [comment]
Whats the status on this?

**Comment by Pyko1** [comment]
Should be fixed.
