### ISSUE TITLE
Cannot use flour sack or mime/clown mask on microwave

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#1057]
User reported issue with trying to put flour into the microwave using the flour sack. I advised them to set to help intent, and they told me they tried help, as well as every other intent, to no avail. They could still get flour into the microwave by putting it in a beaker first, but it was impossible for him to get the mime mask inside. I assume the clown mask would be the same.

**Comment by Pyko1** [comment]
I believe its intended, you make dough with water + four. And then flatten it with rolling pin and cut to pieces, and then microwave the dough pieces for buns and use them to tablecraft burgers.

**Comment by Carbonhell** [comment]
^ Food system has been changed,now dough is the main ingredient for pmuch everything. Close,not an issue

**Comment by danhibiki** [comment]
But what about mimeburgers? How do you make them now?

**Comment by Chronitonity** [comment]
Yup, this isnt an issue. Tablecrafting is how you craft most foods, including every burger type now.
