### ISSUE TITLE
Deep fried telescopic batons don't change their sprite when extended

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#1059]
This includes the baton sprite, and the character's sprite when holding it. No one can tell you're holding an extended telescopic baton unless they examine you.

Forgot to take a picture tho

**Comment by Pyko1** [comment]
For me the character icon changes, only the icon in hand remains unchanged.

Tested it with batons/switchblades/eswords.

**Comment by Pyko1** [comment]
How did you fry em, I assume they were on someone who was fried, as invidualyl frying em would just change them to food.

**Comment by McHatters** [comment]
Yeah, they were in an assistant's pocket when I deepfried him. Guess its not too big of a deal if the character sprite changes.

**Comment by Crystalwarrior** [comment]
Not really easily fixable. THis is one of these cases where I say "FUCK BYOND"
