### ISSUE TITLE
can spawn "kill" icons with the grab intent

### ISSUE THREAD

**Issue by account-name** [HippieStationArchive/HippieStation13-1#1102]
by grabbing a mouse, switching to an empty hand, and killing him with harm intent, then dropping after switching to the "grabbing" hand you can spawn these kill things, i assume it doesn't work only with agressive grab and that you can spawn "reinf" icons too

heres how you do it, and how it looks like, these can be dragged around by the way
![ok](https://cloud.githubusercontent.com/assets/15564417/10868993/399c3aa6-8087-11e5-9870-02835417ed4e.gif)

**Comment by Spacedong** [comment]
http://vgy.me/9Tdchz.png

**Comment by Chronitonity** [comment]
No one added the NODROP flag to grabs for some reason, thats why.

**Comment by Carbonhell** [comment]
ABSTRACT should be the correct flag instead of NODROP i believe

**Comment by Chronitonity** [comment]
Nope, ABSTRACT prevents being picked up iirc, NODROP also needs to be there so you can't, you know, drop things.

**Comment by Carbonhell** [comment]
Maybe dropping is needed to actually stop grabbing?Not sure, i don't think they just forgot to add it. Through i can't check at the moment so

**Comment by Chronitonity** [comment]
This was fixed.
