### ISSUE TITLE
Splashing oil/welding fuel does not result in oil slick

### ISSUE THREAD

**Issue by LogJammer** [HippieStationArchive/HippieStation13-1#1103]
# Steps to reproduce:
1. Fill container with oil or welding fuel
2. Splash on floor
3. Behold the pristine floor with no oil on it

**Comment by danhibiki** [comment]
Its as implemented now, they aren't intended to cause oil slicks and as such this isn't a deficit in our code. A worthy suggestion, but not an issue.
