### ISSUE TITLE
Resisting out of a buckle is borked

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#1106]
ADMIN: augphlosion/(REDACTED) (FLW): You have to wait -1.2 seconds to attempt another resist! 

He was in the dog bed because he's a filthy furry but.

@Crystalwarrior

**Comment by danhibiki** [comment]
Did crystal fix this? Or am I mistaken?

**Comment by Chronitonity** [comment]
This broke because of crystals buckling change iirc

**Comment by Chronitonity** [comment]
I thought i elaborated in my original post but i didnt, this means he cant actually resist out of the buckling again, due to it taking -1.2 seconds. 

He was a corgi during this if that makes a difference, so it could be something with simple animals.

**Comment by Voratius** [comment]
Humans too.
http://i.imgur.com/jZpnYdN.jpg

It didn't unbuckle me between the -2 and -7.9 second messages.

**Comment by Crystalwarrior** [comment]
negative unbuckling is simply a display error, will fix

**Comment by Crystalwarrior** [comment]
Fixed in, uh, one of the grabbing branches. Also fixed in https://github.com/HippieStationCode/HippieStation13/pull/1155

**Comment by Chronitonity** [comment]
Crystal when you fix something in a PR, in the description of that PR put "Fixes #Bugnumber" It autocloses the issue when someone merges it.
