### ISSUE TITLE
Embedding is fucky

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#1108]
Sometimes you can't pull embedded objects out of yourself with the "Left click help intent" way.

Sometimes you can't pull embedded objects out of other people by dragging their sprite to yours.

It's causing a lot of death and a lot of shit. @Carbonhello

**Comment by Carbonhell** [comment]
Yes,we already know,issue is that the bug:
1) doesn't runtime
2) won't let you view its variables/the limb it's in's variables
3)only happens on main server
4)happens rarely
so i got no idea. we need a more experienced coder. all i can do is attempts but that's it.

**Comment by Chronitonity** [comment]
Foos [9:48 PM] 
yeah i threw a screwdriver at chron

Foos [9:48 PM]
it bounced off him

Foos [9:49 PM]
but was embedded

Chronitonity [9:49 PM] 
Spent the entire round inside me

Foos [9:49 PM] 
i picked it up and it was in my toolbelt

Foos [9:49 PM]9:49
but it was also in his leg

Foos [9:49 PM]
???

**Comment by Spacedong** [comment]
fuck this issue is gamebreaking

**Comment by danhibiki** [comment]
We had another issue that was related to this that was closed, but the specific issue reported wasn't recorded, so here it is. Objects thrown from explosions will embed oddly in bodies as well sometimes, and you will not be able to remove them

**Comment by Chronitonity** [comment]
My best uninformed guess is that some things are SAYING and ACTING like they've embedded, but the object actually isn't inside you, if that makes sense. Or a copy is inside you, or something.

**Comment by Spacedong** [comment]
hey i think I figured it out, any time something embeds into you that isn't a player throwing it, it gets stuck, for example, bombs and singulo pulling rods into you, etc

**Comment by trifornt-tinfornt** [comment]
I also noticed that things can embed inside of you even if you catch them.

**Comment by Pyko1** [comment]
Embedding is supposedly fixed, and we have multiple open issues about it. Closing this. 
If the issue persist use any open embed issue reports, or if there is none, make a new one.
