### ISSUE TITLE
Welding a coffin gives the wrong welded overlay

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#1110]
As title says, the locker-welded overlay applies,which is not good for a coffin

**Comment by Pyko1** [comment]
coffins are wooden, maybe make em burn if you weld em as a lazy fix.

**Comment by Crystalwarrior** [comment]
Minor sprite issue.

**Comment by Pyko1** [comment]
Is this still a thing, maybe someone could make an overlay sprite for this?

**Comment by Kokojos** [comment]
Our coffins are wood, why can we even weld them?

**Comment by Pyko1** [comment]
I'll try to fix this by make them "weldable" with stapler instead. (And possibly make velder/etc set em on fire instead causing all nice and warm sensations to occupants.)

**Comment by Pyko1** [comment]
Should be fixed.
