### ISSUE TITLE
[Close this] Spellbook of Barnyard appears to have an "oops" sprite

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1113]
![Image of my ass](http://i.imgur.com/t4KP6Sv.png)

Not sure if this is intentional or some weird thing in the round I was playing. Seems like a missing sprite, though.

**Comment by AliiTea** [comment]
C̶̜͈̦̘̼̳̟͉ͩͣ̑̓a̞̭ͭ͋͠n̥̤̟̹͖̜͖̦̅͌̈̃̽̆n̫̗̬͗̉ͩ̏̐ͮ̂͟o̴̡̗̖ͫt͕̹̪̘͎͕̫ͮͧ̆ͮ͑͟ ͇̼̄͗ͭͫ͞r̺̦̪̗̭͋ḛ̯̒̓ͦ̕͜p̝͔͚̆ͨͫ̆̾̈r̗̬̩͚͕͎ͬ̋͐ͣͅơ̷̥̹̬͖̱͎͒ͥ̋̐ͬ̿͞d̹͓̯͂̌͋̍͜͡u̜͍͍̻ͬ̋́c̶̛̰̗̳̔̾ͣ̿ͩ͞e͎̯̍ͫ̆̀̊̊ͦ̒̕͢!̧̗̈̑̓͡

**Comment by AliiTea** [comment]
@Chronitonity close please
