### ISSUE TITLE
IEDS don't do shit

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1115]
they do no fire no turf breaking, they dont do shit.l

**Comment by ghost** [comment]
dude they dontt even burst welder tanks

**Comment by ghost** [comment]
dude tHEY SUCK

**Comment by Pyko1** [comment]
have you tried igniting them and shoving them in someones butt?

**Comment by ghost** [comment]
nope

**Comment by ghost** [comment]
they make no explody noise either bro!!!

**Comment by Chronitonity** [comment]
Feature request or trello. Or make a new issue tracker with more than "this sucks"
