### ISSUE TITLE
You can get Fire Axes embedded in your arm, which is stupid

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1116]
_---------_
This is Urist McDick!
He has a fire axe embedded in his right arm!
He is bleeding!
_---------_

Why is this a thing? I get that they could embed in real life but it seems like a good way to just lose a fire axe. It's lame.

**Comment by ghost** [comment]
you can pull it out of your body to get it back lad

**Comment by Chronitonity** [comment]
Don't throw a fireaxe. This is a feature, if you want it removed, the best place is the fourms, not the issue tracker.
