### ISSUE TITLE
Meatspiking monkeys no longer works

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1118]
I can no longer steal Pun Pun, meatspike him, rip the meat from it's flesh and eat it infront of the bartender. 

Whenever I try to spike a monkey, I now have to have a reinforced grab, and after a long wait, it shoves the monkey onto the spike (the monkey then lets out a human scream) and I can't take any meat from it.

**Comment by Chronitonity** [comment]
Use a knife on pumpun
