### ISSUE TITLE
Lizard teeth are human teeth

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#1120]
http://puu.sh/l7sNi/4824e79a53.png

Unsure if this extends to other races

**Comment by danhibiki** [comment]
Just might two cents, but I think having different sets of teeth for each race, while logically makes sense, doesn't serve any large purpose for us.

**Comment by Chronitonity** [comment]
Pretty sure its so you can beat them out of lizard/cat people and use them as trophies

**Comment by Crystalwarrior** [comment]
Not supposed to happen, pretty sure I set ligger's teeth correctly...

**Comment by Chronitonity** [comment]
No ones teeth besides humans are set correctly. No cat, lizard or captain teeth.

**Comment by danhibiki** [comment]
This is fixed
