### ISSUE TITLE
Dental Implants are a mess right now

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#1121]
@Crystalwarrior 

Have no action button on the upper hud, meaning you can't use them, seem to just bork with shit

**Comment by Spacedong** [comment]
nah mine works I used mine a few days ago you must be bugged

**Comment by ghost** [comment]
implying all the commits and shit we've ben adding couldnt have brok
en it

**Comment by ghost** [comment]
added a pill to my body and the thing fucking dissapears as soon as it's in

**Comment by ghost** [comment]
https://i.gyazo.com/60b3228e6d94b41818b481c7590d05be.png more proof

**Comment by Chronitonity** [comment]
@oprayx73 You don't need to make 3 comments, just edit your first one.

**Comment by danhibiki** [comment]
Status?
