### ISSUE TITLE
Non cultists can't use soulstones

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#1122]
This means the librarian as a traitor can't use them, or a miner who found one on the asteroid.

**Comment by AliiTea** [comment]
Óͭ̑ͭ͗͘͏̱H̡͔̳͇̝͗̆ͩͯ̔́ ̴̗ͮ̆ͬN̍ͣ́̓҉͉ͅO̴͂ͦͨ̐ͣ͏͍̤͓̩͇̼̘ ̟ͤͥ̅ͭ̃Ģ̙̬̝̞̖ͯͨ͘A̧̫̰̫͚̖̓ͦ̀ͦ͊̀ͧͅM̷̶̘̦ͭͬ̋̆E̶̱͍̳̹̦̲ͥ̂̉B̧̜̦͕̘̪̰͈͐̓ͥͨ́͟ͅͅR̢̳̳̫̣͋ͥ̍͗͛̀̀͞E͗ͮ̃҉̗Ȧ̢͎̳͑͌ͤͫͪ͊̚K͓̫͔̮̺̗͙̎́͘Į̇ͣͣ͑́͊͗͏̦͓̖̜̼͟ͅÑ̨̡͚̩̓͒ͪ̿͒ͧ̚ͅG̜̳̿̈́̇̿́̚ ̷̢̞̮͎̯̞̫̼̊̓̈́ͥͨ̍B̌̅̈̉̂̀ͨͫͫ҉̭͙̦̗̯U̲͉̠̜̹̞̮̯̲̅̂͘G̼̠̘̳̘̿ͬ͠!̢̤̻̝͗̑̏ͪ!ͫ͊ͭ͛͌̓ͤͤ͟҉͕̭!̮̱͉͕͈͍̺͗ͤͅ
