### ISSUE TITLE
Emitters now have a chance to miss Field Generators

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#1123]
Okay so this is weird, but with pixel projectiles, it looks like emitters can become _slightly_ out of line with the Field Generator for the singularity.

http://puu.sh/l7FiA/2662fce1d7.png

http://puu.sh/l7Fjl/72e4f171a2.png

This means that the Field Generator can just get RNG fucked and let the sing free. @Crystalwarrior

**Comment by Chronitonity** [comment]
http://puu.sh/l7Fps/10168e0d40.png

Pictured, emitter just flying pass the shield generator.

**Comment by Crystalwarrior** [comment]
Trying to figure this out, definitely an issue with my pixel projs. Will probably have to use legacy mode for emitter beams.

**Comment by Crystalwarrior** [comment]
Fixed in https://github.com/HippieStationCode/HippieStation13/pull/1124
