### ISSUE TITLE
Extremely game breaking stun bug

### ISSUE THREAD

**Issue by meteoses** [HippieStationArchive/HippieStation13-1#1129]
When you get stunned you are partially blind, very slow, and go unconscious constantly for a solid 5 minutes.

**Comment by Chronitonity** [comment]
Can confirm, no idea why this happens, but its ruined a solid 2 rounds for me

**Comment by Chronitonity** [comment]
To add on, this happened to me when a traitor hit me with the stamina darts, i'll try and test this to see what does it asap
