### ISSUE TITLE
Invisible garrote

### ISSUE THREAD

**Issue by nomis213** [HippieStationArchive/HippieStation13-1#1166]
![invisible garrote](https://cloud.githubusercontent.com/assets/15720413/11023085/2780fd78-866f-11e5-8499-9dce6f9b2a2e.jpg)
yea i made a garrote with purple wire and it turned out invisible can still pick it up seems like there is no sprite for it or whatever was told to report it here.

**Comment by Chronitonity** [comment]
I'll check it out when i get home
