### ISSUE TITLE
You can't tablecraft Garrote handles

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#1170]
http://puu.sh/lezWP/f0d3b5a73e.png

Tried with welder in my hand, on the table, a second welder in my hand, everything. Theres 10 rods on that table and more than enough cablecoils

**Comment by danhibiki** [comment]
On that note, the welding fuel requirement is a bit odd. Here is something a player reported

OOC: DukeNukemForever: dafuq i need '1 welding fuel' for making garottes now
OOC: Dan Hibiki: Wat
OOC: DukeNukemForever: 1 Welding fuel 15 cable coil 1 metal rod, Tools: welding tool
OOC: Dan Hibiki: Maybe its so you can actually weld
OOC: Dan Hibiki: So like, just place a welder on the table
OOC: DukeNukemForever: nope gotta have welder in hand

**Comment by Crystalwarrior** [comment]
Are you sure the welder was lit?
I'll look into it.

**Comment by danhibiki** [comment]
Totally unaware, was just an exchange that happened over OOC.
