### ISSUE TITLE
Metal baseball bats can be table crafted to make wooden spiked bats.

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#1173]
Probably because metal bat is a child of wooden bat, I assume. Just looks a bit silly.

**Comment by Crystalwarrior** [comment]
Solution: DON'T make metal bats a child of wooden bats. Instead, keep all bat-related proc in weapon/baseballbat or whatev, and then add /wood and /metal subtypes.
