### ISSUE TITLE
Engiborgs can repair themselves.

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#1177]

**Comment by Chronitonity** [comment]
Not a bug, it takes time and is cancelled if they're pushed. intended.

**Comment by danhibiki** [comment]
This isn't how it was before rebase, and we shouldn't be making decisions without discussing them with the entire staff. This needs to be changed back to what it was before.

**Comment by Chronitonity** [comment]
uh thats why we have trello. This isn't a bug, we close things that arent bugs, we discuss feature requests and removals on the trello.

**Comment by danhibiki** [comment]
No, your right, its an issue with consistency, because its a change in functionality that resulted in rebasing without properly checking that everything was changed over. We have a lot of little things like this, and these are issues with how the code was transitioned and how its currently maintained. Thus, an issue ticket.

**Comment by Carbonhell** [comment]
So,how should we deal with this?Completely remove the ability, nerf by adding some sort of delay, or what?

**Comment by ghost** [comment]
sounds dumb
i'd be for this if all borgs had a little teenie welder meant for repairs

**Comment by Chronitonity** [comment]
P sure it already has a delay so

**Comment by Pyko1** [comment]
I kinda like it, and they cant still repair the wires inside themself tho.

If it really becames an issue maybe increase the amount of fuel used per repair.

**Comment by Chronitonity** [comment]
Its pretty balanced how it is (and still not an issue)
