### ISSUE TITLE
Biobags in biolockers can't mass pickup slime extracts

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#1184]
Is this intended? It's much faster to take slime extracts and put it in the smartfridge by hand than to use this.

**Comment by Chronitonity** [comment]
If you mean unused ones, yes because they aren't biowaste.

**Comment by McHatters** [comment]
ah

**Comment by McHatters** [comment]
That's weird though, because you can still put unused slime extract into the biobag Does it pick up anything else aside from slime extracts?

**Comment by Chronitonity** [comment]
Syringes, beakers, bottles, blood packs, medipens, and dead mice

They're for containing "waste"

Anyway closing because not a bug
