### ISSUE TITLE
[URGENT FIX] Traitor AI's Borgs don't get the proper Law 0 when AI is a traitor and hacks them.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#1185]
rip my antag round because of this.
Borg was still linked to me and everything when he killed me.

**Comment by danhibiki** [comment]
I'm moderately certain this worked on my MALF round, so it might just be related to traitor AI.

**Comment by SplergeBucket** [comment]
Yo, bug here. Traitor AI hacking their cyborg results in the Cyborg being displayed as an antag in the 'who' list and the Cyborg gaining their hacked weaponry, but the Cyborg itself has no hacked laws and has no obligation to obey the AI.

Proof this thing was an antag:
http://puu.sh/lhpKg/f94e92f14c.png (2KB)

http://puu.sh/lhpKX/663f37074d.png (8KB)

[09:33:11] Has stunned Dean Damon with the electrically-charged arm @ 184,107,1(INTENT: HELP) (NEWHP: 100) = null

Laws:
AI ARTIFICAL ANTHRO GOAT's laws:
0. Accomplish your objectives at all costs.
1. Never willingly commit an evil act.
2. Respect legitimate authority.
3. Act with honor.
4. Help those in need.
5. Punish those who harm or threaten innocents.
CYBORG Fluffy (Slaved to: ARTIFICAL ANTHRO GOAT): laws:
1. Never willingly commit an evil act.
2. Respect legitimate authority.
3. Act with honor.
4. Help those in need.
5. Punish those who harm or threaten innocents.

**Comment by Carbonhello** [comment]
Will look into this in around 6-7 hours

**Comment by Carbonhell** [comment]
So, hacking a cyborg doesn't add a law 0. the law 0 is added automatically on creation if the borg is synced to the traitor ai. the hack option only gives the special module,that's it.
So, from what i saw, traitor borgs have some weird special command used to severe any connection to their AI. Apparently this doesn't remove the hacked module either, nor the law through,so i really don't know how this happened and if it's relevant to this hidden weird verb. More info is required.

**Comment by Carbonhell** [comment]
DISREGARD THAT,i managed to...sorta reproduce the bug where hacked borg doesn't show up as an antag,not the actual law issue through. So yea,cannot reproduce the main bug.

**Comment by danhibiki** [comment]
Any info on this?

**Comment by trifornt-tinfornt** [comment]
Nope. I think it might have been a strange, unknown issue that just kinda happened outta no where. Doesn't seem to have happened again at all.

**Comment by Chronitonity** [comment]
Nah this still happens. Even happens if a traitor uploads a law 0 into an AI and new cyborgs get made. Happens at TG too.

**Comment by TDcoolguy300** [comment]
Just need to autosync the laws on the new cyborg or something.

**Comment by Kokojos** [comment]
https://github.com/tgstation/-tg-station/pull/14272/files

We just need to apply this fix.
