### ISSUE TITLE
Slight VV error

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#1186]
Currently it state the HP before the attack went thru (Has been torn out the tooth from by Huffie Elliott(danhibiki) with the wirecutters @ 125,77,2 (NEWHP: 100) = null) Either getting the hitpoint and logging after damage is process would work, or changing NEWHP to OLDHP would work.

**Comment by Crystalwarrior** [comment]
Actually a case-by-case issue, we need to go over the code and make sure all add_logs proc calls are called AFTER applying the damage.

**Comment by Carbonhell** [comment]
As crystal said, case by case issue, needs to be reported with the exact object it's happening with.
