### ISSUE TITLE
Nuke core container isn't containing core's radiations.

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#1187]
A traitorling got the core, used the box on it and it sealed correctly,yet the core continued to emit radiations as if it wasn't contained.
http://puu.sh/lhIZ4/66a7419d3c.png
http://puu.sh/lhJ06/23cd3bb0d9.png

https://github.com/HippieStationCode/HippieStation13/blob/7e8e4e70be2bf67c1be5800ef7fd0f66ff50efd6/code/game/objects/items/nuke_tools.dm

It happened around 5 minutes ago,round just ended.

**Comment by danhibiki** [comment]
Its true, I thought it was intentional to be honest and I thought it was hilarious, I ended up hiding the extracted core somewhere else so I wasn't tripping balls the entire time.

**Comment by Carbonhell** [comment]
For some reasons i cannot reproduce this in local. Could it be an issue due to something else stopping the obj controller for a while?no clue..

**Comment by TDcoolguy300** [comment]
"SSobj.processing -= core" This should be removing the core from the ticker, preventing it from processing any further. A redundancy var can be thrown in as a second check

**Comment by danhibiki** [comment]
Wasn't this fixed?
