### ISSUE TITLE
Replica Pods not working

### ISSUE THREAD

**Issue by Higitus1** [HippieStationArchive/HippieStation13-1#119]
It seems the problem comes when you need to harvest it. I can inject the seed with blood and when I scan it the yield production is 1 but when it is ready to harvest all I get is some more seeds.

**Comment by Cairo283** [comment]
Damn it, I totally forgot to report this crap. Anyway, yeah, them things be broken as 'ell.

**Comment by ghost** [comment]
Replica pods only work if the user is still in his body, will change this around in the near future, but for now, it works.
