### ISSUE TITLE
Catbans are fucked and broken.

### ISSUE THREAD

**Issue by SplergeBucket** [HippieStationArchive/HippieStation13-1#1190]
if this was fixed somehow so i can actually catban people that'd be fantastic
remember catbeast a disease wipe them out
fresh meme
im out of words here i'll email a blowjob to the guy who gets this shit done

**Comment by Spacedong** [comment]
why catban when looping and foos are furries and allow catbeasts to fight back, it basically makes the entire catban pointless ;^)

**Comment by danhibiki** [comment]
wat da fuk did u sai abut me u litl kunt
