### ISSUE TITLE
SPEAKEASY BAR

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1198]
says " ACCESS DENIED" on the bar vendomat
used to require no access pre-rebase, got FIXED, and now it's back to requiring bar access! LAME!

**Comment by Crystalwarrior** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
This is utterly retarded and should be fixed asap

**Comment by Chronitonity** [comment]
Mostly intended because its a free stun dispenser, just hack it

**Comment by Carbonhello** [comment]
Not a bug,close?
