### ISSUE TITLE
you can pull the sm

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1201]

**Comment by ghost** [comment]
pulling the sm is a shit gimmick shouldinstantly gib your ass

**Comment by TDcoolguy300** [comment]
Well, this is a big issue because of the shit it causes, will bring this back.

**Comment by danhibiki** [comment]
This is a bit different from the SM we had before rebase, as this is the supermatter shard. I'm not sure on the exact detonation radius and how many rads it produces, but I'm fairly certain its lower than it was before.

**Comment by ghost** [comment]
yet it instagibs on touch just the same

**Comment by trifornt-tinfornt** [comment]
This is a supermatter SHARD though, and something that can easily be transported through cargo crates. Making it unpullable would actually make it deadlier because now nobody who is brave enough can space it.

**Comment by Chronitonity** [comment]
you could always give it X burn damage per tile pulled, making it a dangerous item to transport

**Comment by Pyko1** [comment]
Would be neat if it had a chance to cause those lightnings when pulled, that revenant can make with overload lights. Maybe start with really small chance but increase as the sm gets more charged or what ever it does when hit by something.

**Comment by TDcoolguy300** [comment]
Right,  i am not sure if there's a proc for checking whether it's being pulled or not, need to look into it some more.

**Comment by ghost** [comment]
burn per tile will not affect borgs
right

**Comment by danhibiki** [comment]
Less of an issue, more of a balance discussion. Closing this, but I don't want you to think I'm saying "no"
