### ISSUE TITLE
Space vines can spread through space.

### ISSUE THREAD

**Issue by Crystalwarrior** [HippieStationArchive/HippieStation13-1#1204]
http://puu.sh/lkYEO/e821e9ff55.png
Despite the name, this is NOT the purpose of Space Vines.
Spreading through space can possibly cause fuckloads of lag if there's a lot of vines.

**Comment by Pyko1** [comment]
I kinda like this tho, maybe make them need to be adjacent to a turf, while still allowing growing in space tile.

So the vines can cover the station from outside and be even more annoying with hull breaches.

**Comment by TDcoolguy300** [comment]
Did not know this actually happened, a turf check would be the best option here
