### ISSUE TITLE
Fire extinguishers make floor wet with their water

### ISSUE THREAD

**Issue by Crystalwarrior** [HippieStationArchive/HippieStation13-1#1206]
/title, this makes fire extinguishers ridiculously fucking powerful and haviing any other water-based sliptools is pretty much redundant.

@Carbonhell THIS IS ALL YOUR FAULT AAAAAAAAAAAAAAAAA

**Comment by McHatters** [comment]
why is this a thing

**Comment by Crystalwarrior** [comment]
because seems like water acts regardless of amount.

**Comment by Carbonhell** [comment]
As i said countless fuckin times, water doesn't wet a tile for 79 seconds even if one unit is used anymore. It now wets the tile based on the amount of units used. Since only 2 units are sprayed per effect from the extinguisher and therefore 2 units applied per tile, said tile will only be wet for 10 seconds, so it's not really an huge deal, since you can actually make tiles wet for 79 seconds with a proper space cleaner/by splashing water/etc

**Comment by ghost** [comment]
stupidly op

bring back 10u required for making apool

**Comment by Crystalwarrior** [comment]
That's terrible because the stun for slipping is still full. It's a huge deal because you can slip an entire lynch squad and laser them one by one since they don't have enough time to get up.

**Comment by ghost** [comment]
you can make an entire halway unwalkable in one click
for the next 10 seconds

**Comment by Pyko1** [comment]
Imho would had been better if the minimum water slip amount had stayed at 10, and then nerfed the slip times based on that.

Instead of actually buffing the water slipping.

**Comment by ghost** [comment]
plus, this actually ruin's pyko's spray bottles in perma

now you can just spray 5u and slip peopel

**Comment by Carbonhell** [comment]
Gonna remove water but not lube since it's actually harder to get.

**Comment by ghost** [comment]
just made 1000 units of lube in like 2 minutes

**Comment by Carbonhell** [comment]
well thank you,removing lube aswell then you fuk

**Comment by Carbonhell** [comment]
fixed in next pr, 5 units are needed now as a minimum

**Comment by Pyko1** [comment]
would be nice if it was more than 5 as the safety bottles in perma are limited to 5 just to stop slipping.

**Comment by ghost** [comment]
how bout TEN.
;(
