### ISSUE TITLE
Medbay Security Checkpoint's Pepperspray Loader glitched out

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#1212]
![](http://i.imgur.com/UG9nMWk.png)

**Comment by McHatters** [comment]
Forgot to mention, the loader itself is pullable, and has an invisible tile to the left of it that you can't walk over. You can, however, push the loader around by walking into this tile.

**Comment by Pyko1** [comment]
It seems none of the pepperspray refillers are anchored. Making a fix.
