### ISSUE TITLE
Black powder

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1214]
black powder is so shitty,
30u doesn't even mess up the floor or antying, just makes the beaker do a  flip.

**Comment by Carbonhell** [comment]
considering how it can bypass bombcap if you use enough units, i don't think it's an issue really

**Comment by ghost** [comment]
1000 units 
you can't use it practically

**Comment by Chronitonity** [comment]
This is more of a trello thing, not an issüe.

+with enough of this you can easily go all out bomberman, just because 30u doesnt blow a hole in the station means it broken

**Comment by ghost** [comment]
you need literally 1000 units
dude it should do SOMETHING at 30 units holy

**Comment by lcass** [comment]
Even though this is a trello issue I would still say that 30 units is way too high amount for such a mild amount of damage , this basically makes it a horrifically impractical solution for anything . Gib smoke doesn't work at all and nor would a full beaker bomb. You might aswell just use potassium and water.
