### ISSUE TITLE
Fueltanks that explode don't blow up adjacent fuel tanks

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#1215]
http://puu.sh/lnbZH/e113564ba9.png

Used to blow up the fuel tanks next to each other, im guessing @Carbonhello changing how fueltanks worked fucked it up

**Comment by Carbonhello** [comment]
/obj/structure/reagent_dispensers/ex_act(severity, target)
    switch(severity)
        if(1)
            qdel(src)
            return
        if(2)
            if(prob(50))
                boom()
                return
        if(3)
            if(prob(5))
                boom()
                return
        else
    return
Not qn issue,explosion was just too weak

**Comment by Chronitonity** [comment]
A tank literally full of welding fuel should still be blowing up the ones next to them, like it did pre-update

**Comment by Carbonhello** [comment]
Forgot to include this in my PR,was fixed pls close
