### ISSUE TITLE
Monkeying as ling is bugged to hell.

### ISSUE THREAD

**Issue by Norzonion** [HippieStationArchive/HippieStation13-1#1220]
I've had several people ahelp saying they randomly get ghosted when they go into lesser form, the monkey acts like an NPC and usually wanders off.

Another issue i've been notified of is when a ling has the eye augmentation evolution and they go into monkey they will also drop the eye implants given by the augmentation evolution.

**Comment by McHatters** [comment]
Funny enough, they drop the eye augmentation as two separate implants: One for flash and welding immunity, and one for night vision and thermals. A human can only implant one of them, though.

**Comment by Carbonhell** [comment]
runtime here, http://pastebin.com/NaRsPP7g , to reproduce it just monkeify and transform into yourself a few times

**Comment by Carbonhello** [comment]
Theorically should be fixed with the changeling overhaul we had

**Comment by Crystalwarrior** [comment]
Not sure if this is fixed, keep open.

**Comment by Carbonhello** [comment]
Happened again from what i heard.

**Comment by Carbonhell** [comment]
It was fixed from what i heard,and if it wasn't there's another issue up for it
