### ISSUE TITLE
Remove the zombie from the derelict

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#1224]
Players can possess it and eventually reach the main station to infect people. Suggest it be made admin only or a random event to prevent every round being a zombie round.

**Comment by TDcoolguy300** [comment]
I :+1: This movement.

**Comment by ghost** [comment]
wll i get banned for using this

**Comment by Chronitonity** [comment]
Don't use this.

**Comment by ghost** [comment]
; (
var edit it every round agaagag

**Comment by Crystalwarrior** [comment]
:+1: :+1: :+1:

**Comment by calibraptor** [comment]
Any news on this shiz
