### ISSUE TITLE
Janiborg no longer has his janibucket

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#1228]
This is obviously a post-rebase issue considering he used to have the bucket before we switched. Now his mop is useless yet again.

**Comment by Carbonhello** [comment]
You mean the blue or the yellow pullable one?

**Comment by trifornt-tinfornt** [comment]
The yellow one he had back before our rebase - was a borg module?

**Comment by Nokington** [comment]
just remove mop. problem solved

**Comment by Pyko1** [comment]
Should be an easy fix in way or another. 
Just need more head input really.
Remove mop, add bucket or call it a feature.

**Comment by Pyko1** [comment]
feature
