### ISSUE TITLE
Space Lube requires 10 units to make an effect, has little range.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#1229]
Not sure if this nerf was intended but it's not stated anywhere in the changelogs. I can tell it was made for fire extinguishers because they can only shoot five units as opposed to the ten units required for Space Lube to make an effect at all.

Safe to say this nerf has made Space Lube just as useful as Fluro acid.

fire extinguishers not being able to shoot water/lube anymore and not giving them an item that lets them do that any way is lame :-1:

**Comment by Carbonhello** [comment]
It was intended,everyone disliked how fire extinguisher was op with lube or water so i had to remove it

**Comment by danhibiki** [comment]
This fireextinguisher push seems to be having more effects than first conceived
