### ISSUE TITLE
Walking into an electrified door with insulated gloves on will endlessly spam sparks.

### ISSUE THREAD

**Issue by Crystalwarrior** [HippieStationArchive/HippieStation13-1#1232]
/title, this can potentially cause fuckloads of lag and is generally terrible.

**Comment by Weisyl** [comment]
Pretty sure you have to click on the door to spam it, and even then I haven't noticed spam as described here. It's worse when mechs walk into airlocks they can't access though.

**Comment by Crystalwarrior** [comment]
I've seen two people spamclick an electrified door to death

**Comment by desertofunknown** [comment]
Fixed this
