### ISSUE TITLE
Odysseus can synthesize traitor chems

### ISSUE THREAD

**Issue by myontasm** [HippieStationArchive/HippieStation13-1#1238]
It seems that the apparant blacklist that is in place isn't actually working or not existent, as I managed to synthesize initropidril, amanitin and neurotoxin no problem with the exosuit syringe gun during a quick test in the Thunderdome.
![image](https://cloud.githubusercontent.com/assets/10575508/11249685/aafabc32-8e28-11e5-9b53-0206b253ad6e.png)

**Comment by Chronitonity** [comment]
Gonna call this as a feature, if someoen manages to do this good for them.
