### ISSUE TITLE
The canvas for easels are horribly coded and can easily break the game.

### ISSUE THREAD

**Issue by Weisyl** [HippieStationArchive/HippieStation13-1#1239]
So the canvas for easels happens to be awfully broken. In the code, you have to define the sum of all canvases that will be present on every loaded Z-level. While this amount does NOT matter if no canvases are present on any loaded Z-level, there are DISASTROUS effects if there are canvases on any loaded Z-level and the amount defined in the code does not equal the amount of all canvases present.

So if you have 5 canvases on the station but the code has it defined as 3, what will happen is icons for virtually everything will be scrambled and dreamdaemon will flooded by runtime and proc errors. Example: http://puu.sh/lqCDU/8ec8a6ff80.png

This error did not APPEAR to happen if canvases were spawned during run-time, but I only picked them up and threw them around and did not attempt to draw on them. This is a BAD issue because anybody unaware of this could place down canvases, PR a map-update, and if said update is merged, can very easily cause major problems.

**Comment by AliiTea** [comment]
Ayy. La. Mao.

**Comment by Pyko1** [comment]
We are using updated version of the canvas easels thinggy, not sure if this is relevant anymore.

**Comment by AliiTea** [comment]
This probably still is a relevant issue.
