### ISSUE TITLE
Odd grabfu issues

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#1242]
Had someone with reinforced grab, someone dragged them off to another part of the escape shuttle. I move one tile, and the mob I was grabbing previously teleported beside me.

**Comment by Crystalwarrior** [comment]
do you mean aggressive grab, or did you reinforce it into a neckgrab?
I may have missed one of the cases where grabs check for proximity of the grabbed mob.

**Comment by danhibiki** [comment]
I believe I reinforced into a neck grab.

**Comment by Crystalwarrior** [comment]
Should be fixed in https://github.com/HippieStationCode/HippieStation13/pull/1255
