### ISSUE TITLE
Escape shuttle stun is too low, mining shuttle stun is just right

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#1244]
We should be able to, technically, get these stuns to be the same time. It was a lot longer pre-rebase, but I suppose we don't need to get the exact number down. Right now, there is little worry to buckling because you get right back to your feet.

**Comment by calibraptor** [comment]
Let's make it fun and have it throw the people in question back a ways, dealing damage if they smack into other people/objects and stun them for a bit. Same for when it docks except just throw them forward.

**Comment by danhibiki** [comment]
Interesting idea, you should definitely post that on the trello or posit it to a coder (like it is now), but I just want to stress that that is not the issue with this ticket.

**Comment by calibraptor** [comment]
But yeah, the stun is low enough that it's laughable.

**Comment by danhibiki** [comment]
Looking into this.
