### ISSUE TITLE
Revolver on nuked station

### ISSUE THREAD

**Issue by Galardomond** [HippieStationArchive/HippieStation13-1#1248]
Hi,
on the Station, which was attacked by nuke ops (you can find it by orbiting the dead "scientist"), there is the Detective's Room. Inside are Remains, a death note, a bullet chasing and a fully loaded 7/7 live Revolver. You should remove the chasing and make the revolver have 6/7 live rounds!

**Comment by ghost** [comment]
what if he just left it there

**Comment by AliiTea** [comment]
@Chronitonity lowest of low priority here
