### ISSUE TITLE
Skull Face Bandana Inhand sprite

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1257]
https://i.gyazo.com/cfbfdcdf3c9307776b39b7df6cbae656.png

has alien facehugger shit

**Comment by Crystalwarrior** [comment]
oh god holy shit rofl

**Comment by danhibiki** [comment]
halp coders halp

**Comment by danhibiki** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/7e8e4e70be2bf67c1be5800ef7fd0f66ff50efd6/code/modules/clothing/masks/miscellaneous.dm

**Comment by danhibiki** [comment]
http://i.imgur.com/XVpvcPa.png nothing on this end though, might be fixed?
