### ISSUE TITLE
Gang Dominator messages not showign.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1264]
https://i.gyazo.com/f73f0167eda848a795dcd2dede0ab476.png

it doesn't show up for all the gangs,

so as soon as i hear the second one go off the game is already over. the status menu will show the counters but you dont get the real message that shows it

**Comment by TDcoolguy300** [comment]
No idea why your not seeing it, codewise it's perfectly fine. If your holding a gang tool you'll also get a message.

**Comment by Crystalwarrior** [comment]
Can anyone confirm this issue?

**Comment by TDcoolguy300** [comment]
No one was able to reproduce, closing
