### ISSUE TITLE
Krav Maga pindown bug

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1271]
https://i.gyazo.com/a696ca4799c53af645d8a4ed6d5efc72.png
Pinned down a dead dude using the grab tactic to disarm
then threw his ass, ended up like ths. when i dragged him around he was still upsidedown

**Comment by Crystalwarrior** [comment]
weird issue, don't know the exact steps to reproduce. Seemingly random occurence.

**Comment by Carbonhell** [comment]
This bug hasn't been seen since 4 months. Make the issue again if it shows up
