### ISSUE TITLE
"Sticky" Following with Chemtank explosions

### ISSUE THREAD

**Issue by Nebyab** [HippieStationArchive/HippieStation13-1#1276]
If I'm following (orbiting) someone, I can't actually jump to the site of a chemtank explosion
ADMIN LOG: SOMEDUDE/(THESAMEDUDE) triggered a chemtank explosion at 98,74,1 - JMP).
ADMIN LOG: Nebyab/(Hacks-The-Airlocks) jumped to coordinates 98, 74, 1
ADMIN LOG: Nebyab/(Hacks-The-Airlocks) jumped to coordinates 98, 74, 1
ADMIN LOG: Nebyab/(Hacks-The-Airlocks) jumped to coordinates 98, 74, 1
ADMIN LOG: Nebyab/(Hacks-The-Airlocks) jumped to coordinates 98, 74, 1
ADMIN LOG: Nebyab/(Hacks-The-Airlocks) jumped to coordinates 98, 74, 1
ADMIN LOG: Nebyab/(Hacks-The-Airlocks) jumped to coordinates 98, 74, 1

I had to move off the guy I was following in order to be able to jump. 
If this is intended (for some reason) just close this.
Also why is there an extra parentheses at the end?

**Comment by Nebyab** [comment]
Apparently my first thing is an inherent feature of follow, but the second issue is a critical issue which, if let unchecked, will almost certainly bring about the downfall of the server.

**Comment by Carbonhell** [comment]
the JMP thing applies to any jumping command while you're orbiting as far as i know, and the parentheses,eh

**Comment by Crystalwarrior** [comment]
JMP command doesn't cancel-camera-view. Simple fix.
