### ISSUE TITLE
coloring gloves problem

### ISSUE THREAD

**Issue by Angelx113** [HippieStationArchive/HippieStation13-1#1279]
tryed to paint my yellow gloves with mimes grayon, but it didn't work

**Comment by ghost** [comment]
can confirm, tried to colour latex gloves with a yellow crayon and it just reduced the alpha

**Comment by danhibiki** [comment]
This is the code relevant to washing machines changing glove color. https://github.com/HippieStationCode/HippieStation13/blob/a34bd7e7f59f7d4b0116fd9e1a84cbd1db1402b3/code/game/machinery/washing_machine.dm#L55

**Comment by Crystalwarrior** [comment]
Issue with washing machine code now simply recoloring the item sprite.
One solution would be to get a generic "white" glove color and recolor that.

**Comment by danhibiki** [comment]
I think that would work best and is worth a run. And maybe renaming the gloves to the color of the crayon used, as that was sort of one of the things with dyeing gloves.

**Comment by desertofunknown** [comment]
Just fixed this issue as well as added in name and description changing.....

**Comment by JohnGinnane** [comment]
Hi,

I've been testing this and found that the names/descriptions remain the same. I might do up a separate pull request to fix the names/descriptions, so if you coloured any set of gloves (white, insulated, etc.) to any color, for example red then the gloves will be renamed as such, but still hold their function (e.g. insulated will still protect you from electric shocks)

**Comment by desertofunknown** [comment]
Fixed just isn't published yet

**Comment by JohnGinnane** [comment]
Is there a way I could have a look at your code? I've been working on fixing this and would like to see if I've added anything

**Comment by desertofunknown** [comment]
Yeah I will let you see it though once I push it don't want my contribution stolen yah know?

**Comment by JohnGinnane** [comment]
Fair enough

**Comment by JohnGinnane** [comment]
To give you a hint at what I've done so far: 
![image](https://cloud.githubusercontent.com/assets/3355198/14062882/f9c4b5dc-f3a6-11e5-826f-9cffdb84ba8a.png)

I've left the description unchanged for two reasons:
1. It could be a way to distinguish between fake/coloured clothing and the real thing, however this would only work on items not being worn.
2. It makes it awkward to handle things like latex gloves. My change replaced the words using a list, and my resulting description for latex gloves was "Cheap sterile gloves made from red."

**Comment by Pyko1** [comment]
you claim you have fixed this 18 days ago but haven't made a PR...
Please someone else fix this.

**Comment by desertofunknown** [comment]
Tomeno(Noscopetoolbox) has already personally seen it...

Edit:Forget it i'll just discard my changes...
