### ISSUE TITLE
Stepping on lattice causes movement.

### ISSUE THREAD

**Issue by killer653** [HippieStationArchive/HippieStation13-1#128]
Bug: When you step on a lattice, it will cause you to move further than intended.

If there is a lattice setup, like below then you will be able to step on and around both lattices. BUT
XOO
OXO
OOO

(X is lattice, O is open space)
If you step on the lattice, like the setup below, you will proceed to keep moving in the direction you were moving in before, yet you can step around the lattices.
OOO
OXO
OOO

I don't know how to fix this, but, you could perhaps make the lattice count as a "flooring" so when you stepped on it, you wouldn't slip and slide around.

**Comment by lcass** [comment]
Think this is a feature , part of the gravity system.

**Comment by ghost** [comment]
Feature.
