### ISSUE TITLE
Bug report-running into your own bullets

### ISSUE THREAD

**Issue by arotker1** [HippieStationArchive/HippieStation13-1#1290]
Bug details- if you move in the same direction as a shot you fired (taser bullet etc) you can hit yourself with your own bullet
how to reproduce- fire a bullet in the same direction that you're running

**Comment by TDcoolguy300** [comment]
Something with pixel projectiles, Crystal needs to see this

**Comment by trifornt-tinfornt** [comment]
Can confirm, stand still and then shoot a bullet and run at the same time. You'll hit yourself.

**Comment by Crystalwarrior** [comment]
Definitely a recent issue, going to look into it
EDIT: Cannot reproduce. Can you give us more information about what exactly did you do?
Projectiles by default cannot hit the firer in any case.

**Comment by Crystalwarrior** [comment]
Probably fixed, re-open if it occurs again.
