### ISSUE TITLE
chitonous armor prevents gibbing

### ISSUE THREAD

**Issue by arotker1** [HippieStationArchive/HippieStation13-1#1291]
issue- a changeling with chitonous armor on cant be stuffed into the gibber, as the game recognizes the chitonous armor as an abiotic item (either that, or the chitin acts like an exosuit in that you cant strip items underneath the chitin off (like jumpsuits).

**Comment by TDcoolguy300** [comment]
This is a feature technically, try cremating armored changlings rather than gibbing them

**Comment by TDcoolguy300** [comment]
#1066 Yes this is a feature
