### ISSUE TITLE
removing teeth with wirecutters is fucky

### ISSUE THREAD

**Issue by Crystalwarrior** [HippieStationArchive/HippieStation13-1#1314]
if you spam it on a dude, then pull him all the stacks of ripping it out convert into attacks, dealing lotsa damage. 
Secondly it goes through helmets and masks.

**Comment by Crystalwarrior** [comment]
wow whoever coded the wirecutters thing sucks ass don't you think guys

**Comment by danhibiki** [comment]
fuck you asshole teeth are awesome shit talk them one more time and you'll be joining goofball you muddafucka i dare u plz talk more shit plz

**Comment by Spacedong** [comment]
we gotta put dan hibiki down hes too dangerous hes like a rabid dog just look at him
