### ISSUE TITLE
The X-axis on ALL z-levels was somehow doubled to 510 instead of 255.

### ISSUE THREAD

**Issue by Weisyl** [HippieStationArchive/HippieStation13-1#1338]
Not much to say. Was messing around locally when I noticed that the Z-levels were far too big horizontally. This continued despite me restarting.

**Comment by Weisyl** [comment]
Additionally, all map files seem to be the exact same when looking at them in dreammaker. This only seems to happen during runtime.

**Comment by danhibiki** [comment]
I can't seem to see this live, is this for away missions?

**Comment by Carbonhell** [comment]
i heard a long time ago that if a map is set to something bigger than 255x255,all other maps get set aswell so that might be the issue,unsure

**Comment by danhibiki** [comment]
Would make sense, seeing as we just ported back in away missions. If someone could check the dimensions of each map, I'm sure we'll see one that exceed our limits.
