### ISSUE TITLE
Tracking Beacon microphones

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1343]
they do not work,but the speakers do

**Comment by Spacedong** [comment]
lmao who the fukk wud care bout this shit u autist

**Comment by TDcoolguy300** [comment]
Not a bug, intended in the code.

**Comment by carlarc** [comment]
remove the microphone then, it looks bad.
also how did this get ignored for so fucking long?

**Comment by Carbonhell** [comment]
Fixed in #2013
