### ISSUE TITLE
Martial Arts don't transfer to your clone when cloned

### ISSUE THREAD

**Issue by Crystalwarrior** [HippieStationArchive/HippieStation13-1#1350]
/title, needs fixing, @crystalwarrior get off your ass and fix it already JEEEEEEEEEEEEEZ

**Comment by danhibiki** [comment]
first wood teef now this

**Comment by SplergeBucket** [comment]
yeah this is a bug
or is it

**Comment by SplergeBucket** [comment]
????

**Comment by SplergeBucket** [comment]
yeah its a bug

**Comment by Nokington** [comment]
fix it you russian nerd

**Comment by Crystalwarrior** [comment]
holy shit how come I still didn't fix it
reminding myself to fix it asap

**Comment by Carbonhell** [comment]
@Crystalwarrior nerd

**Comment by Gandalf2k15** [comment]
this shit is outdated please remove
