### ISSUE TITLE
People can be healed by the cryopod without actually being in it.

### ISSUE THREAD

**Issue by Norzonion** [HippieStationArchive/HippieStation13-1#1357]
"If someone is in a wheelchair and you drag them to a cyro and turn it on then drag the wheel chair they will be in the wheel chair and the cyro will have no one in it but it still heals then and is working as if they were in it"

**Comment by Weisyl** [comment]
If this happens with wheelchairs then chances are this happens with every kind of chair.

**Comment by danhibiki** [comment]
We should test this with a swivel chair

**Comment by Crystalwarrior** [comment]
Cryo pods need to do a "buckled" check to solve this issue.
