### ISSUE TITLE
Large Beaker stuck to left hand

### ISSUE THREAD

**Issue by Higitus1** [HippieStationArchive/HippieStation13-1#136]
I broke into chemistry to make me some Tricordrazine due to a slime nearly killing me. I ejected the large beaker from the machine so I could put stuff into it to make a pill version of Tricordrazine. I don't think it worked as I had to use a different beaker to make the thing. Eventually I realized I could not drop up or throw it so I picked up a syringe with my other hand and dropped that one just fine. At this point I contacted the admin  Nebyab so I could get some help. The beaker behaved strangely and erratically. At one point I did manage to "drop" it but instead of appearing on the tile I was standing on it  showed up small and slightly above the swap button. I clicked on it and it picked it up again despite it supposedly being on the other side of the wall in a place I could not see. Later on when Nebyab put me into crit I was in a sleeper and it filled up with a pink liquid and when I got out it was gone again. It was only gotten rid of when Nebyab deleted all the large beakers in the station. I hope this bug report has been helps solve the problem.

**Comment by HoaxIT** [comment]
Byond issue, list corruption/memory corruption.

**Comment by WhiteFox08** [comment]
see #350
