### ISSUE TITLE
Plate armour is subsceptible to syringeguns

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1364]
how the fuck

**Comment by TDcoolguy300** [comment]
Not sure on what the flags are for no syringes, let me look at this

**Comment by Chronitonity** [comment]
They're children of riot armor so if they don't have protection neither does the riot armor.

Pretty sure crystal removed the "syringes cant go through armor" thing anyway even after I told him that it was a bad idea

**Comment by Crystalwarrior** [comment]
Huh?
I didn't touch it, though.
Definitely a /tg/ issue.

**Comment by danhibiki** [comment]
Nah, I remember it, its because of how we made patches work on hardsuits probably. That pull, at least
