### ISSUE TITLE
Missing piping not reaching the vents in vault security checkpoint

### ISSUE THREAD

**Issue by Crystalwarrior** [HippieStationArchive/HippieStation13-1#1367]
![](http://puu.sh/lKAwN/a963416859.png)
the piping doesn't reach the vent

**Comment by Kilmannan** [comment]
This appears to be connected in the current map version?

**Comment by Crystalwarrior** [comment]
Possibly fixed, needs to be confirmed though.

**Comment by Kilmannan** [comment]
As far as the map is concerned, it's connected. Will check in game.

**Comment by Pyko1** [comment]
It is connected all right on the picture as well.
The issue is that vent/scrubber connections are only visible when they are on plating.
Most likely since they don't have visible state like pipes do, and that is most likely used for this as well.

**Comment by Kilmannan** [comment]
Yep. This is all in order.
