### ISSUE TITLE
Failiure to handcuff.

### ISSUE THREAD

**Issue by Foosili** [HippieStationArchive/HippieStation13-1#1385]
So I joined the game and was immediately accosted by that SHIThead power gamer DAN HIBIKI when he throw a stun baton at me so I stunned him, attempted to cuff him with cablecuffs and the game told me IT FAILED TO CUFF. This is clearly a bug as I joined as an assistant lizard which isn't supposed to start with clumsyness.

Thank you for your time I hope you guys fix this soon.

**Comment by AliiTea** [comment]
This is hilarious

**Comment by danhibiki** [comment]
Feature A+++++++

**Comment by Spacedong** [comment]
when a fucking headmin does it its fine but when I do it its bad ok i see how this communist society works now

**Comment by danhibiki** [comment]
dan always badmins. always trust dan, right nex?

**Comment by AliiTea** [comment]
If you don't give logs I will continue to think this is a meme @Foosili

**Comment by danhibiki** [comment]
It happened, but I didn't see the fail message personally, I think he just canceled it himself. And I downed that dirty nonhuman fucked with my thrown baton like a pro

**Comment by Foosili** [comment]
I'm not fucking memeing here you FUCK

**Comment by AliiTea** [comment]
@Foosili logs please

**Comment by Foosili** [comment]
Hard since this was last night and I'm at work lmao, I gave you the exact conditions thathat facilitated this

**Comment by AliiTea** [comment]
Well I don't play lizard and haven't tested it yet so ree

**Comment by Foosili** [comment]
:downs:

**Comment by AliiTea** [comment]
You are being a meme ree

**Comment by doobiedoo23** [comment]
nexendia do you even play here

**Comment by AliiTea** [comment]
yes

**Comment by doobiedoo23** [comment]
no u don't?

**Comment by AliiTea** [comment]
I was on all last night
I was even made a vampire for the first time

**Comment by doobiedoo23** [comment]
doubt

**Comment by AliiTea** [comment]
Let me look into serber logs and I will show you.

**Comment by Spacedong** [comment]
close this fucking issue already

**Comment by TDcoolguy300** [comment]
No

**Comment by danhibiki** [comment]
Gonna tell ya this once spacedong, chill the fuck out
