### ISSUE TITLE
Syndicate melee mobs are borderline invulnerable

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#1400]
They are immune to all melee weapon attacks and all ranged laser/ballistic weaponry. For some reason the only way to kill them is through bare fists, high yield explosives, or throwing shit at them.

**Comment by Weisyl** [comment]
Chron checked the code and said they seemed fine, I can look at them in a test and see how they are.

**Comment by Weisyl** [comment]
Actually this is a confirmed issue.

**Comment by Chronitonity** [comment]
Got fixed iirc
