### ISSUE TITLE
Firelocks still block Brig doors

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1408]
![fuck](http://i.imgur.com/ztUoI6F.png)
![shit](http://i.imgur.com/d00gQ87.png)

Going from the hall to the lobby and the doors to the bottom right of the warden's office.

This should have been fixed when that atmos pipe was fixed ages ago, holy shit

**Comment by TDcoolguy300** [comment]
I dont think it's actually that they block it. They might actually be missing their open sprite.

**Comment by Kilmannan** [comment]
This is fixed in my latest brig PR which is awaiting approval

**Comment by Crystalwarrior** [comment]
I'm assuming this is fixed, then?
