### ISSUE TITLE
Mechs start at 20% charge

### ISSUE THREAD

**Issue by collinxchu** [HippieStationArchive/HippieStation13-1#141]
When inserting a new cell into any of the exosuits, you end up with 20% charge, regardless of the actual charge of the cell. Bears further investiation.

**Comment by lcass** [comment]
Found the solution to this , dont know if its a feature or not.
else if(istype(W, /obj/item/weapon/stock_parts/cell))
        if(state==4)
            if(!src.cell)
                var/obj/item/weapon/stock_parts/cell/C = W
                user << "You install the powercell"
                user.drop_item()
                C.forceMove(src)
                //C.use(C.charge \* 0.8)
                src.cell = C
                src.log_message("Powercell installed")
            else
                user << "There's already a powercell installed."
        return
should fix it if it needs fixing
