### ISSUE TITLE
/obj/effect/meatgrinder doesn't grind meat and doesn't delete itself

### ISSUE THREAD

**Issue by Foosili** [HippieStationArchive/HippieStation13-1#1412]
http://puu.sh/lPSkE/879fe01414.png

This thing doesn't work at all. You can click on it and it will say (name) triggered the meatgrinder! but you don't get gibbed and it doesn't delete itself.

**Comment by danhibiki** [comment]
When is this used ingame, or is this just something spawned?

**Comment by Crystalwarrior** [comment]
This issue needs to be elaborated, not sure what this is even.

**Comment by Chronitonity** [comment]
Its for the Wild West away mission, you click it and it kills you allowing your friends to go get dark and dangerous powers

**Comment by Kokojos** [comment]
The wild west mission is not implemented anymore If I recall recorrectly, plus it sucks balls.

Closing unless im told otherwise.
