### ISSUE TITLE
Remove the bedsheet/autolathe from the academy away mission

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#1414]
I was able to make surgery tools and take out my exile implant, leaving me able to wreak havoc on the station. This needs to be fixed.

**Comment by Weisyl** [comment]
I like the idea of people doing ghetto surgery to come back and kick their exiler's ass

**Comment by calibraptor** [comment]
To clarify, I was able to get onto the main station as an academy defender due to being able to create the tools for surgery from the autolathe and using the bedsheet that's on the map.

**Comment by Crystalwarrior** [comment]
This is absolutely fucking horrible and shouldn't be a thing fuuuuuuck

**Comment by Pyko1** [comment]
Just make the exile implant tamper proof with a chance of exploding with any failed implant removal surgeries.

**Comment by Chronitonity** [comment]
Away mission is disabled right now and i doubt it'll be enabled soon, so i'm gonna close this
