### ISSUE TITLE
Some inhand sprites are wonky (HoS overcoat, guitar)

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#1419]
http://i.imgur.com/wYXbOPn.png
http://i.imgur.com/jSENCvk.png

literally gamebreaking

This is just for the east and west-facing sprites, north and south are still a-okay
Probably a quick fix though

**Comment by Crystalwarrior** [comment]
We need to go over all left/right-hand inhands and check them out. I recall this issue existing for guitars, too.
