### ISSUE TITLE
When a Seclite Is in a Toolbelt, Backpack, or Attached to a Gun, the Icon to Activate Shows up but Does Nothing.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1424]
![fuck](http://i.imgur.com/XzTNrni.png)

The icon to the right of the gun shouldn't show up when in toolbelts, backpacks, or when attached to the gun since it does nothing. The gun icon works fine, but it isn't removing the second icon for some reason.

**Comment by danhibiki** [comment]
Having the icon scaled out like that indicated you have it on your person, and is intended. However, if the seclite is duplicated while also being on your taser, thats unintended.

**Comment by Crystalwarrior** [comment]
The reason why it happens is that the seclite is inside the gun, and once I fixed the bug where jetpacks inside hardsuits weren't giving you action button, now the code checks for action buttons inside all items on-person.
iirc there's a variable to make sure it doesn't show you action buttons for items inside other items.

**Comment by Gandalf2k15** [comment]
This is not really an issue.

**Comment by Kokojos** [comment]
It's now shown as red so that you know you can't use it*.
