### ISSUE TITLE
Using the suicide verb with rope does not add suicide flag on body

### ISSUE THREAD

**Issue by myontasm** [HippieStationArchive/HippieStation13-1#1425]
Gamebreaking.
![image](https://cloud.githubusercontent.com/assets/10575508/11755672/51c87c24-a054-11e5-9b96-ca0dc220924a.png)
![image](https://cloud.githubusercontent.com/assets/10575508/11755690/6cbf8932-a054-11e5-9d40-00e36f5b4a77.png)

**Comment by Crystalwarrior** [comment]
Suicide flag is actually broken for suicide verb in general. Oops.

**Comment by Nokington** [comment]
someone fix this because it should come up with the suicde flag

**Comment by Carbonhell** [comment]
Suicide flag works,the issue is when you drag yourself on the noose, but suiciding with cables works so...

**Comment by Spacedong** [comment]
wait what the fuck was this even here in the first place? close this I don't think its a bug

**Comment by Nebyab** [comment]
was this fixed?

**Comment by Crystalwarrior** [comment]
nope :V

**Comment by Crystalwarrior** [comment]
It's a problem with the fact that you're "restrained" as soon as you commit suicide with the rope.

**Comment by myontasm** [comment]
And it still hasn't been fixed ;(

**Comment by Gandalf2k15** [comment]
should be fixed in https://github.com/HippieStationCode/HippieStation13/pull/2491
