### ISSUE TITLE
youtool not working with assistant ID

### ISSUE THREAD

**Issue by account-name** [HippieStationArchive/HippieStation13-1#1429]
what the fuck

**Comment by Chronitonity** [comment]
oh whoops, i'll get to this at some point

**Comment by Spacedong** [comment]
fix this shit already, NOW, ruins every assistant round

**Comment by Chronitonity** [comment]
Chill.

**Comment by nalarmg** [comment]
@Spacedong Please do not be hostile towards coders, especially after one's offered to fix something. If you'd like something fixed faster, please feel free to stop by coderbus. We'd love to have you help out!
