### ISSUE TITLE
Canegun is borked

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1430]
When you try interacting with the canegun, it tries to reskin itself like a doublebarrel with the same menu. You click any of the options and it turns invisible.

**Comment by TDcoolguy300** [comment]
It's my code so i will be checking this out, but during the initial tests before i even PR'd it worked fine

**Comment by TDcoolguy300** [comment]
Alright, it's working fine directly on the server, so this issue is basicly non-existant, however i found a completely unrelated bug with the change option anyways, so i will quickly make a fix for it
