### ISSUE TITLE
Changelings cough while dead

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#1439]
This is a big giveaway as to whether somebody is a ling or not.

**Comment by Chronitonity** [comment]
can confirm this happens, thought it was already reported @crystalwarrior

**Comment by Crystalwarrior** [comment]
...what the fuck?
h-how is this even-
doesn't changeling death still give them DEAD status???

**Comment by SplergeBucket** [comment]
clearly just a ling's death throes feature is indeedntended

**Comment by nalarmg** [comment]
Unable to reproduce locally whilst regenerating, and whilst actually dead. Can anyone verify this is still a thing and/or provide more information?
