### ISSUE TITLE
REGARDING THE NEW ARRIVALS

### ISSUE THREAD

**Issue by account-name** [HippieStationArchive/HippieStation13-1#1447]
THERE ARE **SPACE TILES** UNDER THE FUCKING ARRIVAL SHUTTLE DOORS, YOU CAN'T WALK THROUGH THE **OPEN FUCKING SHUTTERS** SOMEONE FIX THIS SHIT

**Comment by Weisyl** [comment]
The space tiles have been fixed in a recent PR that was merged, might have to be compiled server-side. Although nobody's reported the open shutters blocking people despite being open.

**Comment by Spacedong** [comment]
oh my god stop hiring this newbie mapper this is horrendous

**Comment by ghost** [comment]
u shud learn 2map spaecgogng

**Comment by Chronitonity** [comment]
Spacedong bud if you want to give some constructive criticism feel free too, but if you want to look like a huge child you can do it elsewhere thanks.

**Comment by Kilmannan** [comment]
I've not seen or heard issues with the shutters - watched dozens of people walk through them. I have had this happen before at other shutters on the station so don't know if it might be a bug with the shutters that crops up from time to time.

Once again, apologies for the issues with it, still learning and picking things up. At least I got the scrubbers and air pipes right this time! (If you don't count the space tiles!)

**Comment by account-name** [comment]
i'm not spacedong i'm memerung you cucks
fuck you chron

**Comment by Kilmannan** [comment]
Open shutters are a bug - if set to open in instance, object appears open but can't been seen through nor passed through. If you then open it, it executes open animation. Reported elsewhere.
https://github.com/HippieStationCode/HippieStation13/issues/1460

Space tiles all fixed.
