### ISSUE TITLE
Overlays are ~fucked~

### ISSUE THREAD

**Issue by WhiteFox08** [HippieStationArchive/HippieStation13-1#145]
Happens only after the Radiation storm overlay takes place.

![bzaw9zc](https://cloud.githubusercontent.com/assets/2702850/7792103/66860c9c-0272-11e5-9703-b47a81c03fbf.jpg)
![dlvdwvb](https://cloud.githubusercontent.com/assets/2702850/7792105/683a8176-0272-11e5-8a12-5b32d9408bce.jpg)

**Comment by lcass** [comment]
Does this only occur with beepsky or are there other artifacts aswell?

**Comment by Cairo283** [comment]
I've only seen it occur on beepsky, but it seems to happen every time a rad storm ends.

Personally, I like the idea of beepsky having a giant fuck-off red glow around him. Gotta show of that he _is_ the law.

**Comment by AliiTea** [comment]
The radiation fries his lighting circuits which makes him emit a solid blood red light around him.

**Comment by AliiTea** [comment]
Totally a feature

**Comment by Crystalwarrior** [comment]
B-but beepsky deserves no such treatment! :(

-edit-

This fool must learn to fear beepsky!!

![](http://wiki.ss13.ru/images/1/1f/Beepsky.png)

**Comment by ghost** [comment]
Happens to walls, dark spots, borgs.

**Comment by lcass** [comment]
Ill take a look , if not ill have to leave it to another person,

**Comment by Higitus1** [comment]
I think it also happens a the bridge consoles.

**Comment by Kokojos** [comment]
Fixed when radstorm overlay was removed
