### ISSUE TITLE
Shutters set to open look open, but aren't

### ISSUE THREAD

**Issue by Kilmannan** [HippieStationArchive/HippieStation13-1#1460]
If you set the shutter instance to 'Open' it starts with the sprite showing the object as open, but in fact, it's not and it's not passable.

Can't recall who mentioned this, but I just went and checked and aye, it's confirmed. Can we get a fix on this at all?

At the new arrivals, green lane has this very bug, and if you then hit the shutter button, you see the shutters actually open and they become passable.

**Comment by TrashFiend** [comment]
Yo this needs to be fixed stat. Nobody can get into the station until the shutters are opened unless they break windows or go through maint

**Comment by danhibiki** [comment]
Temporarily removed, so fixed sortof?
