### ISSUE TITLE
Stun batons dont seem to be affected by the ion rifle

### ISSUE THREAD

**Issue by lcass** [HippieStationArchive/HippieStation13-1#148]
Have another person holding a stun baton , shoot them with the ion rifle. Bam they can still stun you.

**Comment by Carbonhell** [comment]
This is normal, EMPs just drain 10% charge from a stunbaton,unlike the entire energy like it happens with eguns etc, not a bug

**Comment by AliiTea** [comment]
not a bug thus closed
