### ISSUE TITLE
I'm not using any custom skins.

### ISSUE THREAD

**Issue by Majotime** [HippieStationArchive/HippieStation13-1#1485]
"Unable to access asset cache browser, if you are using a custom skin file, please allow DS to download the updated version, if you are not, then make a bug report. This is not a critical issue but can cause issues with resource downloading, as it is impossible to know when extra resources arrived to you."

**Comment by TDcoolguy300** [comment]
This is a known issue, it's best to just ignore the message at this time. Also those extra resources should still be going your way

**Comment by Spacedong** [comment]
close this
