### ISSUE TITLE
Mining ripley sometimes unrepairable.

### ISSUE THREAD

**Issue by Krain7k** [HippieStationArchive/HippieStation13-1#1537]
It looks like it depends on it's set of equipment. I could never repair a mining ripley which had a default set of items: usual exosuit drill, hydraulic clamp and a mining scanner. I've tried to weld it when it's maintenance protocols were enabled or disabled, when it's ID panel was locked or unlocked, tried all the possible combinations of those. It only damaged the ripley furthermore. However, the ripley with diamond drill and/or heavy plasma cutter can be repaired just fine, you don't even have to tamper with the maintenance protocols and stuff.

**Comment by TDcoolguy300** [comment]
Was your intent set to harm at all?

**Comment by Krain7k** [comment]
Don't think so. I don't usually change intents when mining. Altough i wasn't paying attention.

**Comment by TDcoolguy300** [comment]
That could be it, in the code you can still attack mechs with a welder should your intent be on harm

**Comment by TDcoolguy300** [comment]
Just tested it with a standard-equiped mining ripley, no sign of this bug.

**Comment by Krain7k** [comment]
Oh, you know what. You're probably right. I do change intents because i squeeze things with clamp. My bad. I'm retarded.
