### ISSUE TITLE
Brig door has weird access

### ISSUE THREAD

**Issue by TDcoolguy300** [HippieStationArchive/HippieStation13-1#1547]
The brig doors in the top left are not the same, the bottom of the two has different access than the one on the top

![image](http://puu.sh/maUOg/bbfc49ba18.png?raw)

**Comment by danhibiki** [comment]
I believe this was fixed recently?

**Comment by Kilmannan** [comment]
Yes. Both changed yo same access level

**Comment by Kilmannan** [comment]
This has been fixed, but it's sat in my PR waiting to get taken on.

**Comment by Kilmannan** [comment]
Is now fixed
