### ISSUE TITLE
Slime Processor Bugged

### ISSUE THREAD

**Issue by WarfaceAlex** [HippieStationArchive/HippieStation13-1#155]

**Comment by lcass** [comment]
Similar things occur for the gibber , however this often happens without a power failure. Just to note.

**Comment by Cairo283** [comment]
On a related note, when moving vending machines from an un-powered area to an area with power, said vending machine won't turn back on once secured to the floor unless totally re-constructed.

**Comment by WhiteFox08** [comment]
Feature
