### ISSUE TITLE
Revenant is borked(maybe)

### ISSUE THREAD

**Issue by Nokington** [HippieStationArchive/HippieStation13-1#1560]
This button was removed from the preferences tab which was the only way for the revenant event to work. Players would have to set it to revenant and then they would get selected when it fired. That was really its only purpose from before but it would be nice for it to come back so the revenant event will work.

**Comment by Nokington** [comment]
Or just make it so revenant can happen without the extra step of players needing to set the specialrole. Just make it like a popup for dead players.

**Comment by Nokington** [comment]
The other day I saw a revenant but I don't know if it was admin spawned or not. I don't know if there is some other way to become one or not.

**Comment by Kokojos** [comment]
fixed in #1712
