### ISSUE TITLE
Brig Office Shutters overlap the sliding glass door.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1565]
![balls](http://i.imgur.com/HELjszj.png)

aaaaaaaaa you cant click this

**Comment by TDcoolguy300** [comment]
Did you actually have access to the windoor?

**Comment by TrashFiend** [comment]
Yes, was Captain

The problem is there are about 5 pixels you can click on the top windoor to actually have it open. The shutters cover most of it.

Should have said it was for the top door.

**Comment by TDcoolguy300** [comment]
That makes it much clearer

**Comment by Kilmannan** [comment]
I've had a look at that - the shutters wont reposition themselves on a lower setting - the R&D desk is the same, but the Brig desk is the only one that has shutters on both sides. You can still do it with an alt-click on the table, but I'll need to play with the layer setting to see if that has any impact on it.
