### ISSUE TITLE
You can use items when turned into a statue by the wizard.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#157]
When you get turned into a statue by the wizard, you can still use any items in your possession. This includes shit like PDAs and I assume megaphones. You can't do some stuff like drop/throw items, construct things, or turn on/off some items. Not sure how big of an issue this is but should be addressed.

**Comment by lcass** [comment]
Eh , probably an easy fix . I might just make it paralyze the person until the stone is done.

**Comment by Carbonhell** [comment]
It was fixed but this issue wasn't closed. Can anyone kindly close it?
