### ISSUE TITLE
Theater Storage has bad wall placement and half the floor is broken.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1578]
![fuck](http://i.imgur.com/KCbk1hR.png)

The two walls on the left don't connect and look dumb. The top two rows of floor tiles are completely wrong. All looks a bit shit.

**Comment by Spacedong** [comment]
JESUS THAT'S BAD

**Comment by Kokojos** [comment]
I admit it dosen't look amazing and il move the wall.

**Comment by Kilmannan** [comment]
![image](https://cloud.githubusercontent.com/assets/16103614/12074638/62fd7bb2-b156-11e5-8d1d-64c681fa863d.png)

**Comment by Kokojos** [comment]
Been fixed, closing.
