### ISSUE TITLE
(SERVER LAGGING/CRASHING) Glitch with smoke grenades containing black powder and chlorine trifluoride

### ISSUE THREAD

**Issue by KayeArray** [HippieStationArchive/HippieStation13-1#1584]
For whatever reason any smoke grenade containing black powder and chlorine trifluoride causes an odd reaction which spams loads of invisible hotspots (which can be seen by right clicking) which lag the damage system along with other server elements before causing several client crashes and then a server crash.

**Comment by AliiTea** [comment]
Anyone looking into this?

**Comment by PKPenguin321** [comment]
i think /tg/ may have had an issue very similar to this one, if nobody fixes this soon you might want to hop into coderbus and ask around

**Comment by danhibiki** [comment]
Thanks for the heads up!

**Comment by Carbonhell** [comment]
Tested the bug,only 6-7 hotspot spawned and i didn't notice any lag nor any major issue

**Comment by Carbonhell** [comment]
still waiting for any feedback since 3 months ayy lmao

**Comment by Carbonhell** [comment]
^
