### ISSUE TITLE
cheap russian piece of shit security escape pod

### ISSUE THREAD

**Issue by SplergeBucket** [HippieStationArchive/HippieStation13-1#1593]
![](http://puu.sh/mhIv4/c40a687a47.png)

this is a design flaw

**Comment by Kokojos** [comment]
What z-level is this on, again?
I need to remake some z-level stuff :3

**Comment by SplergeBucket** [comment]
this is the security escape pod
on the station
which was edited
yet the eject zone or something wasnt ejected 
needs 2 be fixed

**Comment by Kilmannan** [comment]
Ahaha, wait, the ship left but not all of it?? Goddamn those Russian fucks.

**Comment by XeonFaux** [comment]
I was able to fix this by changing the height/width dimensions of the docking port, will be making a pull request soon.

**Comment by Kilmannan** [comment]
I think it's more because I didn't set the 'area' for all of the ship. Checking it now.

**Comment by XeonFaux** [comment]
Am testing it at the moment.

**Comment by Kilmannan** [comment]
Are you on chat mate? I've had a look, it's not the area, it is set around the ship properly. Let me know what your fix is, I'll incorporate it into the PR I've got waiting merge just now if you like, I've got a few more fixes to stick in.

**Comment by Kilmannan** [comment]
Well, if it's the station Z level, if not, fill your boots.

**Comment by XeonFaux** [comment]
Yea, I was able to successfully fix this. Also what chat?

**Comment by Kilmannan** [comment]
https://hippiestation13.slack.com/messages/general/
