### ISSUE TITLE
Changeling objective

### ISSUE THREAD

**Issue by Nokington** [HippieStationArchive/HippieStation13-1#1605]
Have your targets ID and be said target while escaping. The most bullshit objective ever as you are completely fucked if your target gibs themselves at round start via bible/bomb etc.

**Comment by Nebyab** [comment]
Its a bit of a dumb objective

**Comment by Weisyl** [comment]
How to very easily fuck lings with this objective:
1. Throw your ID in a random locker.
2. Space the ID.
3. Cremate the ID.
4. Deep-fry the ID.
Very fair yes indeedy friend.

**Comment by SplergeBucket** [comment]
Lings have dumb, shitty, and hard objectives to accomplish.
Most of them, like most other hard objectives (barring the hijack shuttle and capture AI) require you to do it at round-start; personally I like to think of the objectives as guides for what you can do, so tbh iunno about changing it

**Comment by blobbernaut** [comment]
If they have their ID fucked, you can make another at the HOP office if you have access, that counts doesn't it?

If so, I think the bigger issue is how re-adapting sometimes removes hivemind and hive absorb forever.

**Comment by Nokington** [comment]
No, I don't think so. And even if it did you still have to be transformed as them. And yes re-adapt is also a very big problem.

**Comment by Nokington** [comment]
I made this issue, other heads pls respond

**Comment by Carbonhell** [comment]
Needs head discussion as the tag says,still waiting for that discussion to happen,should the objective be just plain removed, or tweaked,if the latter,how.

**Comment by doobiedoo23** [comment]
Shit objective. Let's replace it with something else.

**Comment by Nokington** [comment]
wew lad about time some other people actually post in this

**Comment by Crystalwarrior** [comment]
It's a terrible objective. I think it should be "Pose as X" at most, the ID requirement is bullshit.

**Comment by Carbonhell** [comment]
hol up i'm an idiot,this isn't a bug,it's a shit feature,so it belongs to the forum to be honest
