### ISSUE TITLE
Singu turning itself off randomly

### ISSUE THREAD

**Issue by Caxxo1** [HippieStationArchive/HippieStation13-1#161]
The singu console will sometimes turn the singu off. I don't know what triggers it, it seems random to me.

**Comment by ghost** [comment]
Unable to reproduce, needs more information.

**Comment by lcass** [comment]
Do you mean the singularity console power was turned off? This is very bare we can't really do anything. You sure you didn't just turn the power off?

**Comment by Kokojos** [comment]
Deeming an accident : Probably the AI or some assistant that turned it down.
