### ISSUE TITLE
Canegun is still borked.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1618]
For some reason this got closed, take a canegun in one hand, switch hands with it and you get the double-barrel shotgun reskin menu. Select anything but cancel and it will become invisible and thus can't be loaded or effectively used.

Pls fix.

**Comment by TDcoolguy300** [comment]
I'll take a look, the previous issue was with it not being able to reskin at all

**Comment by TDcoolguy300** [comment]
Yeah i found the issue, fixing it now
