### ISSUE TITLE
Nonexistent guns show up when examining a person

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#1620]
Picture of person when examining: http://i.imgur.com/6BdFkP3.png
His inventory: http://i.imgur.com/1RzoRuI.png

**Comment by Kokojos** [comment]
Any idea how this happened?

**Comment by TDcoolguy300** [comment]
It's possible for mindbreaker to put shit onto people, and well that could happen.

**Comment by McHatters** [comment]
It was a wizard round, and I'm pretty sure I wasn't high on mindbreaker. Wiz summoned guns, so he may have had the weapon before he got put into crit. However, I didn't find anything on him when I looted his body.

**Comment by TDcoolguy300** [comment]
Strange

**Comment by ghost** [comment]
I know what this is, I found the corpse later in the round.

He had the gun in his belt slot, but no jumpsuit. I put a jumpsuit ON him and then I could access the gun. Still a bug, just a different one.

**Comment by TDcoolguy300** [comment]
Then it was a freak occurrence, i have no idea how he could of possibly lost his jumpsuit without it dropping the belt item

**Comment by danhibiki** [comment]
fire maybe? burnable jumpsuit, nonburnable gun

**Comment by TDcoolguy300** [comment]
Fire burning should be calling Qdel, and even then it will drop the gun

**Comment by McHatters** [comment]
Weird.

**Comment by TDcoolguy300** [comment]
Now that i think of it, only something that could be potentially calling Del() instead of qdel directly could cause this to theoretically happen. But otherwise not possible to reproduce.

**Comment by McHatters** [comment]
Could it possibly have something to do with the C05-R instead?

**Comment by TDcoolguy300** [comment]
No, this issue is more apparent when the jumpsuit disappears, as it should be dropping ANYTHING in the belt slot, however there might be a thing with cursed items.

**Comment by Pyko1** [comment]
I recall some guy in isolation having a pda in their belt slot, and i had to put an uniform on them to take it away.

So you can put things on belt slot when naked, but can only strip it if they have uniform?

**Comment by Pyko1** [comment]
![capture](https://cloud.githubusercontent.com/assets/12048747/13629746/d2ea9a56-e5e3-11e5-9114-11250f498e81.PNG)
Yeah, confirmed it. you can put stuff in belt slot without uniform, but it cant be taken out by others until you wear uniform.
