### ISSUE TITLE
Lawyers don't have access to the Brig Cell Corridor, but can still get in through a roundabout way.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1625]
Lawyers don't get to use the doors from the lobby of security to get into the Brig Cell Corridor, but can go through the doors at the top of that corridor.

They should just have access to the cell corridor anyhow.

**Comment by Nokington** [comment]
They can use the top door but not the bottom door in the lobby.

**Comment by TrashFiend** [comment]
That's even worse!

**Comment by Nokington** [comment]
Yeah its pretty dumb
