### ISSUE TITLE
When the AI camera is on an area without camera coverage, the AI cannot use some equipment (APC/SMES/Air Alarm)

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1626]
Noticed this one one where, if you tried to use an APC or SMES with your camera centered on a tile that doesn't have camera coverage, you can't use the equipment. Really weird bug, doesn't affect doors or computers or anything.

It may be a Nano UI thing since all of these objects use Nano UI, and old UI is fine.

Also the AI can click a Protolathe to make it spark. Why?

**Comment by TrashFiend** [comment]
Or wait, this isn't true.

Sometimes this equipment will just not work at all.

**Comment by danhibiki** [comment]
yeah, its a nano ui issue, and i need to get up to date with TGs basically.

**Comment by trifornt-tinfornt** [comment]
One of these areas is the HoP APC. You used to be able to access them, but now with NanoUI you can't.

**Comment by danhibiki** [comment]
Fairly certain this is fixed

**Comment by Kokojos** [comment]
Fixed with recent updates.
