### ISSUE TITLE
The Twilight Zone

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1638]
So just now I used the stargate to get back from the meteor away mission. It took me to a black screen. Nothing at all on it. Admins couldn't jump to me, I was free to pull things out of my bag and use stuff, but all the tiles were just empty blackness.
![its dark here](https://cloud.githubusercontent.com/assets/16275811/12227556/3f0b0aae-b826-11e5-84e6-7c8e8ae52246.png)

I hope the screenshot attached right.

**Comment by TDcoolguy300** [comment]
Now, i know this issue. It's a freak occurance but your stuck in Z-0 or something, basically a non-existent area. However, your still an object and not removed from play, so when this does occur, just ask an Admin to Teleport you

**Comment by Pyko1** [comment]
Somehow you entered in 0.0.0 but this should not be an issue anymore since we don't even have away missions at the moment, if we ever add them back and this issue re-arrives make a new report or open this. Closing.
