### ISSUE TITLE
Chaos Holoparas TP to Bluespace Reciever

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1640]
As in the title. Chaos holoparasite's random teleport attack seems to teleport people to bluespace recieving pads.

So in this case, we have 5-6 braindeads and corpses in mining.

![image](https://cloud.githubusercontent.com/assets/16275811/12228578/670cddfc-b835-11e5-801a-4fbb83f2c26a.png)

**Comment by Pyko1** [comment]
Still a thing, can anyone confirm?

**Comment by Carbonhell** [comment]
Wait,isn't the bluespace receiver made exactly for them?They can also make them no?How is this an issue?

**Comment by Pyko1** [comment]
yeah, this is workign as intended.
