### ISSUE TITLE
Tesla

### ISSUE THREAD

**Issue by Nokington** [HippieStationArchive/HippieStation13-1#1649]
Someone touched the tesla it insta gibbed them. Their holoparasite was still alive and then went into limbo. Then the MC shut down.

**Comment by TDcoolguy300** [comment]
Interesting

**Comment by Carbonhell** [comment]
Doesn't gib anymore,it now einaths on bump only...So i guess bug fixed?

**Comment by XeonFaux** [comment]
Fixed please close.
