### ISSUE TITLE
Random scrubbers pipes under windows in Vault Security Checkpoint

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1650]
![fuck](http://i.imgur.com/wAQIZ4c.png)

The left and right window both have scrubber pipes that aren't connected to anything. As far as I know they don't exist under any other tiles. Odd!

**Comment by Pyko1** [comment]
Fixed: https://github.com/HippieStationCode/HippieStation13/pull/1679

**Comment by XeonFaux** [comment]
Fixed please close.
