### ISSUE TITLE
Ghosts can enable borg floaters

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#1658]
As the title suggests.
As a ghost, orbit a stationary borg and click and drag its sprit onto an adjacent tile.
It'll act as if it's activating the borg's floaters and move the borg onto said tile.

Ask Nex, he's been a victim of this.

Dunno if this proves anything - http://i.imgur.com/Uw8cEMa.jpg

Edit: This also works with deactivated borgs.

Edit2: You dont need to be oribiting them, if you're on the tile next to them, you can move them 2 tiles from their original position

Edit3: If you're standing on an airlock, and the borg is on one side of the airlock, you can teleport it to the other side.

**Comment by trifornt-tinfornt** [comment]
Can confirm, just tested it in-game. It even plays the pool sound.

**Comment by TDcoolguy300** [comment]
I'll check this out

**Comment by Kokojos** [comment]
_Shame_

**Comment by Kokojos** [comment]
This is still an issue because revert

**Comment by Pyko1** [comment]
Same as https://github.com/HippieStationCode/HippieStation13/issues/1789. Closing.
