### ISSUE TITLE
You can make the shuttle dock at CC in 10 seconds

### ISSUE THREAD

**Issue by killer653** [HippieStationArchive/HippieStation13-1#167]
Problem: You can send the shuttle while it is midway in flight, making it dock in 10 seconds at CC.

How to reproduce: Swipe 2 id's on the shuttle console, then click it with the third id and wait (If done correctly, there should be 1 auth left and you should have  the GUI for swiping your id up). When the shuttle launches, swipe the last id needed and watch as the shuttle docks at centcomm in 10 seconds.

**Comment by lcass** [comment]
alright , ill give it a look.

**Comment by Nokington** [comment]
Fixed
