### ISSUE TITLE
A few suicide types aren't working

### ISSUE THREAD

**Issue by atomicpeace** [HippieStationArchive/HippieStation13-1#1675]
I've noticed a couple suicide types aren't working.

Namely, the ones I've seen, are the Shovel, and the Detective's revolver.

When you suicide, it shows the message, but nothing occurs. Except with the detective's revolver, you get knocked down, but don't die.

**Comment by ghost** [comment]
A lot of brute items seem to be broken as well, such as oxygen tanks(I believe)
