### ISSUE TITLE
Bugged genetics. Monkeys not turning back to humans.

### ISSUE THREAD

**Issue by Theoman02** [HippieStationArchive/HippieStation13-1#1690]
Hey guys, this issue has been persisting since yesterday, 20/01, where in genetics you can't turn someone back from a monkey, or just a monkey in general, to a human. SEs are all below 8 and the subject is still a monkey.

Here's some proof: http://puu.sh/mEsa6/b6cf97d5eb.png

**Comment by danhibiki** [comment]
Strange, I've seen people transform back from monkey using injectors, could you give more information?

**Comment by Theoman02** [comment]
I've just tried to inject a clean SE to a monkey right now, and it hasn't turned it to a human. I tried with UI and UE as well for good measure and still nothing happened. I checked, the SE is clean, with everything below 8. Yesterday we had someone that i monkeyfied on accident, as in, a player, and it still wouldn't do anything, despite injecting him multiple times with a DNA injector.
