### ISSUE TITLE
Owl Hardsuit doesn't protect from kPa

### ISSUE THREAD

**Issue by Nepon** [HippieStationArchive/HippieStation13-1#1706]
It was the first time i saw it so i don't know if it would protect from kPa anyway.

http://prntscr.com/9tkl2d

**Comment by AliiTea** [comment]
It does

**Comment by Nepon** [comment]
It didn't protected me this time, and didn't let me remove, so i died.

**Comment by ArcLumin** [comment]
You have to toggle the helmet mode from combat to travel, like a nuke op hardsuit

**Comment by FuryMcFlurry** [comment]
I equiped and examine it is said travel mode
Will try again however

**Comment by Nepon** [comment]
I equiped the helmet too, but didn't protected.

**Comment by ArcLumin** [comment]
Just tested it, it protects from pressure still. You've just gotta toggle the helmet mode once the helm is on

**Comment by ghost** [comment]
Wings up means It's in travel mode, AKA kPA protection. Wings down means combat I believe.

**Comment by Pyko1** [comment]
So not a bug, closing.
