### ISSUE TITLE
Massive increase in resource use for some players

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#1718]
Ever since an update a couple days ago, many players have been reporting using far more resources than before, input lag, huge fps drops, etc. It's been said all over OOC for the past couple of days, and does make it difficult to play for some people. I have not confirmed if this is true for all players, or just some, but I've been seeing all over OOC (As well as for myself) a huge drop in performance since the "Performance fixes" from a few days ago.

**Comment by TrashFiend** [comment]
Yeah, the fps drops dramatically at the start of the round and keeps going for 30 seconds or so, both before and after the (old) lag spike. It appears to happen mid-round as well, Cultist round had multiple points where it dropped to near-unplayable levels constantly nearing the end, with 10 or so seconds between minutes of it happening.

It's really fucked

**Comment by Pyko1** [comment]
There are rumours floating around that some NTSL scripts are used to lag server, might be worth checkign what has been uploaded when it lags heavily.

**Comment by TrashFiend** [comment]
NTSL's problem was some script that would loop itself forever (maybe not even needing to send/receive messages?) and lag shit up. When the console is deconstructed when it happens it goes away. A few shitlers did it earlier today.

/tg/ removed NTSL entirely, but I think Paradise overhauled it a while back. Might be worth looking at what they're doing to see if the same problems exist there.

**Comment by TrashFiend** [comment]
Well, given what is happening at the moment, you can simply spam the max amount of text over radio and make the server go to shit. If you manage to make NTSL do a loop, you can make it happen automatically with a script.

**Comment by XeonFaux** [comment]
NTSL is being updated, will be up dated by the day end at the latest.

**Comment by Kokojos** [comment]
Been ''fixed'' with the recent revert.
