### ISSUE TITLE
Smoke powder not reacting inside people.

### ISSUE THREAD

**Issue by KayeArray** [HippieStationArchive/HippieStation13-1#1730]
Unlike other chems when smoke powder gets inside someone who is hot enough to cause it to react nothing happens.

**Comment by EldritchCrow** [comment]
What would smoke powder even do inside a person? Also, the pressure the reaction would make inside the body is probably enough to explai irl why it wouldn't react.

**Comment by KayeArray** [comment]
This isn't real life. Unless a deliberate change has been made in the code smoke powder should react like any other chem when heated inside a body.

**Comment by EldritchCrow** [comment]
Ok fine... But then what would smoke powder do if it reacted inside of the body? You would probably just get a gas problem and start farting smoke. Huge improvement.

**Comment by danhibiki** [comment]
Smoke doesn't trigger in body, and its probably for the best too because i'm pretty sure it takes all the other reagents out when it creates the smoke, so it would be a ridiculously easy way to purge chemicals safely.

**Comment by EldritchCrow** [comment]
I'm pretty sure you're right, and it does remove all of the chems.

**Comment by KayeArray** [comment]
I was thinking more along the lines of infinite plasma smoke but w/e.

**Comment by Nebyab** [comment]
According to Dan, not a bug and working as intended

**Comment by Pyko1** [comment]
2 heads say its a feature, closing.
