### ISSUE TITLE
Chemtank explosions aren't properly logged

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#1735]
Either I'm retarded and can't find the chemtank logs, or they're not logged at all.

When a chemtank explosion occurs there is a pop-up in the admin chat that there was an explosion and where the explosion occurred, but not who triggered it.

**Comment by Jaygriff** [comment]
Looks like chemtank explosions that are triggered by bullets are logged.. Are we talking about with a welder in this bug?
