### ISSUE TITLE
Nuclear Operatives can emag into the BlastCo room

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#1736]
Emagging the button allows you access to all the gear at the measly cost of 6 TC.

**Comment by ArcLumin** [comment]
Yup. Common knowledge too. Easiest fix would likely be a computer console to open it, but even then, blowing up the wall to get in works too. Additionally, you can emag the shuttle doors to leave without the leader

**Comment by ghost** [comment]
Yet another shit-tier /tg/ port. Is this still in with the revert?

**Comment by doobiedoo23** [comment]
BlastCo wasn't a /tg/ port mate, it was chron's thing but he's dead so idk

**Comment by ArcLumin** [comment]
Best fix would be a computer console used to open it with the ID, and indestructible walls around the blastco room to prevent c4ing in

**Comment by XeonFaux** [comment]
Or just make the button emag proof and the walls indestructible walls

**Comment by Pyko1** [comment]
Fixed in: https://github.com/HippieStationCode/HippieStation13/pull/1749
