### ISSUE TITLE
Cleaning an Engineering Hardsuit (or any hardsuit with attached helmet probably) does not clean the helmet.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1743]
If you put an engineering hardsuit covered in blood in a sink, it will clean the body just fine but the helmet will stay dirty. Trying to clean blood off fully is impossible unless you have soap in this case.

**Comment by ArcLumin** [comment]
Space cleaner and aiming for the head will do the job. And taking a shower. But no, you can't clean in it a sink.

**Comment by Pyko1** [comment]
a feature?

**Comment by TrashFiend** [comment]
Wouldn't call it a feature. At any rate it's an unintended annoyance.

**Comment by TDcoolguy300** [comment]
It's due to the helmet being a physical part of the suit, a stupid fix would be to have the sink also clean any items within the item that was washed.

**Comment by TrashFiend** [comment]
Can't you make it clean the items but only if they're inside of clothing items? Not sure how that'd work but it should do everything from helmets to scarves to medals like it should.

**Comment by TDcoolguy300** [comment]
Maybe, but this is a minor issue none the less

**Comment by Pyko1** [comment]
I'll add a bug. The helmet should be cleaned if the suit is cleaned as its a physical part of it.
Maybe add a var connected items /list for items that have connected items such as harduits/janitor water tank/defib.

**Comment by JohnGinnane** [comment]
I have fixed this in #2110
