### ISSUE TITLE
Embedding

### ISSUE THREAD

**Issue by XeonFaux** [HippieStationArchive/HippieStation13-1#1745]
Just thought I'd put this here for now so I don't forget it. Embedding in no gravity, causes embedding objects to be unremovable from the player. Also the embedding object is still on the ground after embedding as if it just hit the player.

**Comment by ArcLumin** [comment]
Embedding can also be abused using Wizard's recall spell. Throwing an item, and letting it embed, then recalling it leaves a "ghost" unremovable version of that item in someone, and the weapon back in their hand. Everyone's fucked if the wiz gets a combat knife.

**Comment by Carbonhell** [comment]
fix seems pretty easy to do,just throw a location check in human life proc?

**Comment by ArcLumin** [comment]
Just did an embed test with TK. If you embed someone with TK, you can then table the item, producing the same cloned "Ghost" unremovable items within someone.

**Comment by TDcoolguy300** [comment]
That implies that the ghost items are infact a bad list

**Comment by Carbonhell** [comment]
Possibly fixed in #1769

**Comment by Pyko1** [comment]
Seems to be fixed. Closing
