### ISSUE TITLE
As a traitor AI you cannot use department channels.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#175]
When you are a traitor AI, it seems you cannot use specific department channels. You can still use the general and syndicate channels, but anything else is off limits. You can still hear those channels but not talk. Bit of an issue if someone in that channel asks you something and you randomly can't respond.

**Comment by Jaygriff** [comment]
Can confirm on this one... Perhaps its not building the transmitters correctly..

**Comment by AliiTea** [comment]
NTSL....

http://pastebin.com/jtKjF941

**Comment by GunHog** [comment]
That version of my script hideously outdated. But again, my updated versions might not be compatible with your code.

I am a coder for /tg/, I am also the coder for this feature, and this problem has been fixed on /tg/. Simply change "keyslot" to "keyslot2" on: 
https://github.com/HippieStationCode/HippieStation13/blob/master/code/game/objects/items/devices/radio/headset.dm#L198 and your problem will be solved.

**Comment by AliiTea** [comment]
10/10 GunHog would link your NTSL again

**Comment by ghost** [comment]
Fixed.

**Comment by ghost** [comment]
Thanks @GunHog

**Comment by AliiTea** [comment]
FUCK >_>

**Comment by AliiTea** [comment]
Erik you shit
