### ISSUE TITLE
Atropine Doesn't Metabolize

### ISSUE THREAD

**Issue by Podgehodge** [HippieStationArchive/HippieStation13-1#1754]
Atropine. Y'know... the chem nobody uses or makes, because once you need it, it's already too late. Basically, it works like a slightly crappier version of cryo, but only for people who are in crit. Problem is, atropine doesn't metabolize for some mysterious reason. So, whoever has taken some will be pulled out of crit repeatedly and forever. If the HoS gets their hands on some, they become damn near un-killable, always coming back from the brink because their armor prevents them from taking more damage than the atropine heals. Well,... that's a bit of an exaggeration, but you can see how it's overpowered.

I looked at [the code](https://github.com/HippieStationCode/HippieStation13/blob/f6c66f301d8eb01c060e7d8a4ff49e7caf4ff039/code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm#L614) and, under atropine, it says metabolization_rate = 0.25 \* REAGENTS_METABOLISM. So, with my limited knowledge, I can't see why atropine is the exception to the rule. It's almost as if this was done intentionally, but I doubt this is supposed to be a feature. Also, this issue was around before the revert too.

**Comment by Pyko1** [comment]
/datum/reagent/medicine/atropine/on_mob_life(mob/living/M)
	if(M.health < 0)
		M.adjustToxLoss(-2*REM)
		M.adjustBruteLoss(-2*REM)
		M.adjustFireLoss(-2*REM)
		M.adjustOxyLoss(-5*REM)
	M.losebreath = 0
	return


Not an expert on code but does not this miss. 
	..(

**Comment by Pyko1** [comment]
Fixed in: https://github.com/HippieStationCode/HippieStation13/pull/1755

**Comment by Podgehodge** [comment]
Oh yeah, nice catch. From reported to fixed in 30 minutes. :+1:
