### ISSUE TITLE
Positronic brains can end up with two players stuck in them, with only one controlling them

### ISSUE THREAD

**Issue by myontasm** [HippieStationArchive/HippieStation13-1#1756]
Have seen this happen for a while now and I thought this was already reported.

Turns out that if you're unlucky enough you could end up in an already playeroccupied brain, leaving you with no control if the brain were to be inserted inside a borg or mech.

**Comment by ghost** [comment]
I believe the cause for this is from dead players getting a prompt to enter a brain that is newly manufactured through a protolathe (or exosuit fabricator) automatically, and then at the same time either have the guy making said brain turn it on to search for a host (stacking two people into one) or just having a ghost manually join into it at the same time or before it is occupied by the automatic prompt.

**Comment by Jaygriff** [comment]
Just needs a check after the button is pressed. Should be a easy fix.
