### ISSUE TITLE
Changeling lesser form

### ISSUE THREAD

**Issue by Galardomond** [HippieStationArchive/HippieStation13-1#1766]
Hi, 
oh boi,... 
So I was a changeling. I was cuffed and about to die but regenerated. I then switched to monkey form in order to remove the cuffs. Then im not sure what happend, I switched back to human form. I tried to pick up stuff but i couldn't. I could empty a back via drag and drop. I tried to get back in lesser form. A monkey spawned and I am invisble tile, that can't move or interact with anything now.  
So I ahelped. Speakercity didn't know what the fuck was going on. Meanwhile I reconected. That didn't help. 
Problem was then solved by transfairing me into a new Body and making me ling.
My old body was invisble, standing therea and set to dirarm intent, it was visible via sec hud, as I was wanted.
AMA you need. I don't have logs due to reconect.

**Comment by Galardomond** [comment]
http://puu.sh/mMJnG/42e86b53f5.png

**Comment by TDcoolguy300** [comment]
Best guess is that the switcher fucked up, if this occurs again i'll be sure to investigate further via viewing the runtime logs

**Comment by Galardomond** [comment]
http://puu.sh/mNUM2/2f6b927974.png
I was able to recrate it. Took me ~4 switches human <-> Monkey before it worked. Right before it bugged out, i could not use my hands to pick something up or open a bag. Maybe it has to do with picking different DNA's when getting back in human form.

**Comment by Pyko1** [comment]
Also see https://github.com/HippieStationCode/HippieStation13/issues/1220 for other possible lesser form issues.

**Comment by Gandalf2k15** [comment]
Unable to recreate.

**Comment by Kokojos** [comment]
Apparently fixed in the ghost update
