### ISSUE TITLE
Glitchy object embedding

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1768]
When you get some complete asshole jamming your head full of metal rods that needs surgery to be removed and no one else around (friendly enough) to do said surgery, I've done body augmentations on myself to solve the problem.

Surely enough, the brute tick damage stops along with the bleeding but the game still interprets objects being attached into you afterwards with both damage prompts such as "The metal rod embedded in your head hurts!" and the embed icon on the top right, but there is no actual bleeding or damage being done to the player.

**Comment by Pyko1** [comment]
Un-removable embedded items are definitely ruining this game, as they seem to be more common than competent heads and assisting assistants together.

Would be neat if we could make the embed icon clickable, and it would try to pull out all embedded items in you at once. Removing any embedded item, and dealing damage for any item that actually is properly stuck in you.

**Comment by Carbonhell** [comment]
Possibly fixed in #1769

**Comment by Carbonhell** [comment]
Haven't heard anyone having this issue again,could it be fixed?Except the embedded obj alert sticking which i still have to fix

**Comment by Pyko1** [comment]
I'll close this, as it seems to be fixed now. 
If the issue reappears just open this or make a new report.
