### ISSUE TITLE
Thrall Paralysis Range

### ISSUE THREAD

**Issue by XeonFaux** [HippieStationArchive/HippieStation13-1#1770]
Currently can paralyze you from 5 tiles away, should it be nerfed? Opinions?

**Comment by Lucifers-son** [comment]
Yes, it should be 3, in my opinion.

**Comment by Carbonhell** [comment]
Doesn't thrall paralysis work,lore wise, by staring into someone's eyes?It should be only possible in a 3x3 range with the thrall in the center

**Comment by Spacedong** [comment]
can't we have it as like 2 spaces so it's like a stun, not a "lol 360 quiickscoped across the screen, you're stunned for 2 mins now ;)"

**Comment by Pyko1** [comment]
Yeah 1 or 2 tiles would be a lot better, would at least take a minimum effort to paralyze.

**Comment by Nokington** [comment]
3 would be better imo

**Comment by Pyko1** [comment]
balance/feature not a bug
