### ISSUE TITLE
Bug, thralls can disarm you when they go ghost like

### ISSUE THREAD

**Issue by Lucifers-son** [HippieStationArchive/HippieStation13-1#1772]
Mr Skeltal suddenly fades away!
You need your other hand to be empty!
Mr Skeltal has pushed Lenny Williamson!
Your armor softens your fall!
Lenny Williamson says, "Phor phughsh shaghe"
Mr Skeltal appears from nowhere!
This is what happened to me, I did not have many teeth left so therefore the slurred speech, he then proceeded to beat me to death with a fire axe. Please fix this as quick as you can. This was on Hippie station.

**Comment by TDcoolguy300** [comment]
Interesting, i'll look into it when i can.

**Comment by Lucifers-son** [comment]
Thank you!

**Comment by Kokojos** [comment]
Thralls are in fact just wrapping shadows around them, not actually going in another dimension like the shadowlings.
Their alphas drops to 10.
