### ISSUE TITLE
Emagged borgs and Electrically Charged Arms

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1779]
Along with having no visible animation whatsoever, these are also missing sound when used. Either a missing function or blatantly too OP.

**Comment by Spacedong** [comment]
this is balance rather than an issue or bug, it should have a melee attack animation similar to stun baton, but its not that theres no missing sound, its just not there. also pretty sure it drains the heck out of the borg's cell charge

**Comment by TDcoolguy300** [comment]
It does fuck up a Cyborg's powercell

**Comment by Nokington** [comment]
This isnt really a problem because it fucks the powercell

**Comment by ghost** [comment]
It is a clear feedback problem. No animation and no sound.. It is literally the only combat feature/tool in the entire game that has this.

**Comment by Nebyab** [comment]
Not a bug, this is a balance issue at best (and in my mind, not really one regardless)

**Comment by Spacedong** [comment]
well it'd be hard to make an animation considering 90% of the other borg tools don't have animations at all, maybe a sound?

**Comment by Pyko1** [comment]
balance/feature not a bug
