### ISSUE TITLE
Reverents able to kill their selves.

### ISSUE THREAD

**Issue by killer653** [HippieStationArchive/HippieStation13-1#178]
Bug: Reverents are able to kill theirselves when using their spells.
How to reporduce: use your spells, keep attempting to use them, then when you hit 5 energy, it'll let you use them. When you use it, however, it'll either take a strike/kill you.

Possible solution: Make it so the game requires you to wait until 6 energy (for the 5 power spells), 21 energy (for the 20 power spell) and 26 energy (For the 25 power spells)

**Comment by ghost** [comment]
Intended behavior
