### ISSUE TITLE
The "Beach" in the holodeck has a disposals pipe running through it.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1781]
![test](http://i.imgur.com/wnVeoD7.png)

This really cramps the beach aesthetic. There is no pipe under the window to the left, so it's completely not needed. Not sure why it exists.

**Comment by Pyko1** [comment]
Fixed in : https://github.com/HippieStationCode/HippieStation13/pull/1782
