### ISSUE TITLE
Mutliverse swords are back.

### ISSUE THREAD

**Issue by Nokington** [HippieStationArchive/HippieStation13-1#1783]
They were removed before the revert and need to go again.

**Comment by Nokington** [comment]
Priority because they are complete garbage, approved because it was before the revert and before rebase because there isnt a before revert label.

**Comment by ghost** [comment]
100% agree that shit is cancer get the fuck outta that shit

**Comment by TrashFiend** [comment]
its fun but hooooooooooooooooooooly tits is it terrible
