### ISSUE TITLE
Aliens have FAAAAAAAAAR too much HP

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1785]
Just invaded an alien infested station as deathsquad, trapped one lone alien hunter while being in a Mauler and punted over 50 AC-2 bullets into it's chest (alongside other things) at blank range before it got KNOCKED DOWN while also having them not even get phased by missiles or shotgun blasts to the face.

This is also a problem reaching down to even alien larvae that don't even get knocked down at all from having a missile land straight on their head while also having the current aliens combat system allow them to single-handedly manhandle 2 space marines in power armor by spamming knockdowns: http://puu.sh/mRqb5/b8b091d79b.png

Just.. No.

**Comment by trifornt-tinfornt** [comment]
Are you talking about Ultra AC2 bullets?
If I recall those deal almost no damage. That and Xenos don't take atmos damage (for the most part), which could be part of the reason they were surviving those blasts so well.

**Comment by ghost** [comment]
They kill fully armored humans in 2-3 bursts, and the pulse rifle didn't do much against them either. Also witnessed them eating about 4-5 rockets from the space marine rocket pistol (only being stunned for about 0.5 seconds if hit directly by one) which is just insane in It's own right.

Bug or not, rework/balancing is needed.

**Comment by myontasm** [comment]
Consider using fire next time, it's their biggest weakness and hits hard. And go as a group stronger than two men next time jfc

**Comment by AliiTea** [comment]
Aliens are meant to be a ROUND ENDING event so them being weak would go against what they are for.

**Comment by Spacedong** [comment]
really, the other day I killed an alien with 2 pulse bullets to the chest. Get good lad

**Comment by Nokington** [comment]
Ultra AC2 is just shit. Pulse rifle kills everything in two shots.

**Comment by Kokojos** [comment]
They have 200 health, it's not that much. Please close.

**Comment by Nokington** [comment]
This is a nonissue
