### ISSUE TITLE
Beepsky can see through walls.

### ISSUE THREAD

**Issue by XeonFaux** [HippieStationArchive/HippieStation13-1#1786]
Saw this earlier, on a round. A guy was set to arrest or had an illegal item, and was running through maint. Beepsky saw through the wall and chased him, and then stopped at the wall due to pathing.

**Comment by Nebyab** [comment]
I mean, I'm fine with beepsky being utterly wonderful.

**Comment by ghost** [comment]
Tbh since shitcuckity does nothing beepsky having this buff is good

Not a problem unless it ruins muh emershuns

**Comment by Pyko1** [comment]
presumably working as intended, even tho I do believe they actually need to have LoS to start chasing, after that there is no need for LoS.
