### ISSUE TITLE
Bad lighting on the cyborg's optical meson scanner

### ISSUE THREAD

**Issue by mipmop01** [HippieStationArchive/HippieStation13-1#179]
The optical meson scanner on the mining cyborg is ignoring the ores on the floor, please fix it for a better mining.

**Comment by Cairo283** [comment]
Ores on the floor? Please explain; Do you mean ores that are on the floor as an item, or ores in the rocks?

**Comment by WhiteFox08** [comment]
The way OMS's work is that require a light source to actually see stuff at a distance, if there is not enough light you won't be able to see the ore, just bring a flashlight with you next time.

**Comment by Jaygriff** [comment]
Not a bug
