### ISSUE TITLE
Security can be antags.

### ISSUE THREAD

**Issue by Nokington** [HippieStationArchive/HippieStation13-1#180]
Someone fucked up with picking antag roles first because I believe it doesn't check for loyalty implants anymore so security can be antag. Also AI can be a double agent, that doesn't seem right either.

**Comment by TDcoolguy300** [comment]
Right, looking at this from afar, whoever decided to initialize antags before players are even spawned in or equipped with their shit is a horrible decision. The check for loyalty implants and/or is AI/borg is non-functional. The bit with the loyalty implants is based on equipment, or known as the Select equipment verb. Loyalty implants are part of their base items, or the shit they spawn with, this includes the damn implants. By selecting antags BEFORE the players get their shit or spawn in is an absolutely HORRIBLE decision.

**Comment by ghost** [comment]
FIXED!
