### ISSUE TITLE
Be revenant not appearing in game preferences.

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#1803]
Title.
During mid-game, the game looks for people to make revenants, but noone has it enabled because noone can enable it because noone can see it because it doesn't exist, therefore you always get 

"No candidates were available for becoming a revenant."

**Comment by XeonFaux** [comment]
This been fixed with the HoG update.

**Comment by Jaygriff** [comment]
Can confirm, fixed... Though im not sure if im welcome to close issues on here, despite having the power to.

**Comment by Pyko1** [comment]
If its fixed, I see no reason for issues to be open.
