### ISSUE TITLE
Bible sizzles in hands when beating cultists

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#1807]
Is this meant to happen? Ideally, I'd think most chaplain-related material would help in damaging cultists, but the bible actively damages you when you try to beat a cultist with it.

**Comment by Pyko1** [comment]
Quite frankly the bible being able to identify cultists is pretty damn strong, even if it damages you.

**Comment by Nebyab** [comment]
Its intended to allow you to detect cultists, at the cost of some minor damage. 
Its working as intended.
