### ISSUE TITLE
If a person in the area picks up a butt, it shows up in your hand.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#1826]
So apparently if anybody picks up a butt in the area of a full screen, it shows up in your hand if your hand is empty. I believe it shows up in the hand that they pick it up in.

I have no clue why this is a thing, and it only happens with butts. It's happened multiple rounds. Feature I guess?

**Comment by TDcoolguy300** [comment]
That is incredibly strange, as for whats causing it i have no idea. Butts are no different than any other item with the exception of the fart attack noise, so it can't be that.

**Comment by TrashFiend** [comment]
I tried this by getting someone to pick up a butt and it did show up in my hand, but I couldn't do anything with it. The moment they dropped it the butt disappeared.

**Comment by Spacedong** [comment]
OH FUCK I REMEMBER THIS, ITS A DUPLICATE OF #1478

THIS HAPPENS TO ME SO MANY TIMES WHAT IS CAUSING THIS

**Comment by TDcoolguy300** [comment]
Effectively it's not reproducible reliably. Or who knows, it could just be a thing on the server itself.

**Comment by Spacedong** [comment]
pretty sure its server-side

**Comment by ghost** [comment]
Open yours eyes sheeple

I L L U M I N A T I

**Comment by Kokojos** [comment]
Happened on my test server, a lot, during the last test session. It seems to be utterly random, but it does happen. Seems the butt needs to have fallen off via fart or superfart. Dosen't happen with spawned butts.

**Comment by Carbonhell** [comment]
> so many times
> never seen it other than the first day when ass update was merged
> wat,any new info

**Comment by Crystalwarrior** [comment]
rofl the butt is not removed from internal_organs g fucking g

**Comment by TrashFiend** [comment]
ok so it doesn't actually have to be within a certain area. it applies to any slot it can fit in and from any distance I believe.

**Comment by Carbonhell** [comment]
needs more info on how this happens

**Comment by TrashFiend** [comment]
on the player side you just fart your ass off and have someone else pick it up. i have no clue why it would do anything that a normal item wouldn't do, though

**Comment by Carbonhell** [comment]
I may know why, will fix on next update

**Comment by Kokojos** [comment]
I believe this has been fixed with 5.10 or before, since I never saw it happen since.

**Comment by TrashFiend** [comment]
This is still an issue as of yesterday.
