### ISSUE TITLE
HoG bugs v2.0

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#1828]
1)gods didn't spawn what the total fuck-->I'm a dumb fuck,fixed
2)weird god icon when transformed through TP-->possibly fixed, might need some more info
3)prophet didn't spawn with his hat
4)friendly thing to projectiles and not to turrets themself
5)godspeak prophet ability linked to the hat,fuckin shit,should be linked to the prophet himself
6)make it possible to convert enemy followers
7)hugely nerf claymore, it encourages killing which is not the point of the gamemode at all,or actually make the equipment more "defense"/"kidnap" based instead of lolkill
8)godspeak ability is working funnily,check that shit
9)if a god dies all its followers should become normal people again

**Comment by Spacedong** [comment]
if a god dies shouldn't its follower's shit be fucked up since that's all they believe in

**Comment by SplergeBucket** [comment]
yeah if a god dies their followers should become atheists aka they stop being antags
either that or a follower has the possibility to become his new god aka jesus is yahweh????
