### ISSUE TITLE
Welding logs happen when a borg is being repaired

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#1832]
![bug](http://s9.postimg.org/oogw0eygf/bugreport.png)
It's the guy in the top left.

**Comment by Kokojos** [comment]
and also apparently everytime it's used

**Comment by Pyko1** [comment]
IT should be changed to be releated to hotspot/new() or something.

**Comment by Kokojos** [comment]
AHHHH IT'S BEING USED EVERYTIME SOMETHING HAPPENS IN AN AREA EVEN IF THERE IS 0.0000001 plasma.

**Comment by TDcoolguy300** [comment]
Carbon's fix caused shit.
