### ISSUE TITLE
chaplain spawns with riot armour

### ISSUE THREAD

**Issue by SplergeBucket** [HippieStationArchive/HippieStation13-1#1850]
this crusader armour shiet is basically reskinned riot armour
its too good
needs a nerf
tune it down to 50 or something like the barkeeps armour

![](http://puu.sh/n1gM5/6a888c42f5.png)
![](http://puu.sh/n1gMn/66cf08837e.png)

**Comment by Spacedong** [comment]
w e w

**Comment by Nebyab** [comment]
not a bug

**Comment by Pyko1** [comment]
I assume the main issue really is https://github.com/HippieStationCode/HippieStation13/issues/1824.

**Comment by Spacedong** [comment]
fixed close this

**Comment by Carbonhell** [comment]
Nerf's been merged for riot armors,if the problem persists make a new issue yo
