### ISSUE TITLE
Changlings that have been absorbed remain the husked after regenerating 

### ISSUE THREAD

**Issue by Eragossiver** [HippieStationArchive/HippieStation13-1#1852]
Started round as a changeling, ran into other changeling. Knew changeling would try to kill me, but let him mess with my genetics anyway. He pulls me out to start absorbing me, so I enter regen stasis for fun. He absorbs me, I wait for awhile and can regenerate. Come back to life after he has drained me, my sprite is a drained corpse sprite. I was blind and had some superpower, not sure which ones. here is server info https://github.com/HippieStationCode/HippieStation13//commit/55f298e620258e8f65d100114c3997c004c7e33a

**Comment by Pyko1** [comment]
Whats the issue here?

**Comment by danhibiki** [comment]
Husked living changelings is the bug he's reporting

**Comment by Pyko1** [comment]
So make the regenerate restore the character appearance, (also add it to admin heal, unless it was already added in)?

**Comment by Pyko1** [comment]
I guess the husked appearance counts as a bug.

**Comment by Pyko1** [comment]
So the real bug is that getting absorbed while regening, does not stop it?

**Comment by Carbonhell** [comment]
For future reference if someone gets to attempting to fix this bug, headmins want it so that husked lings can't regenerate

**Comment by ghost** [comment]
What about lings that get husked from spess, can't they revive and still be husked? Is that allowed? Or is it when they get sucked by another ling that they shouldn't regen?

**Comment by Pyko1** [comment]
Lings who have gotten the succ aint coming back no more, closing.
