### ISSUE TITLE
Wizard's teleport spell doesn't work at all.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#1861]
Title. It does literally nothing.

**Comment by Jaygriff** [comment]
Does not pull up menu, enters recharge mode, doesn't ever recharge.

Runtimes Triggered

`runtime error: bad arg name 'user'
proc name: perform (/obj/effect/proc_holder/spell/targeted/area_teleport/perform)
  usr: Lucas Fuchs (/mob/living/carbon/human)
  src: Teleport (/obj/effect/proc_holder/spell/targeted/area_teleport/teleport)
  usr.loc: the floor (43,160,1) (/turf/simulated/floor/plasteel/shuttle)
  src.loc: null
  call stack:
Teleport (/obj/effect/proc_holder/spell/targeted/area_teleport/teleport): perform(/list (/list), null)
Teleport (/obj/effect/proc_holder/spell/targeted/area_teleport/teleport): choose targets(Lucas Fuchs (/mob/living/carbon/human))
Teleport (/obj/effect/proc_holder/spell/targeted/area_teleport/teleport): Click()
Teleport (/datum/action/spell_action): Trigger()
Teleport (/obj/screen/movable/action_button): Click(null, "mapwindow.map", "icon-x=10;icon-y=16;left=1;scr...")`

**Comment by Grufus2** [comment]
In area_teleport.dm(line 11) changing:

`/obj/effect/proc_holder/spell/targeted/area_teleport/perform(list/targets, recharge = 1)`

to

`/obj/effect/proc_holder/spell/targeted/area_teleport/perform(list/targets, recharge = 1, mob/user = usr)`

Seems to fix it.
