### ISSUE TITLE
Shadow Walk (or whatever) for Shadowling Ascendants is STILL broken.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#1867]
Still has the exact same affect as the Teleport spell does, as in literally none.

**Comment by Jaygriff** [comment]
Part of #1861

**Comment by Grufus2** [comment]
In shadowling_abilities.dm(line 836):

`for(user in targets)`

The For loop is invalid.

Changing or removing it seems to fix it.

**Comment by Kokojos** [comment]
Apparently been fixed recently as It worked during my tests.
