### ISSUE TITLE
Cultist can gain infinite Hp thanks to a manifest rune + drain rune.

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#1869]
Reply PM from-Hackole/(CENSORED): summon a shade,(?|F) and then drain it. repeat.

**Comment by Pyko1** [comment]
Infinite HP, or just heal?

**Comment by Jaygriff** [comment]
I do believe it allows you to go beyond the HP cap.

**Comment by TDcoolguy300** [comment]
Unless someone was doing sloppy coding it shouldnt even be going above the max, or rather in the negatives for damage types

**Comment by Kokojos** [comment]
Just heal, but infinitely.

**Comment by Hackole** [comment]
Another thing you can do is raise as many dead people as you want using the raise dead rune - because the shades you're summoning are technically people, you can use them as a dead body for the raise dead rune.

**Comment by Pyko1** [comment]
hardly an issue then, takes more effort than a medbot.

**Comment by Pyko1** [comment]
balance thing, not a bug
