### ISSUE TITLE
Plant people traitor

### ISSUE THREAD

**Issue by lcass** [HippieStationArchive/HippieStation13-1#187]
If you die and then are respawned through being put into a plant pod thing , you cannot complete the escape on the shuttle alive and free objective.

**Comment by ghost** [comment]
Plant people are counted as nonhumans, same goes for monkeys and others.

**Comment by lcass** [comment]
The objective should still complete though , it is escape live and well not escape as a human.

**Comment by WitheredGryphon** [comment]
Yes it says alive, implying you have a pulse. That's the point behind borging/podding people, traitors can still play but no longer accomplish their objective because they died and weren't cloned.

**Comment by lcass** [comment]
eh thats a bit too much of an rp reason to be perfectly honest. I think it should be fixed for this. Excluding borgs of course , once youre borged youre out.

**Comment by Jaygriff** [comment]
Plant people should still be eligible as its comparable to cloning.

**Comment by AliiTea** [comment]
Naw.

You died and weren't cloned by normal means..  How do the syndicate know it's you?

**Comment by lcass** [comment]
^^still wayyyyy to rp for my liking.

**Comment by lcass** [comment]
gah wrong button
