### ISSUE TITLE
Graffiti sprayed on the floor appears over lockers

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#1886]
http://i.imgur.com/7Aedz5K.png

Pretty minor, but still

**Comment by Pyko1** [comment]
Many of the machinery, including chem tanks/lockers/crates are layer 3.0 while gang sprays are 3.6.
Not sure if moveable machinery should be brought a bit higher and reduce the spray layer below it.

Might cause other issues, gotta check whats in the layers 3 to 3.6.

**Comment by Pyko1** [comment]
balance/feature not a bug
