### ISSUE TITLE
I'm unable to activate a pill from a dental implant

### ISSUE THREAD

**Issue by yacobm8** [HippieStationArchive/HippieStation13-1#1891]
I've tried using styptic powder which says it deals toxin damage when ingested. I activated a 40u pill with no effect.

I tried chlorine pill 50u no effect

also tried a meth pill with no effect, Am I doing something wrong? I have the option to click and activate the chemical pill denture implant but there doesn't seem to be any effect happening. When I swallow these pills normally though the effect does happen for example when I swallowed a morphine pill it knocked me out but with the denture implant it did nothing.

**Comment by Kokojos** [comment]
Since this has been a month withouth any confirmations/sighthings I will close this.
