### ISSUE TITLE
Space zlevels are borked

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#1928]
You can only go to mining or station when crossing zlevel borders, i've tested 50 times and everytime i went either to zlevel 1 or zlevel 5,so it's 100% bugged

**Comment by FuryMcFlurry** [comment]
isnt there a new system that removed random zlevel travel and actually allows you to map out space.

**Comment by Carbonhell** [comment]
I tried different directions: left, right, up and down. None of them worked,so.

**Comment by Kokojos** [comment]
Probably the torus was being complicated. I got to z-level 6, 5, 4 and 3 with no problem just by buildmode-throwing myself around.
Closing..
