### ISSUE TITLE
White Ship itself spawns offset to the left of where it's actually supposed to land

### ISSUE THREAD

**Issue by toolboxtothehead** [HippieStationArchive/HippieStation13-1#1929]
However, the hitbox remains where it's supposed to be. Just got killed by it recently.

**Comment by toolboxtothehead** [comment]
When going to the derelict. Forgot to mention that.

**Comment by AliiTea** [comment]
Will look into this if it already hasn't been.

**Comment by ArcLumin** [comment]
It's been an issue ever since the derelict has been made, nobody's ever bothered to fix it though. Literally just gotta move the docking indicator a few tiles towards the derelict.
