### ISSUE TITLE
Unfuck zombies

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#1930]
So far on every single occasion that zombies have been introduced to a round, the server undergoes lag spikes, which increase in frequency until it eventually crashes and needs to be reset. Typically this occurs after there are many zombies active, and many people infected with the zombie virus running around.

I don't know the exact cause of this, but what I do know is that zombies made for a fun late-round event that would bring lots of dead players back into the game, and generally spiced things up for those still alive.

Would be pretty sweet if somebody could unfuck them for me, thanks.

**Comment by Kokojos** [comment]
:+1: Someone with more experience get on this.

**Comment by blobbernaut** [comment]
sounds like a memory leak

**Comment by Carbonhell** [comment]
Sort-of linked with #2097

**Comment by JohnGinnane** [comment]
Closing as this appears to be fixed in #2349 as tested with 100 zombies

**Comment by calibraptor** [comment]
<3
