### ISSUE TITLE
Nukeops Reinforcements don't spawn with space suits.

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#1934]
As said in the title, they don't. This fucked me over badly last night by not having enough spacesuits.

Excuse me if I did something wrong, just wanted to make a bug report.

**Comment by TDcoolguy300** [comment]
This is technically not a bug, Nuke op reinforcements are meant to be called on the station and not on your shuttle/mainbase

**Comment by TDcoolguy300** [comment]
But it is, however, balancing

**Comment by Pyko1** [comment]
Actually...
```
/obj/item/weapon/antag_spawner/nuke_ops/proc/check_usability(mob/user)
	if(used)
		user << "<span class='warning'>[src] is out of power!</span>"
		return 0
	if(!(user.mind in ticker.mode.syndicates))
		user << "<span class='danger'>AUTHENTICATION FAILURE. ACCESS DENIED.</span>"
		return 0
	**if(user.z != ZLEVEL_CENTCOM)
		user << "<span class='warning'>[src] is out of range! It can only be used at your base!**</span>"
		return 0
	return 1
```

**Comment by TDcoolguy300** [comment]
That is horrendously dumb then.

**Comment by Pyko1** [comment]
Maybe up the cost to 35-40 and give them something like:

```
/datum/uplink_item/specoffer/bulldog
	name = "Bulldog bundle"
	desc = "Optimised for people that want to get up close and personal. Contains the popular Bulldog shotgun, a two drums of ammunition, and an elite hardsuit."
	item = /obj/item/weapon/storage/backpack/dufflebag/syndie/bulldogbundle
	cost = 16

```
or
```
/datum/uplink_item/specoffer/medical
	name = "Medical bundle"
	desc = "Support your fellow operatives with this medical bundle. Contains a Donksoft machine gun, a box of ammo, a pair of magboots and a medical beam gun to rescue your friends in no-gravity environments."
	item = /obj/item/weapon/storage/backpack/dufflebag/syndie/med/medicalbundle
	cost = 17

```

**Comment by trifornt-tinfornt** [comment]
I'd just say make them start with the black and red spacesuits and give them 15/20 TC to spend for themselves - especially on Declaration of War. They're not worth it in any other mode.

**Comment by Pyko1** [comment]
I'd rather equip them with premade sets instead of giving tc, as with TC we would have to increase the summon price directly for the amount given, or make it so that their uplink cant be used to share TC.

**Comment by carlarc** [comment]
I think we should just equip them with the basic starting gear + black-red spacesuits and a jet harness.

**Comment by ArcLumin** [comment]
I'd be interested in having them have specializations or random items, and costing a tad more TC's

**Comment by Pyko1** [comment]
balance/feature not a bug
