### ISSUE TITLE
Hippie still runs /tg/ code

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#1971]
fuck /tg/

**Comment by Carbonhell** [comment]
avoid meme issues, plus if it wasn't for tg we would have to *openeyes *closeyes with bay

**Comment by ghost** [comment]
I meant we should switch to gooncode nerd

**Comment by Carbonhell** [comment]
License doesn't allow it nor it's viable anyhow since it's way different than our and noone would think of coding there unless crazy

**Comment by TDcoolguy300** [comment]
It's all spaghetti code
