### ISSUE TITLE
Malf AI is cardable

### ISSUE THREAD

**Issue by AliiTea** [HippieStationArchive/HippieStation13-1#1975]
See title.

Possible that the AI loses it's antag status.. or that we have a /tg/ update that allows it.

**Comment by Carbonhell** [comment]
it doesn't, it only lost its special_role var somehow. no clue how yet.

**Comment by trifornt-tinfornt** [comment]
It's because on /tg/ Malf AI was removed, and instead Traitor AIs are "malf", and they hack APCs to speed up their takeover rate and to get module points instead of being locked to 100 module points from the start.

**Comment by Pyko1** [comment]
so a feature then?

**Comment by AliiTea** [comment]
We don't have that I think..

We still have Malf AI gamemode

**Comment by Carbonhell** [comment]
It's a non confirmed bug that happened only once. No more similar issues have been reported, and the code seems fine, iunno. Close?

**Comment by AliiTea** [comment]
Ye
