### ISSUE TITLE
Revenant links TG wiki.

### ISSUE THREAD

**Issue by TheOneAndOnlyCreeperJoe** [HippieStationArchive/HippieStation13-1#2008]
When a Revenant spawns, it gives a link to the wiki guide, except it's the TG guide.

The TG Wiki has a different version of Revenant, giving misinformation (we don't have Blight or Night Vision).

We got a mostly up to date wiki page on Revenant (http://wiki.hippiestation.com/index.php?title=Revenant) ourselves. In addition, using our own wiki looks more professional.

**Comment by carlarc** [comment]
I remember that CM has every damn article being bay wiki or something.
But uh, support?
Also, 

> more professional

**Comment by Spacedong** [comment]
why does CM matter in this at all

**Comment by Spacedong** [comment]
like really what? this is a good fix

**Comment by Carbonhell** [comment]
Fixed
