### ISSUE TITLE
Darksight is broken again.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#2012]
http://i.imgur.com/yw7JYYY.png
Amazing.

**Comment by Zadeon** [comment]
I don't think this is broken, it's just that their default darkness_view is 1. You can change it with shift nerves to bump it up to 8. I just tested shift nerves and everything was working fine.

**Comment by KayeArray** [comment]
you['re supposed to take eyewear off before using it...

**Comment by trifornt-tinfornt** [comment]
Ah, that makes sense.
