### ISSUE TITLE
Suiciding with Air tanks gibs the victim, preventing objectives to be completed

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#2042]
This is sad. People get gibbed and changeling/antags search forever.

**Comment by Spacedong** [comment]
I thought if they suicide the objective is complete for them since they're dead?

**Comment by Kokojos** [comment]
There is the ling objective to escape with their ID and identity.

**Comment by Spacedong** [comment]
we should rework that as its extremely fucking shit for this reason and if the fuckers decide to explore space or something.

**Comment by Spacedong** [comment]
a lot of changeling stuff needs revamping tbh

**Comment by doobiedoo23** [comment]
What if there was a way to somehow absorb them through a set of gibs? It wouldn't entirely fix the issue (if the gibs were cleaned up or something) but iunno

**Comment by Spacedong** [comment]
but air tank suicides are the best way to go out

**Comment by TDcoolguy300** [comment]
How about we keep the explosion, but only for the head.

**Comment by Pyko1** [comment]
How about new changeling ability that lets them to collect DNA samples from blood/gibs/vomit/meat.

The DNA sample then needs to be "cultivated" before it can be used properly.
This would take 1 minute or so, while changeling is rendered immobile and is wildly mutating appearances.

Also make gibbing should produce meat no matter how its done.

**Comment by myontasm** [comment]
I like TD's suggestion. Having just the head nixed on airtank suicide would prevent it from being an issue.

**Comment by Pyko1** [comment]
Could add that to shotgun suicide as well.

**Comment by blobbernaut** [comment]
well really it'd be the body because it's the lungs that are exploding, but they'd still be connected to their lower body via the spinal column which is a pretty strong piece of bone, it should make a body with all the flesh gone from the torso and no damage elsewhere

**Comment by Gandalf2k15** [comment]
Not an issue. due to the fact it was removed.

**Comment by JohnGinnane** [comment]
It's an issue if a changeling wants to greentext

**Comment by Gandalf2k15** [comment]
The objective was removed.

**Comment by JohnGinnane** [comment]
Ah sorry, my bad!
