### ISSUE TITLE
n20 is labeled as "unknown" by air analyzers

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2045]
title. makes no sense honestly, at most the unknown would be plasma because it's new (arr pee)
and something that has been known for hundreds of years should not be labeled as unknown.

**Comment by TDcoolguy300** [comment]
It's more a TG oversight than anything.

**Comment by Spacedong** [comment]
its not a bug, the wiki literally mentions this, not an oversight and intended

**Comment by carlarc** [comment]
why?
if it's not it's dumb anyways

**Comment by carlarc** [comment]
also, could you provide a link?

**Comment by Pyko1** [comment]
its bad coding really, the whole N2O seems to be slapped on to other gasses using different system.

**Comment by carlarc** [comment]
then replace the unknown with n20 on the air analyzer and make the text blue
unless there's more than n20 labeled as unknown

**Comment by Spacedong** [comment]
its n2o not n20 ok

**Comment by carlarc** [comment]
oh sorry, it's nso

**Comment by KayeArray** [comment]
From looking at it, it appears that N2O appears to be slapped on as a rather strange "trace gas" instead of a normal gas. I fear what scary shit might happen if we try to change it.

**Comment by Spacedong** [comment]
this is not a bug this was always in-game since the beginning
