### ISSUE TITLE
you can get mulligan in crit

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2049]
fuck

**Comment by Carbonhell** [comment]
Is this really an issue,you can still be healed... Like it happened

**Comment by Crystalwarrior** [comment]
uhh, if you're in crit in the first place chances are you'll be either finished off or die from "natural causes".

**Comment by Pyko1** [comment]
Not a bug really, at least I see no reason to add checks for health to mulligan antags.

**Comment by carlarc** [comment]
well i figure it'd be pretty annoying to have a chance to be traitor and be in crit, unable to do jack shit except whisper some dumbass your PDA code.

**Comment by Pyko1** [comment]
not a bug, closing.
