### ISSUE TITLE
Disposals lead you to law office and dumps you there

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStationArchive/HippieStation13-1#2064]
See 
![image](https://cloud.githubusercontent.com/assets/3355198/14062862/5d1ae97c-f3a6-11e5-8f92-6a2b9cb225b7.png) for reference. This seems like a big issue!

**Comment by Kokojos** [comment]
@Spacedong !!!!

**Comment by JohnGinnane** [comment]
I'm actually trying to recreate this and I'm having difficulty. It happened the first two times, but now I'm not sure how I managed that

**Comment by Pyko1** [comment]
Somehow i can already see what happened there...

**Comment by Spacedong** [comment]
I dont understand what I did wrong this shouldn't happen what the hell

**Comment by JohnGinnane** [comment]
I'm not sure if it counts, but the junction disposal pipe had another pipe in it's contents..

Again, sometimes you end up in the law office, sometimes it takes you to cargo
![image](https://cloud.githubusercontent.com/assets/3355198/14062975/26ea894c-f3ac-11e5-8089-53bd360ee396.png)

**Comment by Pyko1** [comment]
The junction point to wrong direction at least to begin with, but then again that should not direct crap in there.

**Comment by Spacedong** [comment]
i am utterly dumb and cannot into disposals, do I need a junction there or what? a sorting pipe?

**Comment by Pyko1** [comment]
jsut make the juntion leading to law office point upwards.

**Comment by JohnGinnane** [comment]
It seems random on whether it drops you there, I think because there are two disposal pipes on the one tile

**Comment by JohnGinnane** [comment]
Okay, it seems the junction is the wrong type:

![image](https://cloud.githubusercontent.com/assets/3355198/14063145/7dcda9b8-f3b3-11e5-839b-5e33cea10f43.png)

The junction circled in red should go in the opposite direction. The pipe on the left leads into security while the pipe on the right leads out of security

**Comment by Spacedong** [comment]
wait what so it needs to go up?

**Comment by JohnGinnane** [comment]
Sorry, I should have clarified: The pipe junction needs to go up towards security, not down and away. I'm fixing it now as me speak though!

**Comment by JohnGinnane** [comment]
I'm noticing **many** changes to the .dmm despite only changing one pipe...

**Comment by Kokojos** [comment]
He remade the lawyers office too.

**Comment by JohnGinnane** [comment]
I've created a PR, #2067 so hopefully this tiny little change won't interrupt any other changes made in the map
