### ISSUE TITLE
Blendmode var is broken.

### ISSUE THREAD

**Issue by SplergeBucket** [HippieStationArchive/HippieStation13-1#2072]
It's supposed to have 5 choices (0-4), the default of which is 0, which is normal (1 is also normal 4someraisin).
Instead, turning it to 2 makes the icon disappear, and 3 and 4 do nothing.

**Comment by Carbonhell** [comment]
Blend mode is a byond var which affects what happens to the overlays added so

**Comment by Kokojos** [comment]
Yeah so far I see no problem with blendmode. It works with images in the lobby for me, although 1 is still normal.
