### ISSUE TITLE
Coloring a winter coat with a crayon in the washer doesn't give the hood the same color as the coat.

### ISSUE THREAD

**Issue by atomic1fire** [HippieStationArchive/HippieStation13-1#2083]
TBH it just looks silly. The hood is colored in one sprite, but not colored on the person or the head slot.

![image](http://i.imgur.com/JmAaemL.png?1)

**Comment by JohnGinnane** [comment]
Is the hood similar to hardsuits where you activate it instead of just equiping it?

**Comment by JohnGinnane** [comment]
Note to self: check for hood_type when washing and set to wash_color if exists

**Comment by JohnGinnane** [comment]
I have fixed this in #2110
