### ISSUE TITLE
"Flowey" and "Flowey Grin" AI statuses do not work.

### ISSUE THREAD

**Issue by Daundra** [HippieStationArchive/HippieStation13-1#2087]
![image](https://cloud.githubusercontent.com/assets/5360736/14136130/42016fd6-f62f-11e5-9eb0-09a79b3a3385.png)

Basically the two ones at the bottom.

Clicking on them does nothing. It does not attempt to change the AI status at all.

**Comment by Crystalwarrior** [comment]
I'm assuming those flowey sprites don't exist or something?

**Comment by danhibiki** [comment]
sprites DO exist inthe current code ![d](http://i.imgur.com/eQL6Du7.png)

This is the line dealing with picking from the list and displaying it on the status display screens.

https://github.com/HippieStationCode/HippieStation13/blob/f08fbc5f932b9d4f408888c9df77bfb72e1e4f34/code/modules/mob/living/silicon/ai/ai.dm#L677

**Comment by Carbonhell** [comment]
Issue is here:
https://github.com/HippieStationCode/HippieStation13/blob/f6c66f301d8eb01c060e7d8a4ff49e7caf4ff039/code/game/machinery/status_display.dm#L244
It'd be pretty easy to fix in a shitty way,but i'd suggest to properly fix it and remove that ugly useless switch.

**Comment by trifornt-tinfornt** [comment]
The status looks terrible, I'll be honest. I'd rather it not be fixed.
