### ISSUE TITLE
Xenobiology made xenomorphs have no abilities due to being different mobs

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#2097]
fuck you whoever did this

**Comment by Crystalwarrior** [comment]
might be intended but FUCK THAT, honestly it just feels snowflakey and dumb.

**Comment by carlarc** [comment]
dumb

**Comment by blobbernaut** [comment]
intended because otherwise xeno rounds, and if they were the xenos that had abilities, they wouldn't do anything until made sentient

**Comment by Carbonhell** [comment]
This is a core problem with simple mobs being coded in a shitty way, there should be an AI datum that can control a mob similar to how a player does. Iunno if anyone's up for taking such a big pain in the ass. @Crystalwarrior ?

**Comment by Gandalf2k15** [comment]
This is just a bad feature. Not an issue.

**Comment by TDcoolguy300** [comment]
This is not even an issue or a bad feature, golden slimes will ALWAYS spawn the simple_mob variant of the aliens, this is so they can actually do shit without spawning an empty body
