### ISSUE TITLE
mech drilling is garbage

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#2103]
> mech drills floor
> random guy walks by
> wrong moment wrong place
> guy gets critted

**Comment by carlarc** [comment]
you can drill supermatter and make it dissapear

**Comment by Pyko1** [comment]
also https://github.com/HippieStationCode/HippieStation13/issues/2037

**Comment by ArcLumin** [comment]
This is not a bug

**Comment by ArcLumin** [comment]
This is not a bug, if you're drilling the floor it hurts everything on top of it
