### ISSUE TITLE
Epipherine + Crit = CRAWL MASTER

### ISSUE THREAD

**Issue by Crystalwarrior** [HippieStationArchive/HippieStation13-1#2114]
/title, if you are injected with epipherine when you're in crit you'll crawl at supersonic speeds.

**Comment by Kierany9** [comment]
Or meth. Leave it as it is, it's fucking hlarious

**Comment by JohnGinnane** [comment]
I think it's "intended". After all you take damage when crawling around crit I think? So you're basically crawling yourself to death really fast

**Comment by Crystalwarrior** [comment]
You take oxyloss when crawling, honestly yeah it's fucking hilarious.
