### ISSUE TITLE
A nuke ops Bug.

### ISSUE THREAD

**Issue by Lucifers-son** [HippieStationArchive/HippieStation13-1#2117]
the c90-GR or whatever it is called cannot switch between launching grenades and fire-ing bullets, cannot even be loaded with grenades. 40MM ones to be exact. The description shows it has a under-slung grenade launcher, and the bundle comes with the 40mm Grenadas.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
You can switch to grenades and you can normally load, but not directly from the box, you have to manually remove the grenades from the box and put them into the gun.

Could do with some QoL changes

**Comment by Gandalf2k15** [comment]
This is no longer an issue.
