### ISSUE TITLE
Stuns are fucked

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2128]
I got hit twice by a taser (no riot shield) And didn't get stunned at all. In addition, I accidentally crushed myself with shutters, and I could crawl as if I were in crit.

**Comment by Kierany9** [comment]
First one's a bug, as for the second one:

https://github.com/HippieStationCode/HippieStation13/pull/2124

Changelogs aren't showing up or some shit.

**Comment by Kokojos** [comment]
@Crystalwarrior Fix yo shit and test it beforehand

**Comment by Crystalwarrior** [comment]
EEEEEEEEEEEEEEEEEEEEEEEEE FUCK
Seems like stun reduction on armor is done like garbage

**Comment by Crystalwarrior** [comment]
Figured out the issue, going to PR a fix. Better be merged ASAP as full stun proofness is NOT good.
