### ISSUE TITLE
Syndicate Shuttle can be broken into (again)

### ISSUE THREAD

**Issue by TheOneAndOnlyCreeperJoe** [HippieStationArchive/HippieStation13-1#2129]
The 3 right-most walls on the Syndicate Shuttle cockpit can be destroyed, as well as the right-most wall on the top of the cockpit

See imagine for better instructions

![plzfix](https://cloud.githubusercontent.com/assets/17836851/14363835/7389f9be-fd06-11e5-9a16-0d32c0ed293e.png)

**Comment by Carbonhell** [comment]
that's what happens when i try to map
how the fuck did you even find that out?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
@Carbonhell The walls had a description, I know from heart the indestructible ones don't have descriptions.
