### ISSUE TITLE
Emergency shuttle cannot be marked as an area by blueprints

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2137]
This fucked me over a little when I was atmos tech during the nexendia shuttlebuild.

**Comment by Kokojos** [comment]
Fairly sure this is intended as not to break the shuttle itself.

**Comment by Spacedong** [comment]
why the fuck do we have a working as intended label, close it or if its an actual issue, keep it open

**Comment by Crystalwarrior** [comment]
yeah I agree, working as intended is kinda silly.

**Comment by Pyko1** [comment]
The label is for searching purposes mainly.

And usually when I use it, i keep issue open for couple days if someone has anything to add.
