### ISSUE TITLE
Securitron detain has no timer.

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2144]
When securitrons detain, there's no timer or anything. They just keep on stunning forever. Literally no way to escape. Man, that's fun! Please add one.

**Comment by Carbonhell** [comment]
It's exactly what detain means

**Comment by ghost** [comment]
It's always been like that, it can only keep 1 person detained at any given time (I think) and if you have anti-stun then it's arguably worse than arrest.

**Comment by Gandalf2k15** [comment]
I think the reason the left it to stun forever is so that a sec officer can come and properly arrest you.

**Comment by Crystalwarrior** [comment]
I don't think this is fun though, you're basically stuck in an infinite stunlock if the security never comes/are dead/rogue AI likes to fuck with people.
I suggest that Beepsky simply closes the windoor behind you and leaves you there.

**Comment by Carbonhell** [comment]
...Windoor?

**Comment by Carbonhell** [comment]
More like,add a max time, so if noone comes after 60 seconds the detain function will stop on the current target

**Comment by McHatters** [comment]
Isn't this a feature? That's what they're supposed to do.

**Comment by Pyko1** [comment]
Should really have some limit on how long the bot can keep stunning you.

**Comment by Crystalwarrior** [comment]
Unavoidable stunlocks are NEVER fun for anyone but the attacker, and if the attacker is a fucking bot it's not fun for anyone period.

**Comment by Pyko1** [comment]
yeah if the classic baton was OP and had to be removed, this is a lot worse.

**Comment by ghost** [comment]
this issue is giving me my daily dose
thanks doc

**Comment by carlarc** [comment]
reminder that i will not leave this shit hanging, i'm going to keep it at the top until it's fixed

**Comment by Nebyab** [comment]
This is a feature, not a bug.

**Comment by carlarc** [comment]
Well yes. I know. This isn't the bug report place, this is an issue. That's why I put it here.

**Comment by doobiedoo23** [comment]
@crystalwarrior: windoor???

**Comment by Crystalwarrior** [comment]
window door holy shit it's almost like you never seen it before

**Comment by doobiedoo23** [comment]
No, I know what a windoor is, I'm asking what relevance it has to this

**Comment by Crystalwarrior** [comment]
pretty damn sure brig cells have windoors. What I'm saying is make Beepsky leave the cell after enough time has passed and make him close the door so you don't just waltz out of the cell, but have to strip yourself and break the cell open if security doesn't care.

**Comment by Carbonhell** [comment]
This is a feature,the fact that it might be unbalanced or not means it doesn't have to stay here. Move it on the forum, this isn't the proper place to discuss balance things,really.

**Comment by Crystalwarrior** [comment]
..huh? I thought issue reports worked for both, really. It can still be considered an issue and we DO have a "Bad Feature" tag soooooo

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Removed in #2284 should be closed.
