### ISSUE TITLE
Nuclear Ops being able to get infinite borgs from one purchase

### ISSUE THREAD

**Issue by BroomHill** [HippieStationArchive/HippieStation13-1#2148]
A few days ago while playing as a nukie I discovered you could get infinite Borgs by buying the thing once then spam clicking it in your hand but not choosing a borg type right away. After several spams you will like 20 borg choice menus which let you get tons of borgs.

**Comment by carlarc** [comment]
Oh hey, this is almost the exact same bug of the challenge mode.
