### ISSUE TITLE
You can put poly acid in a spray bottle by using a syringe

### ISSUE THREAD

**Issue by killer653** [HippieStationArchive/HippieStation13-1#215]
You can bypass being unable to put poly acid into a spray bottle by using a syringe.

How to reproduce:
1. Get a spray bottle
2. Make poly acid
3. Attempt to put poly acid in bottle via beaker, see it doesn't work
4. Take the poly acid out via syringe and inject it into the spray bottle
5. have fun with your killing weapon

**Comment by ghost** [comment]
known bug.

**Comment by AliiTea** [comment]
Easy fix

**Comment by Nokington** [comment]
This was fixed
