### ISSUE TITLE
Nuke Ops round end stats dont show all items purchased by syndicate

### ISSUE THREAD

**Issue by Jaygriff** [HippieStationArchive/HippieStation13-1#216]
Observed when I was a syndicate agent, none of the items I purchased showed up in the round end stats.

**Comment by WhiteFox08** [comment]
![g071hop](https://cloud.githubusercontent.com/assets/2702850/8245967/421c423e-15fc-11e5-9579-946c3c48057d.jpg)

Auto delcare returning the items bought correctly, I could not reproduce on my local.

Going to go test this on the server.

**Comment by JustinNewton** [comment]
Try with multiple agents. I believe the first agents spends get reported. Also may be linked to the spending device being destroyed.

**Comment by lcass** [comment]
This does happen , if justin hasnt handled it I will.
