### ISSUE TITLE
Can cast spells during Bloodcrawl and Ethereal Jaunt

### ISSUE THREAD

**Issue by TheOneAndOnlyCreeperJoe** [HippieStationArchive/HippieStation13-1#2160]
What it says on the tin. Most spells won't actually work, but some of them do:
Fireball, EMPulse, Smoke, Teleport and Instant Summons still work while in this shape. Fireball shoots a fireball in the direction you were originally facing, EMPulse causes the pulse at your current location, same goes for smoke. Teleport lets you teleport like normal, not a problem during jaunt but a large one during Bloodcrawl. Casting Instant Summons pulls the item into limbo (aka it vanishes) until you summon it again.

In addition, casting Jaunt or Teleport while in Bloodcrawl causes the blood crawl hands to remain stuck in your hands until you cast Bloodcrawl again, preventing you from using your hands until then.

**Comment by Kokojos** [comment]
Fixed in my tests!
