### ISSUE TITLE
Wiz events/Book of change sends the player back to the lobby, forcing them to rejoin as a new player

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#2164]
No idea how this happens, since this is coming from the ahelps I received during a wiz round. It may have been events, as one ahelp said he got sent back to the lobby after getting mindswapped. Another dude got sent back to the lobby when he used a spellbook of change, and signed back in to find that his old body was still there.

DC'd after mindswap:
http://i.imgur.com/1v2rh1o.png
http://i.imgur.com/YjonC6x.png
http://i.imgur.com/pqFz2If.png

DC'd after spellbook use:
http://i.imgur.com/rGOvPH8.png

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Change? I think he means Charge, because as far as I know there's no Change spell in the game.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Can't seem to reproduce it after half a hour of fucking around with mindswap and the book of charge

**Comment by carlarc** [comment]
Staff of change?

**Comment by McHatters** [comment]
Nah, it was a spellbook. It might've been charge.

**Comment by Pyko1** [comment]
Something fucked up the ckey swap, that causes you to get disconnect and get sent back to lobby if no mob has your ckey.

**Comment by Kokojos** [comment]
I believe John Jinname fixed this a long time ago with the ghost changes.
