### ISSUE TITLE
Signalers in C4s don't work.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#2165]
You can put a signaler into a C4 and then put it on an object, but when that happens you'll be unable to actually set off the signaler and you'll just have a useless C4 on an object because you can't pry the things off.

**Comment by McHatters** [comment]
Yep. This is a thing.

**Comment by blobbernaut** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/5462010e5bcc8a61ad5618ffd0f04f07eeb570b0/code/game/objects/items/weapons/explosives.dm

how it works is  it just delays it by the timer, then explodes the atom if it hasn't been deleted yet. The c4 actually not a thing anymore, other than a variable and a sprite overlay.

**Comment by Crystalwarrior** [comment]
I'll fix it on my assembly overhaul PR

**Comment by Crystalwarrior** [comment]
Lol this is a straight up runtime. Will fix on https://github.com/HippieStationCode/HippieStation13/pull/2163
