### ISSUE TITLE
Rev is broken

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#217]
Since antag picker update, rev will never happen. If you try to force it, it says unable to start game mode, resseting lobby.

**Comment by Nokington** [comment]
Can't we just remove the antag picker thing. It has literally caused more problems than it has fixed

**Comment by asskek** [comment]
antag picker is good
i think
that's the thing that rolls antag before job, right?

**Comment by AliiTea** [comment]
I agree with Nokington, Antag picker has caused too many bugs..

Rip it out and try again!
