### ISSUE TITLE
Cosby Sweater Not On Clothesmate Lists

### ISSUE THREAD

**Issue by WallaceShark** [HippieStationArchive/HippieStation13-1#2170]
Right as it says on the can. Both standard, hacked, and premium lists lack the Cosby sweater. Below is a complete list of all wardrobe items from a machine with both green light and coin.

Vend top-hat: 2
Vend fedora: 1
Vend monocle: 1
Vend bomber jacket: 2
Vend puffer vest: 2
Vend puffer jacket: 2
Vend navy suit: 1
Vend executive suit: 1
Sold out burgundy suit: 0
Vend charcoal suit: 1
Vend white suit: 1
Sold out kilt: 0
Sold out laborer's overalls: 0
Vend amish suit: 1
Vend jeans: 3
Vend classic jeans: 2
Vend camo pants: 1
Vend black jeans: 2
Vend khaki pants: 2
Vend white pants: 2
Vend red pants: 1
Vend black pants: 2
Vend tan pants: 2
Vend track pants: 1
Sold out military jacket: 0
Sold out snazzy jumpsuit: 0
Vend blue tie: 1
Vend red tie: 1
Vend black tie: 1
Vend horrible tie: 1
Vend red scarf: 1
Vend green scarf: 1
Vend dark blue scarf: 1
Vend purple scarf: 1
Vend yellow scarf: 1
Vend orange scarf: 1
Vend light blue scarf: 1
Sold out white scarf: 0
Vend black scarf: 1
Vend zebra scarf: 1
Vend christmas scarf: 1
Vend striped red scarf: 1
Vend striped blue scarf: 1
Vend striped green scarf: 1
Vend waistcoat: 1
Vend black skirt: 1
Vend sundress: 2
Vend striped dress: 1
Vend sailor dress: 1
Vend red evening gown: 1
Vend black tango dress: 1
Vend red plaid skirt: 1
Vend blue plaid skirt: 1
Vend purple plaid skirt: 1
Vend Prescription Glasses: 2
Vend sombrero: 1
Vend poncho: 1
Vend worn shirt: 1
Vend laceup shoes: 2
Vend black shoes: 4
Vend sandals: 1
Vend fingerless gloves: 2
Vend orange glasses: 1
Vend red glasses: 1
Vend fannypack: 1
Vend blue fannypack: 1
Vend red fannypack: 1
Vend tacticool turtleneck: 1
Sold out balaclava: 0
Vend ushanka: 1
Vend soviet uniform: 1
Vend black fannypack: 2
Sold out checkered suit: 0
Vend mailman's hat: 1
Vend mailman's jumpsuit: 1
Vend leather jacket: 1
Vend leather overcoat: 1
Vend Must Hang jeans: 1

**Comment by McBawbaggings** [comment]
Isn't the cosby sweater called the checkered suit?

**Comment by JohnGinnane** [comment]
This is my bad, I didn't update the changelog after we decided to make it only spawn in maint/contraband: https://github.com/HippieStationCode/HippieStation13/pull/2116/files#diff-2c9ee1b008318615f13a6b5410f59704R6

Sorry for the confusion!

**Comment by ghost** [comment]
If it isn't in the clothesmate then the refill shouldn't probably refill 3 items for a maximum of 6 if the refills are meant to do 1/3. Although I've never ever seen a refill be used.

**Comment by JohnGinnane** [comment]
Good point!
