### ISSUE TITLE
Gandalf's template is runtiming

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#2175]
## WARNING: build_pipeline(): further messages about pipenets will be supressed

runtime error: list index out of bounds
proc name: setPipenet (/obj/machinery/atmospherics/components/setPipenet)
  source file: components_base.dm,105
  usr: null
  src: the Space vent pump #6 (/obj/machinery/atmospherics/components/unary/vent_pump)
  src.loc: the plating (40,43,6) (/turf/simulated/floor/plating)
  call stack:
the Space vent pump #6 (/obj/machinery/atmospherics/components/unary/vent_pump): setPipenet(/datum/pipeline (/datum/pipeline), the scrubbers pipe (/obj/machinery/atmospherics/pipe/simple/scrubbers/hidden))
/datum/pipeline (/datum/pipeline): build pipeline(the scrubbers pipe (/obj/machinery/atmospherics/pipe/simple/scrubbers/hidden))
the scrubbers pipe (/obj/machinery/atmospherics/pipe/simple/scrubbers/hidden): build network()
Air (/datum/subsystem/air): setup pipenets(null)
Air (/datum/subsystem/air): Initialize(360695, null)
/datum/controller/game_control... (/datum/controller/game_controller): setup(null)
and a lot of similar runtimes

**Comment by TDcoolguy300** [comment]
Should be technically fixed, closing for now.
