### ISSUE TITLE
catbeasts using mimic voice still meow

### ISSUE THREAD

**Issue by collinxchu** [HippieStationArchive/HippieStation13-1#218]
See title.

**Comment by ghost** [comment]
10/10 would meow again.

**Comment by asskek** [comment]
pls fix 
i can't pull off my changeling gimmick without a proper disguise

**Comment by ghost** [comment]
@asskek 5$

**Comment by Jaygriff** [comment]
It's a feature.

Jk probably not. Probably a easy fix.

**Comment by Kokojos** [comment]
Catbeast can't be antags anymore.

**Comment by Chronitonity** [comment]
This isn't just a Catbeast problem, its a problem with all races who use the voice changer afaik
