### ISSUE TITLE
Trying to type emotes in OOC

### ISSUE THREAD

**Issue by Nokington** [HippieStationArchive/HippieStation13-1#2187]
It brings up an annoying screen that says it looks like you were trying to type that in IC. Do you want to type it OOC instead?

I couldnt be assed to see if there was an issue about this already if there is close this

**Comment by ghost** [comment]
Probably because there's a script to stop radio messages going into OOC. Since : can be used as a preface for messages, it gets picked up by this.

**Comment by Carbonhell** [comment]
^ not an issue, it's a feature, if it's shit bring it on the forum
