### ISSUE TITLE
Lesser Form -> Human Form Rips Intercoms Off The Fucking Wall

### ISSUE THREAD

**Issue by asskek** [HippieStationArchive/HippieStation13-1#219]
Bug details:
see title

How to reproduce:
Be lesser form changeling. Stand on tile with an intercom on the wall. Change back to human form. The intercom will be in your pocket/belt/holster. 

Notes:
i forget but i don't think the intercom can be taken out of whatever slot it jumps to

**Comment by asskek** [comment]
how do i add tags

**Comment by AliiTea** [comment]
Holy shit this is amazing

**Comment by asskek** [comment]
pls fix
i'd fix it and that'd fill my "good ss13 deeds" monthly quota
but i can't code
