### ISSUE TITLE
Sometimes Constructs/Shades won't have CultHud

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#2202]
I don't quite know what causes this but if you pick "Would you like to play as a Shade?" there appears to be a small chance for you to just not be a cultist - even if your creator was a cultist. You also get affected by Cult runes and cannot use Cult Chat. Basically it completely breaks you as you run around the place unable to know which side you're on until a powergamer inevitably kills you.

**Comment by carlarc** [comment]
Also whenever I'm cult I don't get the cult verb (which has communion) And can't hear cultchat.

**Comment by Kokojos** [comment]
Not did hear of this for a long time, I believe it's been fixed, correct me if I am wrong, will close this meanwhile.
