### ISSUE TITLE
Janiborgs have no way to wet mops without human support

### ISSUE THREAD

**Issue by Jaygriff** [HippieStationArchive/HippieStation13-1#221]
Janiborgs should start with a bucket with liquid in it for their mops.

Partial of http://www.hippie-station-13.com/forums/viewtopic.php?f=34&t=1756d

**Comment by TrashFiend** [comment]
Can you wet your mop if you have the bucket in your other hand? If so just adding a bucket to a janiborg's inventory should work fine.

**Comment by Jaygriff** [comment]
Nope, buckets cannot be used to wet mops. Only mop buckets. 

Ill look into the code and see whats preventing it

**Comment by AliiTea** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/222
Nice one @JustinBNewton
