### ISSUE TITLE
Orion Trail games disappear if you disconnect and reconnect their monitors.

### ISSUE THREAD

**Issue by Someone1214** [HippieStationArchive/HippieStation13-1#223]
Exactly what it sounds like, disconnected and reconnected the monitor on an orion trail game, and it disappeared completely. No trace left.

**Comment by ghost** [comment]
Uhh. Can you try alt-clicking on the location of the used-to-be arcade? Or right-clicking? Sounds like an icon issue tbh

Sent from a not-so-smartphone. Anything written herein that you find misspelled, objectionable, incoherent, dim-witted, plagiarized or legally actionable should be attributed to the phone manufacturer, Chinese hackers, or PRISM.

**Comment by Someone1214** [comment]
No, I right clicked. It was gone completely.

**Comment by Jaygriff** [comment]
runtime error: Cannot modify /obj/item/weapon/circuitboard/arcade/orion_trail.loc.
proc name: attackby (/obj/structure/computerframe/attackby)
  source file: buildandrepair.dm,339
  usr: Shaun Beach (/mob/living/carbon/human)
  src: the computer-frame (/obj/structure/computerframe)
  call stack:
the computer-frame (/obj/structure/computerframe): attackby(the crowbar (/obj/item/weapon/crowbar), Shaun Beach (/mob/living/carbon/human), "icon-x=29;icon-y=10;left=1;scr...")
Shaun Beach (/mob/living/carbon/human): ClickOn(the computer-frame (/obj/structure/computerframe), "icon-x=29;icon-y=10;left=1;scr...")
the computer-frame (/obj/structure/computerframe): Click(the plating (66,152,1) (/turf/simulated/floor/plating), "mapwindow.map", "icon-x=29;icon-y=10;left=1;scr...")

Error output when I attempted to remove the board from the computer

**Comment by Carbonhell** [comment]
Fixed,can be closed
