### ISSUE TITLE
[NO] [WHAT THE FUCK] [FUCK] [HOLY SHIT] Lizard Tails and snouts don't show up properly

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2238]
lizards look LIKE FUCKING HUMANS WHAT THE FUCK
THEY DON'T HAVE TAILS FROM THE FRONT BUT LEFT AND RIGHT THEY DO
THEY LOOK LIKE FUCKING PLAYDOH HUMANS WHAT

**_SHUT IT DOWN_**

**Comment by TheOneAndOnlyCreeperJoe** [comment]
LIGGER RIGHTS, WE DEMAND RETRIBUTION.

WE WANT OUR SNOUTS, HORNS, FRAILS, TAILS AND SPINES BACK!

**Comment by TDcoolguy300** [comment]
ITS BEING WORKED ON

**Comment by blobbernaut** [comment]
actually the worst, my waifu looks like fucking barney now

**Comment by Crystalwarrior** [comment]
:scream:

**Comment by Spacedong** [comment]
FIX IT GOD DAMN IT FUKC YOU DO IT NOW

**Comment by blobbernaut** [comment]
My hulk sprite thing worked before but now it doesn't because of dismemberment fucking up all the sprites FIX IT AAAAAA

**Comment by TDcoolguy300** [comment]
Fixed
