### ISSUE TITLE
Skeleton sprites have their arms poking out of the side.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#2240]
http://i.imgur.com/cyLERt3.png

CRYSTAAAAAAAAAAAAAAAAAAAL
EDIT:
They also randomly change colors. Sometimes my skeleton is yellow but other rounds he's normal, but then he's green.
What is even going on

**Comment by Crystalwarrior** [comment]
Oh goddamnit, I did notice it was happening but I thought I fixed it.
Will fix in a jiffy, sprite issue.

Regarding colors, though... No clue why it happens. Skeletons are not supposed to change colors so it's just odd.
