### ISSUE TITLE
Lings unable to regenerate when decapitated

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStationArchive/HippieStation13-1#2255]
Seems to be a side affect of the dismemberment update. If you decapitate a ling they can't regenerate at all which makes sense. It's a rather large nerf because it means practically anyone can properly dispose of a ling with any of the following:
1. Fireaxe (2 at round start)
2. Butcher's knife (1 at round start, requires hacking Chef's machine)
3. Circular saw (2 at round start, many more if you use the autolathe)

And possibly more. I think we should consider whether or not lings can be decapitated. Even if it's a power. Right now it's much easier to remove lings permanently!

**Comment by TDcoolguy300** [comment]
How about on ling decapitation the head becomes a headcrab, giving a reason for people to NOT decapitate lings

**Comment by JohnGinnane** [comment]
If someone could put labels (balance, controversial) on this that'd be appreciated

**Comment by Crystalwarrior** [comment]
I'll solve this issue with a general ling touch-up update

**Comment by Sarcalogo** [comment]
Please don't do the stupid head spider stuff. It's bullshit and you know it. Now changelings will lose all of their shit once they are killed once, and it'll probably be ridiculously easy to kill the spider thing.

**Comment by Crystalwarrior** [comment]
Then what else do you suggest? If you got decapitated it should be a pretty big hit on your ability to function, but you'll still be able to escape.
It won't be the head spider shit, though. I'm bringing back headslugs and making them less atrociously retarded, speed-and-hatch time-wise.

**Comment by JohnGinnane** [comment]
maybe disable head dismemberment for lings?

**Comment by Crystalwarrior** [comment]
Nah, for one it'd be too snowflakey to do. For two it'd just confuse people.

**Comment by JohnGinnane** [comment]
Good points!

**Comment by dreamcrab** [comment]
i really like the idea of them ejecting to a headslug if they get decapitated. make them keep their abilities and DNA? i dunno
