### ISSUE TITLE
Debraining/Beheading someone forces them back into their body, even if they are a xenobio mob, midround antag, etc.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#2289]
Title. And boy is it obnoxious.
How many Abductors/Slimes/Aliens have had this happen to them at this point?
Fix it, please.

**Comment by Crystalwarrior** [comment]
This is an issue that existed pre-dismemberment if your original body was, say, Ei Nath'd or debrained or any of the like.
I think it's about the brains and how they handle forcing you back into it.

**Comment by trifornt-tinfornt** [comment]
Did it really? I don't quite ever remember that happening.

**Comment by Crystalwarrior** [comment]
Tell me, how often has your old body been debrained when you're playing as someone else?

**Comment by trifornt-tinfornt** [comment]
Almost never.

**Comment by Sarcalogo** [comment]
https://github.com/HippieStationCode/HippieStation13/issues/2140

Also MMI's STILL CANNOT GHOST. THIS IS A CRITICAL BUG. IT MAKES YOU UNABLE TO GET ANY ENJOYMENT WHATSOEVER OF THE ROUND IF YOUR MMI IS SPACED OR LEFT IN AN ISOLATED PLACE

**Comment by Spacedong** [comment]
why does an issue have a do not merge label

**Comment by JohnGinnane** [comment]
Might have been to do with me messing up with commits/merging. Will remove now
