### ISSUE TITLE
Some TG stuff we NEED to port

### ISSUE THREAD

**Issue by SugarBooger** [HippieStationArchive/HippieStation13-1#2290]
https://github.com/tgstation/-tg-station/pull/17472
https://github.com/tgstation/-tg-station/pull/17428
https://github.com/tgstation/-tg-station/pull/17399
https://github.com/tgstation/-tg-station/pull/17341
https://github.com/tgstation/-tg-station/pull/17333
https://github.com/tgstation/-tg-station/pull/17240
https://github.com/tgstation/-tg-station/pull/16933
https://github.com/tgstation/-tg-station/pull/17192
https://github.com/tgstation/-tg-station/pull/16866
https://github.com/tgstation/-tg-station/pull/16858
https://github.com/tgstation/-tg-station/pull/16851
https://github.com/tgstation/-tg-station/pull/16778
https://github.com/tgstation/-tg-station/pull/17228
https://github.com/tgstation/-tg-station/pull/16761
https://github.com/tgstation/-tg-station/pull/16729

**Comment by SugarBooger** [comment]
More stuff
https://github.com/tgstation/-tg-station/pull/16694
All their mining department ex:Lava land and such
The shit that's in the crafting menu ex:bola,skateboard,scooter etc

**Comment by SugarBooger** [comment]
I found Lavaland:https://github.com/tgstation/-tg-station/tree/master/code/modules/mining/lavaland

**Comment by Crystalwarrior** [comment]
Miniature energy gun already exists on atlas as energy pistol
I don't think tablecrafting should turn into UI clutter personal crafting tho, also I heard creeperjoe was fixing tablecrafting?
I like the wetness PR
Pretty sure we already have fire extinguisher cabinet construction
The macho man thing is better off being done with OUR wrestling in mind since our wrestling is very different from /tg/'s.
The floorbot thing is good
Chemical explosives PR is gucci
Fire Extinguisher help intent is great

**Comment by TheOneAndOnlyCreeperJoe** [comment]
I wasn't fixing jack shit.

**Comment by imtakingabreakdontatme** [comment]
Lavaland is all over our codebase and we changed turf paths, it would be difficult to port

**Comment by SugarBooger** [comment]
Fuuuck can't u help us a bit Kor?

**Comment by SugarBooger** [comment]
Fuuuck can't u help us a bit Kor?

**Comment by ghost** [comment]
There is not a thing here I dislike, assuming the wrestling is better than ours.

**Comment by Crystalwarrior** [comment]
chances are it isn't :^)

**Comment by Iamgoofball** [comment]
you guys have the old /tg/ wrestling you know

just port my goon port its better

**Comment by Crystalwarrior** [comment]
Dude, no. Our wrestling is rewritten from scratch by me and I've added like 6 new moves with fancy animations.
I'm quite a nerd when it comes to martial arts :V

**Comment by carlarc** [comment]
tgstation/-tg-station#16761
MERGE ASAP

**Comment by imtakingabreakdontatme** [comment]
R E B A S E

**Comment by Iamgoofball** [comment]
> R E B A S E

**Comment by TDcoolguy300** [comment]
Then you nerds do the rebase and all the rebalancing

**Comment by carlarc** [comment]
> Then you nerds do the rebase and all the rebalancing
> 
> 881 open issues
> 
> 82 open prs

you fucking wish

**Comment by danhibiki** [comment]
This isn't remotely what the issue tracker is for.

**Comment by TDcoolguy300** [comment]
Dan does have a point, please move this discussion to the forums.

**Comment by Iamgoofball** [comment]
> > R E B A S E

**Comment by Crystalwarrior** [comment]
someone's not aware of how our last rebase went huh

on a serious note, it's too much of a pain stripping out things and features that don't suit our server at all, catching all the bugs and oddities and porting all our shit we have. Our team is too small for that and it's frankly not worth the effort.

**Comment by Iamgoofball** [comment]
> > > R E B A S E

**Comment by Crystalwarrior** [comment]
:scream: :gun:

**Comment by KorPhaeron** [comment]
R E B A S E 
E
B
A
S
E

**Comment by Nebyab** [comment]
> rebasing to modern tgcode again

We've had our bi-annual dose of autism and cancer. Come back next year though!

**Comment by optimumtact** [comment]
it'll be many things but it wont' be fun
