### ISSUE TITLE
Canegun is eternally borked.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2294]
Alas working canegun, we hardly knew ye.

Canegun tries to reskin itself, offers the double-barreled shotgun skins, when you pick anything it turns invisible.

Steps to reproduce:
Have canegun in one hand, other hand empty
Use empty hand on canegun
Select a fun new skin from the menu that appears
???
Your canegun is fucking invisible

**Comment by TDcoolguy300** [comment]
I hate the shotgun code

**Comment by Voratius** [comment]
Confirmed. Swap hands too.
http://i.imgur.com/OugMGnR.jpg
http://i.imgur.com/Q6gwlta.jpg
http://i.imgur.com/vKxHMce.jpg

**Comment by Spacedong** [comment]
wew lad

**Comment by JohnGinnane** [comment]
Looking at this now. As a work around you can still use the "change" verb to change the skin to a cane or pimp stick, and this will update the icon
