### ISSUE TITLE
Items can't be thrown

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#2298]
well they can, but they have a throw_force of 0.
Known bug.
Putting it here so it can be logged

**Comment by Crystalwarrior** [comment]
Hold up is this still an issue? Creeperjoe's cluwne PR was reverted recently.

**Comment by JohnGinnane** [comment]
Is this all items?

**Comment by Spacedong** [comment]
this is fixed, close it
