### ISSUE TITLE
PDAs and the E hotkey

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2299]
Tiny fucking thing but I know it's going to annoy the shit out of me.

With the inventory updates, equipping a PDA via hotkey automatically puts it in your belt slot. Before it put it in the ID slot.

Please make it go into the ID like it did before.

**Comment by Crystalwarrior** [comment]
Huh?
In my experience it always put it in the belt slot.

**Comment by ghost** [comment]
All things being equal, if both slots were open and your ID was inside the PDA, it put it in the ID slot.

I have a muscle-memory roundstart routine that involves the hotkeys that's all screwed up now.

**Comment by Crystalwarrior** [comment]
I see, I'll see what I can do
