### ISSUE TITLE
Riot shields have been replaced with riot helmets

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2303]
what

**Comment by calibraptor** [comment]
what

**Comment by carlarc** [comment]
all instances of riot shields in the armory are now riot helmets

**Comment by danhibiki** [comment]
Can confirm http://i.imgur.com/NN8ccZm.png

**Comment by Crystalwarrior** [comment]
what in the unholy fuck happened

**Comment by JohnGinnane** [comment]
Issue seems to be caused by https://github.com/HippieStationCode/HippieStation13/commit/a9ac19eba38865613231eab69d3fd91ae7fa09ea

Pull request which caused this: https://github.com/HippieStationCode/HippieStation13/pull/2278

**Comment by AliiTea** [comment]
kekekekeekek

**Comment by Gandalf2k15** [comment]
oh ye
i knew something was up when travis hated me.
just gotta replace all instances of the riot helmet with riot shield.
tbh riot shields are useless now, its not a huge deal.

**Comment by Crystalwarrior** [comment]
...if you do that then there will be no riot helmets.
Fix it manually.

**Comment by carlarc** [comment]
you guys fucking SUCK

**Comment by calibraptor** [comment]
Fixing this in #2293

**Comment by JohnGinnane** [comment]
Closing as PR has been merged
