### ISSUE TITLE
Heat and pressure can still travel through crystal windows without breaking them

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#2311]
As said in the title.

**Comment by TDcoolguy300** [comment]
Blame Atmos

**Comment by calibraptor** [comment]
Hey @McBawbaggings

Try adding Heat_Proof = 1 to the windows. Heat_resistance seems to be a turf specific thing,

**Comment by calibraptor** [comment]
Or I will I guess, if I can figure it out.

**Comment by calibraptor** [comment]
Did it myself. IT DIDN'T WORK AAAAAAAA

**Comment by calibraptor** [comment]
Fixed it with some help from @TDcoolguy300, will be applying the fix along with my supermatter PR once I'm finished with it.
