### ISSUE TITLE
Skeleton sprites have their arms poking out of the side - AGAIN.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#2323]
Showed up the round Gandalf's PR for the Gateway got merged.
http://i.imgur.com/33nA4XS.png
How did you even break this with the GATEWAY?

**Comment by Spacedong** [comment]
fixd?

**Comment by trifornt-tinfornt** [comment]
Nope. And their punch sound isn't skeletontrumpet anymore.

**Comment by Pyko1** [comment]
there was a revert, not an issue
