### ISSUE TITLE
The science outpost is gone

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#2324]
The fuck man me and gandalf put a lot of work into that

**Comment by trifornt-tinfornt** [comment]
We either had a mass revert or Gandalf ruined everything with his Gateway PR.

**Comment by Kokojos** [comment]
10/10

**Comment by Spacedong** [comment]
is dis fixed

**Comment by trifornt-tinfornt** [comment]
Nope. Both the skeleton glitch, science outpost, etc. are still broken.

**Comment by calibraptor** [comment]
This will, incidentally, be fixed in #2333

**Comment by Pyko1** [comment]
there was a revert, not an issue
