### ISSUE TITLE
Gateway zombies can be possessed

### ISSUE THREAD

**Issue by LuisReyesX** [HippieStationArchive/HippieStation13-1#2326]
This is literally gamebreaking(Im serious).Zombies can go to station and ruin the round for everyone and thats not cool

**Comment by Kokojos** [comment]
Testing 101. We are on it but thanks for the report.

**Comment by Gandalf2k15** [comment]
@here https://github.com/HippieStationCode/HippieStation13/pull/2325

**Comment by yobob591** [comment]
o shit

**Comment by LuisReyesX** [comment]
Also,based in TGs code,spiders can be possessed too.So thats something to point out

**Comment by Spacedong** [comment]
should zombies even be able to be possessed by normal players in the first place?

**Comment by carlarc** [comment]
uh either it's a bug or a feature

**Comment by Pyko1** [comment]
Technically a feature, but its so bad that it could even considered as a bug.

**Comment by Gandalf2k15** [comment]
Zombies are broken
