### ISSUE TITLE
Health analyzer works on floors

### ISSUE THREAD

**Issue by bloxgate** [HippieStationArchive/HippieStation13-1#233]
Not sure how to reproduce just saw it out of the corner of my eye, but you can use the health analyzer on floors.

**Comment by Jaygriff** [comment]
Please explain some more?? Their programmed to work only on persons.

Does it output health statistics of the floor or?

**Comment by bloxgate** [comment]
Not sure, like I said I only saw someone use it on the floor. I was sitting in the shuttle and saw "<Name here> check's the floors vitals with the health analyzer" or something to that extent.

**Comment by killer653** [comment]
It happens when you have a shitload of brain damage and try to scan someone with the health scanner.
It's not a bug, it's a feature.
See: https://github.com/HippieStationCode/HippieStation13/blob/4fbed6885ccb3172f2875b6bed69faaf23a224da/code/game/objects/items/devices/scanners.dm#L82-L90

**Comment by bloxgate** [comment]
Ah, ok.
