### ISSUE TITLE
bajillion of stuff reverted??

### ISSUE THREAD

**Issue by carlarc** [HippieStationArchive/HippieStation13-1#2330]
riot shields are always on, c hotkey doesnt work, wwwhhyyyyyy

**Comment by JohnGinnane** [comment]
The revert fuck-up has been undone. Server will be updated shortly and everything should be back to normal

**Comment by carlarc** [comment]
shortly you WISH

**Comment by trifornt-tinfornt** [comment]
It's been four hours, they aren't in yet.
Fucking fix it.

**Comment by Pyko1** [comment]
there was a revert, not an issue
