### ISSUE TITLE
Engineering (the area) has two APCs

### ISSUE THREAD

**Issue by Jaygriff** [HippieStationArchive/HippieStation13-1#235]
One in the power storage room and another in the room before the PA. Conflicts with eachother. When one goes out it cuts the power to the entire area.

**Comment by Nokington** [comment]
@JustinBNewton Can you give a picture because i'm not sure I know what you are talking about

**Comment by Jaygriff** [comment]
Heres the first APC, which displays the area in a blackout with the APC fully charged.

![APC 1](http://i.gyazo.com/bce7eec08ffcc0713d5d9f226e426c49.png)

and heres the second APC which is discharged and being used as the 'primary' APC for the area.

![APC 2](http://i.gyazo.com/bcde18ab865ad75943d4db31c9c0345d.png)

**Comment by Nokington** [comment]
Alright. @Kokojos You never showed me how to make new areas so the engineering lounge probably also has this problem with the foyer. Need to make a new area for the singulo.

**Comment by Kokojos** [comment]
Talk to me on skype when you want to learn~
