### ISSUE TITLE
Zounds of unconnected pipes, batman.

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#2354]
Unconnected pipe manifold located at 100,61,1 (Filtering Room)
Unconnected pipe manifold located at 100,61,1 (Filtering Room)
Unconnected pipe manifold located at 100,61,1 (Filtering Room)
Unconnected air supply pipe located at 78,68,1 (Port Engineering)
Unconnected scrubbers pipe located at 80,69,1 (Port Engineering)
Unconnected air supply pipe located at 154,97,1 (Virology)
Unconnected air supply pipe located at 102,173,1 (Brig)
Unconnected pipe located at 102,61,1 (Filtering Room)
Unconnected pipe located at 102,61,1 (Filtering Room)
Unconnected pipe located at 102,61,1 (Filtering Room)
Unconnected pipe located at 102,61,1 (Filtering Room)
Unconnected pipe located at 102,61,1 (Filtering Room)
Unconnected pipe located at 102,61,1 (Filtering Room)
Unconnected air supply pipe located at 80,68,1 (Port Engineering)
Unconnected scrubbers pipe located at 78,69,1 (Port Engineering)
Unconnected air supply pipe located at 152,97,1 (Virology)
Unconnected scrubbers pipe located at 112,113,1 (Central Primary Hallway)
Unconnected scrubbers pipe located at 112,115,1 (Vault)
Unconnected scrubbers pipe located at 190,134,1 (Escape Shuttle Hallway)
Unconnected scrubbers pipe located at 191,136,1 (Escape Shuttle Hallway)
Unconnected scrubbers pipe located at 52,148,1 (Security Checkpoint)
Unconnected air supply pipe located at 51,155,1 (Arrivals North Maintenance)
Unconnected air supply pipe located at 133,163,1 (Law Office)
Unconnected air supply pipe located at 135,163,1 (Dormitory Maintenance)
Unconnected scrubbers pipe located at 133,168,1 (Law Office)
Unconnected scrubbers pipe located at 109,177,1 (Brig)
Unconnected pipe located at 192,143,4 (Derelict Medbay)
Unconnected pipe located at 194,143,4 (Derelict Medbay)
Unconnected pipe located at 171,65,5 (Mining Station Starboard Wing)
Unconnected pipe located at 171,68,5 (Mining Station Starboard Wing)
Unconnected pipe located at 170,69,5 (Mining Station Starboard Wing)
Unconnected pipe located at 171,70,5 (Mining Station Starboard Wing)
Unconnected pipe located at 28,169,5 (Labor Camp Security)
Unconnected pipe located at 30,169,5 (Labor Camp)
Unconnected pipe located at 25,183,5 (Labor Camp)
Unconnected pipe located at 26,183,5 (Labor Camp)
Unconnected pipe located at 27,183,5 (Labor Camp)
Unconnected pipe located at 28,183,5 (Labor Camp)
Unconnected air supply pipe located at 152,203,5 (Outpost Toxins Lab)
Unconnected air supply pipe located at 154,203,5 (Outpost Toxins Lab)
Unconnected scrubbers pipe located at 164,208,5 (Outpost Lobby)

**Comment by calibraptor** [comment]
Looks like the majority of these are my doing. I'll get to work.

**Comment by calibraptor** [comment]
Fixing this in #2352

**Comment by calibraptor** [comment]
At least, fixing it on Z1 anyways.

**Comment by Kokojos** [comment]
Reopening because reverted.

**Comment by Kokojos** [comment]
Fixed in #2448
