### ISSUE TITLE
Surgery is borked. (Implating stuff)

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2361]
It appears that if you implant the fugu organ from the gateway, you break your own surgery.
We had a lad who phrased his bug nicely.

Reply PM from-Rohan123/([REDACTED]): nope, i tried removing it but instead i cudnt and i had to stuff latex gloves into me(or anything) to close my chest again 
Reply PM from-Rohan123/([REDACTED]): now i have seclite and gloves in me 
Reply PM from-Rohan123/([REDACTED]): i couldnt stop, had to cautery+ drape. And since i couldnt remove even a single item, i had to insert something else in to be able to cautery+drape, or it would try to insert the drape into my chest 

STEPS TO FOLLOW:
Do normal surgery and implant a fugu into the chest cavity.
Remove said fugu in a new surgery.
Add new items in separate surgeries.
Try to remove new items.

I had it so I could stop surgery with cautery + drapes but I could stuff infinite things into the chest cavity.

**Comment by Spacedong** [comment]
gateway is disabled so this issue is null
