### ISSUE TITLE
Headslug monkey is borked.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2363]
Changeling turned into a headslug, laid an egg and turned into a monkey. Tried to turn back into a human black screened. Rejoined but had no corpse.

Probably a mob failing to be created or some shit.

**Comment by carlarc** [comment]
can confirm, also gives the wizard events' Boo! and Possess! verbs but they dont really work

**Comment by Carbonhell** [comment]
hol the fuck up, headslugging a monkey gives boo and possess?wtf

**Comment by blobbernaut** [comment]
Can confirm this happened to me.  The person i layed an egg in was decapitates as was I when i used it.
