### ISSUE TITLE
Server crashes every time it tries to restart, requiring manual restart

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#2364]
Just thought I'd make this an official issue. Hop on it code monkeys, chop chop.

**Comment by JohnGinnane** [comment]
What's happening when you try to restart?

**Comment by calibraptor** [comment]
@JohnGinnane 

At the end of the round, when the server tries to automatically restart for a new round, at some point inbetween the round ending and the start of the next round, it crashes. GMs/Headmins have been having to manually restart it each time.

**Comment by JohnGinnane** [comment]
Can we view the output of the dream daemon or is there some way of knowing what's happening?

**Comment by blobbernaut** [comment]
I think TD said the garbage collector was fucking up

**Comment by JohnGinnane** [comment]
Okay, will do some local testing tonight to see what I can replicate

**Comment by Pyko1** [comment]
Either zombies or gateway, or the server is shitting itself.

**Comment by JohnGinnane** [comment]
Tested locally and appears to reboot, but plenty of errors that need to be fixed I think.

[server_log.txt](https://github.com/HippieStationCode/HippieStation13/files/269073/server_log.txt)
