### ISSUE TITLE
Mining Jetpack bugs

### ISSUE THREAD

**Issue by Zilenan91** [HippieStationArchive/HippieStation13-1#237]
If you have fully working internals (hardsuit, O2 tank, breath mask, helmet on) and have a mining jetpack in your hand, it siphons air from the jetpack rather than from your internals.

Also happens when it's on your back, and for some reason the mining jetpack doesn't actually give any propulsion.

**Comment by Jaygriff** [comment]
Half of this is a feature, the other half is not bugged as you said.
![Jp](http://i.gyazo.com/6da1f9b602fef024e826950a8033f913.gif)
