### ISSUE TITLE
Health Sensors No Longer Trigger Bombs/Assemblies

### ISSUE THREAD

**Issue by Podgehodge** [HippieStationArchive/HippieStation13-1#2379]
Health sensors have been broken for at least a few days now, so this isn't something that just cropped up in a recent revert or update. I've tested them a fair amount and it doesn't seem to matter where you keep them on your person or what they're attached to; they just don't trigger anything anymore. And yes, I made sure the sensors were turned on. :unamused:

**Comment by Pyko1** [comment]
I recall they are working again, so closing.
