### ISSUE TITLE
Rumour: Zombie not restoring HP when infecting someone for the first time

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStationArchive/HippieStation13-1#2393]
![image](https://cloud.githubusercontent.com/assets/3355198/15450767/2763939c-1f9d-11e6-917f-77d2f278f6a3.png)

![image](https://cloud.githubusercontent.com/assets/3355198/15450770/405715e0-1f9d-11e6-98b3-bf089b66c475.png)

**Comment by Gandalf2k15** [comment]
Fixed. https://github.com/HippieStationCode/HippieStation13/pull/2397
