### ISSUE TITLE
The Supermatter can stunlock you even if you have full protection from radiation damage

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#2396]
The stun is literally detain-mode long, as you sit there getting endlessly bombarded with radiation without any breaks until you explode. Engineers who try to fix the SM or help you - even if they have full protection too - will suffer the same fate.
http://i.imgur.com/O3B6TKR.png
Calibraptor, you suck.

how did i screw up the title that badly jesus christ

**Comment by Gandalf2k15** [comment]
fix

**Comment by calibraptor** [comment]
Were you wearing mesons? Because the SM can still fuck you up if you're not wearing any.

**Comment by calibraptor** [comment]
Yep, tested with full protection, when it's about to detonate you receive radiation and stamina damage regardless of your protection. Could someone more experienced possibly get on this?

**Comment by ghost** [comment]
I think I got the fix.

**Comment by ghost** [comment]
I've got the protection working me thinks. Just have the same text as singulo stuff?

**Comment by ghost** [comment]
Fix is here: https://github.com/HippieStationCode/HippieStation13/pull/2411
