### ISSUE TITLE
Zombies that spawn inside of morgues literally cannot escape.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#2401]
stuff all bodies into morgue
watch as zombies spam scream hoping someone will let them out
10/10

**Comment by Voratius** [comment]
tbh this feels like it should be intentional or stay as it is.

**Comment by Crystalwarrior** [comment]
lol no fucking way.
For one, it's no fun being stuck.
For two, it's kind of lame that Zombies can't morgue-spook people. It's such a classic spook.

**Comment by Voratius** [comment]
> no fun being stuck

let's remove bluespace anomaly then, hurrr

also there's a huge difference between bodybag spook and morgue spook
https://upload.wikimedia.org/wikipedia/commons/5/58/Morgue.JPG

**Comment by Gandalf2k15** [comment]
This is fine, I can't really figure out how to work around this anyway.

**Comment by Kokojos** [comment]
This is not an issue IMO, Zombies should be cucked by your intelligence, and there's bound to be a random corpse somewhere.
