### ISSUE TITLE
Catbanned people who become Golems don't become golems.

### ISSUE THREAD

**Issue by TheOneAndOnlyCreeperJoe** [HippieStationArchive/HippieStation13-1#2402]
Aka they just are brought back to life as a normal cat and not as a golem.

**Comment by ghost** [comment]
Kinda intentional? They're catbent for a reason right?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
but it's a waste of a golem rune

**Comment by carlarc** [comment]
its gud

**Comment by ghost** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/2411 Fixed here
