### ISSUE TITLE
AI Turrets sometimes do not shut off properly

### ISSUE THREAD

**Issue by TheOneAndOnlyCreeperJoe** [HippieStationArchive/HippieStation13-1#2403]
Dunno how to reproduce but had it happen this round, a revenant was flying in the AI core and having the AI hit themselves with their own lasers, except the AI's bottom 2 turrets wouldn't respond to the turret controller and didn't shut down/switch to stun.

**Comment by trifornt-tinfornt** [comment]
It was because the turrets were being tampered with because of the Revenant's Malfunction ability. The ion rifle screws with the turrets.
