### ISSUE TITLE
Ayy's can't impregnate monkeys

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2415]
ROUND RUINING LADS
I DEMAND AN ANTAG TOKEN

**Comment by myontasm** [comment]
This /is/ actually round ruining for some
pls ficks

**Comment by calibraptor** [comment]
Wow what

**Comment by Kokojos** [comment]
Grey ayys or purple ayys?

**Comment by trifornt-tinfornt** [comment]
Xeno ayys. Not working as intended.

**Comment by Kokojos** [comment]
Duplicate of https://github.com/HippieStationCode/HippieStation13/issues/2382
