### ISSUE TITLE
Dragging your sprite onto the cryo cell doesn't automatically activate it

### ISSUE THREAD

**Issue by myontasm** [HippieStationArchive/HippieStation13-1#2416]
Using the UI to close it activates it, but dragging yourself into it doesn't. I know it's been like that for ages, but I'd love for that to be corrected.

**Comment by JohnGinnane** [comment]
I agree it's inconvenient, but personally, fixing this would mean the only reason anyone would play medical doctor is to get into the medbay without having to break windows or disassemble walls.

I can try fix later but should we consider whether or not people can just heal themselves so easily with no help from doctors?

**Comment by Badmex** [comment]
You can already heal yourself in the cyro tubes, you just need to open the ui and do it over the ui. So overall it would not really change much, just make the process a bit better.

**Comment by ghost** [comment]
Damn,
It probably should force the pod to turn off when the user is the pod user

**Comment by Nebyab** [comment]
Not a bug, and a bad idea to change this.

**Comment by ghost** [comment]
What, not being able to cryo yourself or being able to cryo in one way and not another?

**Comment by Kokojos** [comment]
So far, I see people have been againts this and will close it for now.
