### ISSUE TITLE
Rad storm lighting causes lighting glitches

### ISSUE THREAD

**Issue by collinxchu** [HippieStationArchive/HippieStation13-1#242]
http://puu.sh/iWg6m.png
http://puu.sh/iWgi6.png
http://puu.sh/iWgiQ.png

All of these are post-rad storm.

**Comment by collinxchu** [comment]
Seems like it may be an issue with only specific areas and object-based lighting.

Can't say for sure but it's a good place to start looking.

**Comment by SplergeBucket** [comment]
#145  #177 
Red's inactive.
