### ISSUE TITLE
Chaplain doesn't have access to chapel maintenance

### ISSUE THREAD

**Issue by doobiedoo23** [HippieStationArchive/HippieStation13-1#2422]
what the fuck is this
http://img.prntscr.com/img?url=http://i.imgur.com/exfPUf0.png

**Comment by JohnGinnane** [comment]
Don't only assistants, captain, chief engineer, station engineers and atmospheric techs have maint access?

**Comment by ghost** [comment]
Metastation allows departments to access their own maintenance (IIRC)
I think lowpop allows people to access their maintenance too?

**Comment by ghost** [comment]
Wait, I can recall chefs and botantists being able to access maint via their departments and only their departments.

**Comment by AliiTea** [comment]
Would be nice if we could move to using a more custom map than just a few edits onto the existing station imo

**Comment by Kierany9** [comment]
Every job has access to their own departments maint tunnels.

**Comment by AliiTea** [comment]
@Kierany9 he's talking about trying to get into Chapel maint from inside the chapel, chaplain doesn't have access to it

**Comment by Kierany9** [comment]
I know, I was replying to John and Mcbawb

**Comment by Kokojos** [comment]
Chaplain should be able to access his maint.

**Comment by Spacedong** [comment]
HOW IS THIS CONTROVERSIAL JUST FIX IT REEEEE

**Comment by calibraptor** [comment]
I see nothing wrong with the chaplain having access to his own maint

**Comment by Gandalf2k15** [comment]
Why is this even being discussed. I'll fix it.

**Comment by Gandalf2k15** [comment]
Fixed https://github.com/HippieStationCode/HippieStation13/pull/2495
