### ISSUE TITLE
You can swap NoDrop items [FUCK]

### ISSUE THREAD

**Issue by TheOneAndOnlyCreeperJoe** [HippieStationArchive/HippieStation13-1#2424]
You can swap NoDrop items by pressing the backpack icon in the bottom left with an item that goes in the same slot and it'll swap the two items, regardless if it's nodrop.

Issues include the owl hardsuit, cluwnes and some other crap.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Internal screaming.

**Comment by Gandalf2k15** [comment]
CRYSTALL

**Comment by Gandalf2k15** [comment]
Fixed https://github.com/HippieStationCode/HippieStation13/pull/2498
