### ISSUE TITLE
AI can look through emagged borgs

### ISSUE THREAD

**Issue by jediluke1999** [HippieStationArchive/HippieStation13-1#2440]
Played as an AI some round. Used my borg as security camera, only to find out that at the end of the round, it had been emagged the entire time. It showed up in the camera lists and not even as disabled. -5/26/16

**Comment by Carbonhell** [comment]
If it wasn't able to,it would be a good way to find out which borg is emagged,so i don't think this is an actual issue imo,or perhaps let the borg activate/deactivate his own cam

**Comment by ghost** [comment]
Working as intended?

**Comment by Kokojos** [comment]
Im pretty certain this is working as intended to make AI's unsure if their borg has been emagged and if IIRC, there's a wire on the borg to stop that.
