### ISSUE TITLE
When cutting off limb via surgery, limb comes off but it is still usable in game.

### ISSUE THREAD

**Issue by jmonga-1675** [HippieStationArchive/HippieStation13-1#2451]
I just cut off my left arm via surgery, and while it came off as an object and I had no arm in my sprite, shift+clicking on myself did not show a missing arm and I was still able to use my left arm.

**Comment by Gandalf2k15** [comment]
CRYSTALLLLL

**Comment by JohnGinnane** [comment]
Should be fixed by https://github.com/HippieStationCode/HippieStation13/pull/2391
