### ISSUE TITLE
Headslugs giving birth to new bodies is unfuckgodly broken

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#2456]
Basicly, it crashes the client so much I could't even respawn or see the player pannel of the guy, the only thing that worked was adminpms. Giving a new body his ckey did not work,

The whole thing is also suspected of crashing the MC.

**Comment by Sarcalogo** [comment]
>getting to tag his own issue as confirmed

THIS IS THE POWER.... OF BEING... A...CODER....
