### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by SpyderVenom** [HippieStationArchive/HippieStation13-1#2463]
Unable to access asset cache browser, if you are using a custom skin file, please allow DS to download the updated version, if you are not, then make a bug report. This is not a critical issue but can cause issues with resource downloading, as it is impossible to know when extra resources arrived to you.

Thats what is says when I log in. Since I am not using a custom skin file... heres my report!

**Comment by ghost** [comment]
Everyone gets it, it doesn't do anything though (to my knowledge) so it's not a big concern.

**Comment by Kokojos** [comment]
It's a byond issue with SS13, IIRC, not a game issue, just a sad thing, but thanks for reporting.
