### ISSUE TITLE
Escape Pods that are emagged do not launch when you try to send it to "escape pod" (mining)

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#2469]
This kind of hinders the effectiveness of the emag as it doesn't allow you to escape tense situations when you need it.
How did this even break to begin with?

**Comment by ghost** [comment]
I'm pretty sure escape pods only launch like that during Delta (Nuke ops, gangs, AI).
They crash land into the asteroid.

**Comment by Gandalf2k15** [comment]
This is not an issue.
