### ISSUE TITLE
Beheaded people can still be hung...

### ISSUE THREAD

**Issue by Gandalf2k15** [HippieStationArchive/HippieStation13-1#2490]
Title
![image](http://i.imgur.com/geJBjSr.png)

**Comment by doobiedoo23** [comment]
maybe they still have a neck

**Comment by Gandalf2k15** [comment]
CLEARLY THEY DONTAAAAAA

**Comment by doobiedoo23** [comment]
i was joking but okei

just add a check to see if someone has no head, then if they're headless don't allow them to be hanged

**Comment by Gandalf2k15** [comment]
Aight I guess I'll fix it then

**Comment by Gandalf2k15** [comment]
Fixed by https://github.com/HippieStationCode/HippieStation13/pull/2491
