### ISSUE TITLE
Emagging the Nutrimax and MegaSeed Servitor don't actually do anything.

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#25]
Its replies with text but doesn't cause any actual difference in the machines themselves. Its apparently supposed to give some evolved plants such as Death Nettle, Ambrosia Deus but with low potency so they can't be used straight away

**Comment by Carbonhell** [comment]
Currently the emag only removes the product lock on machines, if they got none it just does nothing. Maybe it could be better to make it both remove the product lock and enable contraband permanently?

**Comment by Carbonhell** [comment]
done in #629 CLOSE
