### ISSUE TITLE
Cauterising in Self-Surgery will not work.

### ISSUE THREAD

**Issue by HeddyLamarr** [HippieStationArchive/HippieStation13-1#2503]
**Problem Description:** When preforming self-surgery you can not cauterise yourself using the cauteriser and any ghetto equivalents, other people cannot end the surgery for you instead they just attack you.

**What did you expect to happen:** I expected to have about a 50/50 chance in successfully preforming the act and ending the surgery.

**What happened instead:** Instead I either received a "You stuffed up." message or no message at all after preforming the action, I believe I was meant to succeed when the no message appeared but something went wrong along the way.

**Why is this bad/What are the consequences:** I could not finish any self-surgeries, stopping me from preforming multiple self-surgeries on one area.

**Steps to reproduce the problem:**
1. I used a bed-sheet to drape my eyes to prepare for the organ manipulation surgery.
2. I preformed the steps of the organ manipluation surgery right up to cauterising part without major failure.
3. I tried to cauterise with a welding tool, a lighter and finally a cauteriser, they all did not work.

**Server:** Hippie Station 13

**Revision:** c2d75ee7d144de691de1cc273812503162ddfb99 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?):** I was playing as a IPC scientist, the cauterising fails in every self-surgery I try to preform, other people can't end the surgery for me.

**Comment by danhibiki** [comment]
This sounds like using the wrong intent, but that couldn't be possible if you got all the way to cauterization. Sounds like its a problem with how you stuff things up your butt.

**Comment by JohnGinnane** [comment]
I think there's an error when it does succeed which is why you don't see a message and the surgery is still "ongoing"

**Comment by blobbernaut** [comment]
Try holding a bedsheet or drapes in your hand and a cautery in the other and clicking the area with the bedsheet/drapes, I know that works.

**Comment by JohnGinnane** [comment]
I have followed the steps on my local server and found that I can't recreate this issue. I tried the normal operation procedure using correct tools, then I used all ghetto tools (bedsheet, kitchen knife, wirecutters, and lighter) and found same result: It works.

I tried this on a human and an IPC. Is there a more thorough set of steps I could follow?

**Comment by JohnGinnane** [comment]
![image](https://cloud.githubusercontent.com/assets/3355198/15864179/eea32b6a-2ccd-11e6-934a-a8e66f2538e6.png)

**Comment by trifornt-tinfornt** [comment]
Thing is, try to actually do another surgery on John's eyes now that John has "finished" the surgery. It'll usually tell you that you need cauterize it.

**Comment by blobbernaut** [comment]
I seem to have a 0% success rate closing a surgery with the cautery though when doing it on myself

**Comment by ArcLumin** [comment]
Could not reproduce in any way
