### ISSUE TITLE
70 fucking issues, get your shit together coder bus

### ISSUE THREAD

**Issue by WhiteFox08** [HippieStationArchive/HippieStation13-1#2507]
god damn :hankey:

**Comment by Kokojos** [comment]
meme

**Comment by nalarmg** [comment]
Please do not use the issue tracker irresponsibly.

**Comment by WhiteFox08** [comment]
@nalarmg what about this irresponsible coding??????????

**Comment by WhiteFox08** [comment]
:eyes:

**Comment by Gandalf2k15** [comment]
who are you

**Comment by Kokojos** [comment]
wew why so angsty all of a sudden whtefox

**Comment by danhibiki** [comment]
Its because this isn't a tangible issue.
