### ISSUE TITLE
Can't rotate chairs

### ISSUE THREAD

**Issue by collinxchu** [HippieStationArchive/HippieStation13-1#251]
I WANT TO, BUT YOU JUST CAN'T NO MATTER WHAT OR WHO YOU ARE

AAAAAAA

**Comment by Nokington** [comment]
What do you mean? As a ghost or as a human/snowflake?

**Comment by Kokojos** [comment]
At all, it seems. Tested by making a chair, spawning a chair, and trying to rotate a chair on station.
