### ISSUE TITLE
Telescopic shield missing initial icon

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStationArchive/HippieStation13-1#2512]
See below the lack of icon for the telescopic shield in the Head of Security's locker:

![image](https://cloud.githubusercontent.com/assets/3355198/15944963/f9b38aac-2e87-11e6-80fb-0a20486c72cb.png)

![image](https://cloud.githubusercontent.com/assets/3355198/15944966/fc32af7e-2e87-11e6-95f9-67c45d4e21ea.png)

**How to reproduce:** None. It starts like this.
**How to fix:** Opening and closing the shield fixes it.

**Comment by Gandalf2k15** [comment]
Crystalll!!!!!!!!!!!!!!!!!!!!!!

**Comment by JohnGinnane** [comment]
I suspect it's incorrect icon_state in the new() proc. Should be very easy to fix. You up for this @Spacedong ?

**Comment by Gandalf2k15** [comment]
i already fixed it
ill let him do it
