### ISSUE TITLE
Nodrop items stay even if the limb holding them gets delimbed

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#2515]
This is   Unknown!
He is wearing   a blood-stained true roboticist's jumpsuit of the void +2!
He is wearing   a blood-stained robust labcoat of the forest +2!
He has   a major backpack of dexterity +4 on his back.
He is holding   a rusted cursed katana of the night -3 in his right hand.   !!!
He has a blood-stained hand!
He has   a blighted toolbelt of the sun -1 about his waist.
His head is missing!
His right arm is missing!   !!!
He has severe bruising!
He is bleeding!

**Comment by Gandalf2k15** [comment]
Confirmed. http://i.imgur.com/nXZTzHM.png
