### ISSUE TITLE
beheading husks creates a healthy head you can transplant

### ISSUE THREAD

**Issue by dreamcrab** [HippieStationArchive/HippieStation13-1#2516]
ADMINHELP: LuisReyesX: You can behead husks, it gives you the normal head (with name) and you can attach it to a new body. Neat

**Comment by LuisReyesX** [comment]
i can confirm this, i could clone 2 guys using this

**Comment by Spacedong** [comment]
fix it reeeeeeeeeee

**Comment by ghost** [comment]
It's not a massive issue, you can brain transplant husks anyway.

**Comment by LuisReyesX** [comment]
add the FUCK tag lad. Priority issue. Muh Inmershiuns

**Comment by danhibiki** [comment]
There has always been a way to revive husks, and usually it involved the head (although you needed to do surgery to remove the brain). If we're going to "fix" this, we should probably address if we want people revivable if they are husked otherwise.

**Comment by dreamcrab** [comment]
i mean, i dont mind it staying.. but it should be an unknown husked head. its kind of weird that it makes the head normal again when you chop it off, no?

im all for them being cloned still

**Comment by TDcoolguy300** [comment]
Probably because it grabs the user's real name rather than current name, which is to avoid the bugs of multiple heads named SHITLORD MCCOCKFACE because someone put a gasmask on them and the ID, the beheaded them

**Comment by dreamcrab** [comment]
alright well the only thing i understand about code is that i dont understand code

so if you guys think this is fine, then no worries

**Comment by Gandalf2k15** [comment]
This is fine

**Comment by Spacedong** [comment]
this is pretty much the same thing as taking the brain out and transplanting it (which nobody ever does anyway) so it's fine

**Comment by JohnGinnane** [comment]
Closing as it's not really an issue.
