### ISSUE TITLE
Adrenals not working/Glitching off screen.

### ISSUE THREAD

**Issue by TheRangerFrank** [HippieStationArchive/HippieStation13-1#2517]
http://puu.sh/po5aM/626c3bb0b5.png

Adrenals just seem to glitch off the screen, refuse to work. Resetting the top bar by pressing the little arrow does not work.

**Comment by doobiedoo23** [comment]
Try dragging the button

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Holding down your mouse on the icon and dragging it around lets you move it. It's a feature.

**Comment by TheRangerFrank** [comment]
How would I stop this? Because when i click the button the adrenals will not pop.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Adrenals have limited uses, you may have used them all up. Just clicking once and not holding it down triggers it.

**Comment by TheRangerFrank** [comment]
Mmm okay, Thanks.

**Comment by Kokojos** [comment]
Yeah it seems you dragged it off-screen and just used it enough times.
