### ISSUE TITLE
Security bomb suit missing icon

### ISSUE THREAD

**Issue by EvenInDeathIStillServe** [HippieStationArchive/HippieStation13-1#2530]
The security bomb suit has no icon when worn.

![](http://image.prntscr.com/image/a602a733faa24c3ea3a15ceab1bef62d.png)

**Comment by GenericGoose** [comment]
That icon isn't in icons/mob/suits.dmi (at least I can't find it)
Idk who to blame. TG doesn't have it either.
Maybe it's in some other file but searching for it would be painful as fuck. 
Can't find it, someone's gotta find it and shove back in.
If nobody noticed it's probably never used lol
Alright my dude found it and now im gonna PR it. Apparently it was removed in 2013 as unused. It's old and ugly as fuck but at least it will have an icon?

**Comment by Gandalf2k15** [comment]
This was fixed.
