### ISSUE TITLE
Cant refine carp fillets into regents

### ISSUE THREAD

**Issue by Erawh** [HippieStationArchive/HippieStation13-1#2535]
Carp fillets cant be grinded in a all-in-one grinder. 
Place carp meat into a grinder to test

**Comment by GenericGoose** [comment]
I don't yet know how it all works (or rather doesn't) but basically all snacks aren't grindable
https://github.com/HippieStationCode/HippieStation13/blob/5462010e5bcc8a61ad5618ffd0f04f07eeb570b0/code/modules/reagents/Chemistry-Machinery.dm#L1003
maybe this check doesn't work
https://github.com/HippieStationCode/HippieStation13/blob/5462010e5bcc8a61ad5618ffd0f04f07eeb570b0/code/modules/reagents/Chemistry-Machinery.dm#L1099

I totally remember that I was able to grind food into nutriments and meat was grindable sometime ago too.
Don't yet know how to fiks it. Also gotta refactor chemistry_machines, 1.5k lines of code and a lot of random machines, impossible to track history

Another theory is there's comment saying 'put all recipes above this' and then a recipe right below...If that's the case we can blame [this commit ](https://github.com/HippieStationCode/HippieStation13/commit/e9f5e9628911b0c5019cbca2f3e71e330fe9b4bb)
Nah, that's not it

**Comment by GenericGoose** [comment]
Alright[ this commit](https://github.com/HippieStationCode/HippieStation13/commit/7f33129131768f0fa5538787d5d09ae24a535c12) is to blame, I guess.
I'll revert it and check if things work. If they do i'll PR a revert.
Yeah, it really broke the grinder, I reverted and it works.
