### ISSUE TITLE
Clowns remain clumsy when thralled

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2536]
Read the title.

All other antag roles remove it.

Fix this.

**Comment by Sarcalogo** [comment]
[Balance] [Controversial] [Needs Head Input] [BAD FEATURE] [Feature] [Not a Bug]

**Comment by TDcoolguy300** [comment]
Technically thralling is not a round-start antag, as Thralls are created by Shadowlings. I would also like to note that clowns revved by revheads also keep their clumsy mutation. Closing.
