### ISSUE TITLE
HUD elements missing, need to be re-added

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#254]
Previously, we had both a stamina and hunger bar always present, but with the addition of movable UI, we lost those two icons

https://github.com/HippieStationCode/HippieStation13/commit/974456c7d6558b454afc0c499a0b2aeb2c752142

heres the commit we made when certain UI elements failed, so it should be in the removed code section

https://github.com/HippieStationCode/HippieStation13/commit/ac3cf331598a506d36bd3f67f7469503b0844532

 here is the commit that staminaloss was added as an icon

https://github.com/HippieStationCode/HippieStation13/blob/master/code/_onclick/hud/_defines.dm

doing a quick look at our _defines.dm in HUD, we're simply missing those two from there
i also looked up which commit the UI icons for the three missing HUD icons were removed, and it was during the initial port of movable UI, here https://github.com/HippieStationCode/HippieStation13/commit/183863a33cf722a7c21f92ec92efd59a81d709c9

In total, the HUD elements that need to be added are ui_nutrition, ui_temp, and ui_stamina

**Comment by ghost** [comment]
these elements are not coming back, i'll turn `ui_stamina` into a screen alert, and i'll check if `ui_nutrition` and `ui_temp` work, which as far as i'm aware, both work.

**Comment by danhibiki** [comment]
Nutrition pops up when its low, but isn't present otherwise. ui_temp is the same I believe, but only when its drastic temperatures. Could you lower the values they prompt at, or make them static?

**Comment by ghost** [comment]
I could change the values for `ui_temp` but i'm not planning to change `ui_nutrition` due to the fact that it only is relevant if you're getting hungry, which is when it pops up, i'd like to keep the screen clutter to a minimal, so i can use that side of the screen for other relevant bits of info.

**Comment by danhibiki** [comment]
I'm not going to argue to get nutrition to be a static HUD element, but I do think stamina needs to be one for sure with the existence of disablers and staminaloss from hallucinations and the like.

**Comment by ghost** [comment]
it doesn't need to be a static element, you only need to recieve an alert, when your stamina is getting low.

**Comment by danhibiki** [comment]
Why not make these toggleable UI elements, similar to how the rest of the system is implemented? If people don't want those icons on the side, they can toggle them off.

**Comment by HippieStation13** [comment]
"Why not make these toggleable UI elements, similar to how the rest of the system is implemented? If people don't want those icons on the side, they can toggle them off."

Approved.

**Comment by ghost** [comment]
There are no `toggleable UI elements` the entire reason i ported the initial version, which was approved, and pulled was to remove clutter, and make it easier for developers to integrate systems into the sidebar.

It replaces some of the hardcoded HUD icons defined at mob level with a pair of mob procs throw_alert() and clear_alert(). Alerts will appear on the top-right side of the screen.
You can shift-click alerts to get a description of what's wrong and sometimes a tip on how to solve the alert.

![](https://cloud.githubusercontent.com/assets/1389934/6449341/fd7e907c-c0d4-11e4-8629-85763d34939b.gif)

i also don't really want to add more unlogical code into the codebase, and option toggles that never get used, there are two things we can do at this point.
- add stamina as a alert.
- add stamina as an state for the `100%` health bar 
  - ![](http://x.hoax.io/6C7D14368263183K152Z1436826318179T3m14368263187T666J14368263189l.png)

**Comment by danhibiki** [comment]
The HUD is very much toggleable, you can hide visibility of a wide variety of icons using F12.

**Comment by ghost** [comment]
that's a super snowflaky system, which will be removed

**Comment by Kokojos** [comment]
Mid-range temperature need to be readded, whatever the system

**Comment by collinxchu** [comment]
Seems like a non-issue. Not displaying stamina when it's not required to display it is perfectly serviceable.
