### ISSUE TITLE
Dismembered heads don't seem to be affected by conveyor belts or the mass driver.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#2543]
I took a head I dismembered and dropped it on the conveyor belts in disposals and it wouldn't move. I then just manually moved it onto the mass driver. While everything else fired off into space, the head just stayed there. Seems weird.

**Comment by TDcoolguy300** [comment]
This is because they are "anchored", they can not be moved by normal means such as dragging, belts, and are too massive to fit in crates. But you can still pick them up because they are still items.

**Comment by Kokojos** [comment]
Simple 1 var change fix I mean, why would they ever need to be anchored?

**Comment by ghost** [comment]
It's so you cant drag them.

Same reason you cant put them in a backpack and it slows you to carry them, they're supposed to be hard to transport so you dont get fuckboys stealing heads I guess.

**Comment by trifornt-tinfornt** [comment]
I have no idea why these would not only need to be gigantic, but also be anchored. It's not like you can't just remove the brains from the head and carry on.

**Comment by Carbonhell** [comment]
That takes time,whereas chopping someone's head off and running away With it is Too op

**Comment by trifornt-tinfornt** [comment]
Not really, it takes a matter of seconds - and any sharp object can remove the brain so once you dismember them it's another two seconds to take their brain out. Not overpowered at all.

**Comment by GenericGoose** [comment]
you can drag bodies but can't drag heads
whats the fucking point it takes longer to chop off a head
you still can put them in a locker in maint and nobody will ever find them

**Comment by Kokojos** [comment]
Technicly not a bug, shitty feature that's apparently here to stay.
