### ISSUE TITLE
A.I. unable to complete traitor objective "Stay alive until the end"

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStationArchive/HippieStation13-1#2545]
Was a traitor AI (not malf) whose last objective was to stay alive until the end. I completed all other objectives (3 kills) no problem, but failed the last despite nothing happening to my core.

**Comment by ghost** [comment]
Is this tied to how being AI'd and Borged counts as death for tator objectives?

**Comment by JohnGinnane** [comment]
Unsure. I started the round as A.I.

**Comment by ghost** [comment]
I tested as round start AI and I succeeded the objective.
I can't reproduce this.

**Comment by JohnGinnane** [comment]
Interesting... I don't have a screen cap but it definitely happened. I'll
try to recreate on my machine, as well as look into what satisfies this
objective's goal

**Comment by Kierany9** [comment]
Just happened.

![fix this](http://i.imgur.com/eisgaXL.png)

**Comment by Kierany9** [comment]
Fixed

**Comment by JohnGinnane** [comment]
I think by not having "fixed" right in front of the issue number it didn't recognise
