### ISSUE TITLE
Direct flashes don't flash you for real anymore.

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#2547]
No more white screen when you get directly flashed, but I saw it when I was flashed indirectly.

**Comment by Gandalf2k15** [comment]
right I'll look into this

**Comment by Gandalf2k15** [comment]
Okay can't recreate.

**Comment by Gandalf2k15** [comment]
http://i.imgur.com/KUsAONX.png

**Comment by Gandalf2k15** [comment]
Aight tested with two people(on server), cant recreate.
http://i.imgur.com/ms7MgLB.png
http://i.imgur.com/ChfUAGp.png

**Comment by McHatters** [comment]
What version of BYOND were you on?

**Comment by Kokojos** [comment]
510, freshly updated. Maybe I just hallucinated, if you can't recreate it, il close it.
