### ISSUE TITLE
AI asimov core laws don't include birds/lizards/ipcs

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#256]
Pratically, I saw on tg and other places that the asimov core lawset has been replaced with an humanoid core lawset, which laws are:
1) Lizardperson, Birds and Humans are classified as Humanoids
2)You may not injure a humanoid being or, through inaction, allow a humanoid being to come to harm.
3)You must obey orders given to you by humanoid beings, except where such orders would conflict with the Second Law.
4)You must protect your own existence as long as such does not conflict with the First or Second Law.

Just to make sure that AIs don't kill birds and lizards because they gave a punch to an human.

**Comment by AliiTea** [comment]
This can also be solved with admins... Just job ban the shitters

**Comment by Nokington** [comment]
If an AI on asimov is killing snowflakes then an admin should be stepping in to stop it. The AI still falls under rule 1.

**Comment by AliiTea** [comment]
Tada - closing this as it's been solved.
