### ISSUE TITLE
/datum/design/bot_upgrade is constructable.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2561]
Exosuit fabricators -> Cyborg upgrades -> First entry.
This is kinda bad since it causes runtimes, shouldn't be doable and prevents the machine from building anything new until you deconstruct the machine.

**Comment by JohnGinnane** [comment]
Blame me, I wrote that object. I'll fix in the next hours when I'm home

**Comment by ArcLumin** [comment]
This has been fixed
