### ISSUE TITLE
HEV suit is not fully spaceworthy.

### ISSUE THREAD

**Issue by Gandalf2k15** [HippieStationArchive/HippieStation13-1#2564]
Fix

**Comment by ArcLumin** [comment]
I was never sure if this was a feature or not

**Comment by GenericGoose** [comment]
is it supposed to be? description doesn't seem to say that and I don't think it was in hl

**Comment by Pyko1** [comment]
Its some kind of armored hazmat suit, I dont think its supposed to me spaceproof.

**Comment by blobbernaut** [comment]
Not supposed to be, but it does make you a lot better at being in space.

**Comment by TDcoolguy300** [comment]
This was intended, as the HEV is for hazardous environments, not a low pressure environment. The fact that it protects you partially is decent as an armored suit.

**Comment by JohnGinnane** [comment]
If it's supposed to be anything like the one in Half-Life it should be space-worthy, as seen in Xen

**Comment by TDcoolguy300** [comment]
But Xen wasn't really space, there was alot of shit there that sorta didn't make sense, whose to say Xen had some form of air?

**Comment by JohnGinnane** [comment]
Good point, but shouldn't it still protect the user from high/low pressure?

**Comment by TDcoolguy300** [comment]
I'd say it would protect more from high pressure than low, because i don't think anyone at Black Mesa expected it to go into a low pressure enviroment

**Comment by Gandalf2k15** [comment]
I'll amend this then

**Comment by Spacedong** [comment]
gandalf i'd close this tbh
