### ISSUE TITLE
Sticking a bunch of people/bodies in an object then slamming it against a supermatter will kick all players involve and let them respawn

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2567]
Longass title.

Basically, I first noticed this in a ripley, holding a closet of 3 dead bodies. Went to go lift the supermatter into my cargo compartment when lagspikes hit and I ran into the supermatter. Immediate kick and disconnect from the game, when I logged back in, I was able to rejoin as a fresh new character, and not just me, but everyone who was a dead/ghosted that I had in the locker was kicked and forced to make a new character

Steps to replicate:
Load a locker of players into a ripley
Walk into the supermatter

**Comment by GenericGoose** [comment]
lmao what the frick is this 
meme of the year

**Comment by ArcLumin** [comment]
It's absolutely insane, especially since Ripleys can hold 60 or so bodies in their compartments. This allows anyone to take dead bodies and force them to respawn as a new job.

**Comment by Spacedong** [comment]
I tried this, completely closes connection and boots everybody inside.

**Comment by Spacedong** [comment]
No remains are spawned or anything which is unusual as when people bump into the supermatter they leave skeletal remains.

**Comment by ArcLumin** [comment]
It even deletes their ghosts, or more properly, doesn't make them. It just boots them and lets them rejoin

**Comment by ArcLumin** [comment]
It even deletes their ghosts, or more properly, doesn't make them. It just boots them and lets them rejoin.
You can even do this to dead bodies who HAVE ghosts out, it'll boot the ghosts not attached to their body either.

Super meme bug

**Comment by TDcoolguy300** [comment]
I'd like to mention it's that the supermatter shard, for whatever reason, deleting the lockers improperly, i don't know why though

**Comment by ArcLumin** [comment]
Not just the shard, the full on supermatter too. And not just the locker, the mech and the driver too.
