### ISSUE TITLE
You can throw around the SM Shard and SM with telekenesis grab.

### ISSUE THREAD

**Issue by toolboxtothehead** [HippieStationArchive/HippieStation13-1#2571]
Yes. It is exactly as cancerous as you think it is. You can fling the SM around with telekenesis.

**Comment by Pyko1** [comment]
Last time I tested this it did not kill people tho when you beat em with SM. So it was not that useful in the end.

**Comment by blobbernaut** [comment]
No, it is absolutely not as cancerous as you think it is. Throwing it at somebody does not disintegrate them. Also, the new supermatter explodes when it hits something, so actually getting one you can throw around requires a cargo crate.

**Comment by ghost** [comment]
I wouldn't say this is a feature.
TK grabbing it should disintegrate you.

**Comment by Pyko1** [comment]
Not exactly bug either, at least codewise.

Maybe make it unable to be moved with TK, or make all big items move a lot slower when TK grabbed (lockers/welding tanks/SM/etc). I really fail to see why or how the SM is supposed to gib someone over a telekinetic grab.

Even tho TK grabbing the SM is ultimately pretty useless considering to the effort it takes to get TK and to order the shard, when all you can do is move it and people have to bump on to it themself.

**Comment by Spacedong** [comment]
remove it before it becomes the new meta

**Comment by Nebyab** [comment]
> meta
> die spacedong

**Comment by Pyko1** [comment]
its practically useless as long as people don't walk on it themself. And even then you gotta go order a new one for next person.

Quite frankly TK + Toolbox gets more kills in a minute.

**Comment by Spacedong** [comment]
what are you talking about

**Comment by Spacedong** [comment]
why would you have to order a new one for the next person

**Comment by Pyko1** [comment]
pretty sure the shard detonates nowdays when people get killed by it.

**Comment by Spacedong** [comment]
no??

**Comment by Pyko1** [comment]
oh wait its the launch shit, but still, its more or less useless, as hitting people with it does nothing.

**Comment by Spacedong** [comment]
yeah but they can easily walk into it if you hit them with it while they're running

**Comment by Pyko1** [comment]
still easier to just throw anything in it and then toss them in, instead of trying to bait them to walk in it.

**Comment by Pyko1** [comment]
It sounds great on paper, but absolutely useless on practice compared to the usual SM shennigans.

**Comment by GenericGoose** [comment]
kek just fiks this nonsense

**Comment by blobbernaut** [comment]
this isn't a bug and it isn't overpowered, fucking close this

**Comment by Spacedong** [comment]
close this too, non-issue, if needed to be changed suggest it on the forums
