### ISSUE TITLE
AIs sometimes start out blind. (Crit blind)

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2574]
This is the second time I've seen someone suffer this.
It's pretty severe.

**Comment by JohnGinnane** [comment]
Were you able to fix it on the server? If so how did you do it?

**Comment by ghost** [comment]
I couldn't.
I'm gonna check to see if it's to do with status flags though.

**Comment by TDcoolguy300** [comment]
Fairly sure it's a 510 issue, as failing to update to 510 causes the plane shit to fuck up and always display.

**Comment by ghost** [comment]
The guy said he was on 510.

**Comment by TDcoolguy300** [comment]
Latest build?

**Comment by ghost** [comment]
Yep.

**Comment by ghost** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/b149a510ae9aa5a2ea4339f59c14b69b42794bdb/code/modules/mob/living/silicon/ai/life.dm#L108
This only fires if the APC is turned back on before the fault is confirmed.

I imagine in the 2 if statements here:
https://github.com/HippieStationCode/HippieStation13/blob/b149a510ae9aa5a2ea4339f59c14b69b42794bdb/code/modules/mob/living/silicon/ai/life.dm#L71
and here:
https://github.com/HippieStationCode/HippieStation13/blob/b149a510ae9aa5a2ea4339f59c14b69b42794bdb/code/modules/mob/living/silicon/ai/life.dm#L75

The remove overlay proc should be called.
