### ISSUE TITLE
Using the Library Computer to check out books crashes clients

### ISSUE THREAD

**Issue by Nebyab** [HippieStationArchive/HippieStation13-1#2577]
http://hippiestation.com/showthread.php?tid=4346

Reports coming in from several people, this one is on the forums.

**Comment by Spacedong** [comment]
didn't crash me at all

**Comment by Spacedong** [comment]
this never crashed me in all the times ive done it, they either need to upgrade byond or some shit

**Comment by Gandalf2k15** [comment]
This is actually a confirmed bug.

**Comment by Spacedong** [comment]
still tested it, every test I do, on server or on local never works, I never crash. /shrug

**Comment by ArcLumin** [comment]
This is fixed.
