### ISSUE TITLE
Stuff that should temporarily blind you instead blinds you forever

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#2578]
Someone shot an ion gun at me while I was a regular crew member and it permanently blinded me for some reason, also happened while I was AI and someone shut off my APC. My sight did not come back when the breaker was switched back on.

**Comment by McHatters** [comment]
This has been happening quite a bit now that I think about it. I remember an AI that got blinded by an explosion on his core too, and he stayed blind after being carded and put into a new shell.

**Comment by TDcoolguy300** [comment]
Some things that need to be replaced, i'll look into it when i can

**Comment by ghost** [comment]
AI being blind forever from APC has been fixed I do believe.

**Comment by GenericGoose** [comment]
ai blindness was fiksd and issue seemed to be the same

**Comment by Spacedong** [comment]
this is fixed methinks

**Comment by TDcoolguy300** [comment]
Not 100% sure on this

**Comment by Kokojos** [comment]
Pretty sure this is fixed.
