### ISSUE TITLE
Security Escape pod lags client to hell

### ISSUE THREAD

**Issue by AliiTea** [HippieStationArchive/HippieStation13-1#2582]
![](http://i.imgur.com/hBPUb1L.png)
lagged to hell after this happened while watching it.. no idea what caused it

**Comment by danhibiki** [comment]
I assume by lag you mean specifically a frame rate drop? Can you tell us more about this situation, was this a normally occuring event or did an admin do any kind of fuckery?

**Comment by Gandalf2k15** [comment]
Far too specific to be a bug.
