### ISSUE TITLE
Secure safes aren't secure

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2597]
This is a HELLA old bug, and one I keep forgetting to put up here, but it's been around since secure safes have been around, I think.

Alt clicking any secure safe will open it and let you take anything out, regardless of what locks are on it. You can't put anything in it though.

**Comment by Spacedong** [comment]
fixed, close this

**Comment by ArcLumin** [comment]
This isn't fixed lads

**Comment by Spacedong** [comment]
it IS fixed though

**Comment by ArcLumin** [comment]
> not fixed

http://puu.sh/q59LE SPESSDONK PLS
Literally roundstart

**Comment by ArcLumin** [comment]
Has been fixed
