### ISSUE TITLE
Blue Space RPED has no sprite

### ISSUE THREAD

**Issue by Gandalf2k15** [HippieStationArchive/HippieStation13-1#2601]
Awh(inhand)

**Comment by ArcLumin** [comment]
You mean in hand sprite? It has a on ground sprite

**Comment by Spacedong** [comment]
this isn't a bug?

**Comment by Spacedong** [comment]
this is not a fucking bug, tons of items have no inhand sprite, fucking close this already, christ

**Comment by Spacedong** [comment]
for the last, fucking, time, close this, a lot of sprites DO NOT HAVE INHAND SPRITES
