### ISSUE TITLE
Taking a human shield doesn't actually protect you from bullets

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#2629]
To clarify, getting somebody into a neck grab and trying to use them as a shield does not protect you from projectiles. This happened during a ling round in which I was under siege by the HoS and decided to use the warden as a shield by putting them in a neck grab and putting their sprite between me and the HoS.

The warden's sprite was clearly positioned between me and the HoS, yet the electrode he shot flew right past my meatshield and nailed me in the face.

I'm super salty that my hostage taking strategy didn't work, please fix this.

**Comment by Spacedong** [comment]
it has a chance of protecting you or not IIRC

**Comment by Spacedong** [comment]
theres a chance it doesnt work, remove this, its not a bug
