### ISSUE TITLE
Area defines suck

### ISSUE THREAD

**Issue by collinxchu** [HippieStationArchive/HippieStation13-1#263]
At the moment, in the editor the defined pathing for areas is just abyssmal.

http://puu.sh/j2y3Z.png
http://puu.sh/j2y62.png
http://puu.sh/j2y6T.png

At the moment, that is how split up the minisat is, in terms of area.
It's awful. Fixing pathing to be more logical and clean should happen thx.

**Comment by Jaygriff** [comment]
They are pretty abysmal, but the map is a relatively small deal as it doesnt affect any game elements and is strictly up to the mappers.

**Comment by Kokojos** [comment]
There are, but this is not an issue at the moment.
