### ISSUE TITLE
Clients calling an admin proc on join

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#2636]
https://github.com/HippieStationCode/HippieStation13/blob/b459dde967ccdf983b35c0f4e69ef1edab6b40fd/code/modules/client/client%20procs.dm#L290

**Comment by Spacedong** [comment]
this is related to the new ahelp system right? @Gandalf2k15

**Comment by Gandalf2k15** [comment]
yah

**Comment by Spacedong** [comment]
is this fixd @Gandalf2k15

**Comment by Gandalf2k15** [comment]
will be soon

**Comment by ArcLumin** [comment]
This is fixed, close this
