### ISSUE TITLE
Bluespace capsules can be put in moving space

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2646]
Title. Makes for some killer autism forts

http://puu.sh/q7nUK.png

**Comment by Gandalf2k15** [comment]
wew

**Comment by Spacedong** [comment]
just remove these piles of shit, they're the worst thing ever and they serve no purpose

**Comment by Gandalf2k15** [comment]
please dont i plan on doing cool shit with this

**Comment by ArcLumin** [comment]
http://puu.sh/q7tLS.png　ＣＯＯＬＳＨＩＴ

Ａｌｓｏ，　Ｉ　ｒｅａｌｌｙ　ｌｉｋｅ　ｂｓ　ｃａｐｓｕｌｅｓ，　ｔｈｅ　ｂｉｇｇｅｓｔ　ｉｓｓｕｅ　ｂｅｉｎｇ　ｔｈａｔ　ｙｏｕ　ｃａｎ　ｇｅｔ　ｔｈｅｍ　ａｔ　ｒｏｕｎｄｓｔａｒｔ　ｎｏｗ　ｗｉｔｈｏｕｔ　ａｎｙ　ｉｓｓｕｅｓ．　Ｏｎｃｅ　ｔｈａｔ　ｓａｆｅ　ｉｓ　ｐａｔｃｈｅｄ　ｉｔ’ｓ　ａｌｌ　ｇｏｏｄ

**Comment by GenericGoose** [comment]
bs stands for bullshit
i remember someone broke shuttle or something with them and i ded ples restart

**Comment by ArcLumin** [comment]
Confirmed, you cannot use the 4 on the station to reach centcom, no matter which ride you take

**Comment by ArcLumin** [comment]
http://puu.sh/q8bED.png BUT YOU CAN DO IT IN 5

**Comment by blobbernaut** [comment]
I mean this is kinda hilarious and I hope it stays

**Comment by ArcLumin** [comment]
http://puu.sh/q8bO9.png best response to me breaking into centcom

**Comment by Spacedong** [comment]
lmao

**Comment by blobbernaut** [comment]
#feature

**Comment by blobbernaut** [comment]
Bluespace capsules create safe stable forts in the bluespace realm, fits in lore definitely feature

**Comment by ArcLumin** [comment]
I agree, 100% lore, we should keep it

**Comment by Voratius** [comment]
REMOVE THIS SHIT FEATURE! IT HAS ABSOLUTELY NOTHING POSITIVE TO ADD EXCEPT TO RUIN ROUNDS AND BE GENERALLY USELESS !!!

**Comment by ArcLumin** [comment]
b-but muh instant autism forts

**Comment by ArcLumin** [comment]
Spacedong also made his own, https://github.com/HippieStationCode/HippieStation13/issues/2649

**Comment by ghost** [comment]
blue space capsules aught to be removed.

**Comment by GenericGoose** [comment]
remove this kanser until its fuking fiksed all these things do is break literally anything that komes into kontakt whats the fuking point

**Comment by Spacedong** [comment]
@generalgoose why do u talk like that r u a kindergartener

**Comment by Spacedong** [comment]
I dont really see the point of the capsules really, they're so invasive and annoying, I'm not even sure what they're supposed to be used for

**Comment by ArcLumin** [comment]
They're an emergency shelter to protect you on the asteroid if you crash land there

**Comment by Spacedong** [comment]
gay

**Comment by GenericGoose** [comment]
@Spacedong im typing like that because my keyboard is almost as broken as bullshit capsules (and cant care enough to use screen one)
remove from premises

**Comment by ArcLumin** [comment]
This can be closed considering bluespace capsules were removed
