### ISSUE TITLE
Canned laughter makes you spam the laugh emote constantly

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#2656]
Spams it like once per second, which quickly becomes incredibly annoying. I was legitimately on the verge of lynching someone who had canned laughter in their system.

It should force you to emote like once every 5 seconds, not spamming the emote like it currently does.

**Comment by GenericGoose** [comment]
kek just add prob thing or maybe it should start after some cycles too

**Comment by GenericGoose** [comment]
should be fiksed klose https://github.com/HippieStationCode/HippieStation13/pull/2657
