### ISSUE TITLE
Firefighter APLU has worse defenses than the Ripley APLU

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2667]
It's supposed to be the fancy nicer version so why is it's armor shittier? It has more health, but far less armor

**Comment by ghost** [comment]
The only thing that doesn't make sense is the fact it has less fire protection?
Issue tracker isn't really meant for balance, that's what the forums are for.

**Comment by ArcLumin** [comment]
Fair enough. I see balancing issues here occasionally, but if this isn't the place for it, I'll close it.

**Comment by ghost** [comment]
I do try to keep active on the suggestions part of the forum.
