### ISSUE TITLE
You can lock open lockers

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2668]
Unsure if this is a bug but it's a bit of a balancing issue. You can open a lockable locker, drag something on it to prevent it from closing and click on it, it'll lock instead of closing. Then you can have it both opened and locked, and have it be locked whenever it closes

This allows you to easily get anyone to stand on the open locker tile in the halls, close it and they can't escape.

**Comment by ghost** [comment]
The mere fact you can instantly capture people like this is pretty funny though

**Comment by blobbernaut** [comment]
This is great, don't remove

**Comment by ghost** [comment]
Not the right attitude tho
