### ISSUE TITLE
PDA screen not able to be closed

### ISSUE THREAD

**Issue by Firerobot25** [HippieStationArchive/HippieStation13-1#267]
I believe it happened by my Pda and body being gibbed by the singularity while my PDA screen was up, making it 99% impossible to close, even when I was respawned as a death commando.

**Comment by Nokington** [comment]
@Firerobot25 Did you try relogging?

**Comment by Jaygriff** [comment]
Relogging fixes it, but we really should make a stat checker on PDA functions.

**Comment by Firerobot25** [comment]
I hadn't tried to relog due to it being end of round

**Comment by nalarmg** [comment]
Unable to reproduce locally. Closing PDA seems to work fine, even if it's destroyed. Can someone else confirm this is an issue please?

**Comment by Firerobot25** [comment]
I had it on the PDA message screen  (where you choose to message someone) and was gibbed by singularity
