### ISSUE TITLE
New batteries in mechs are always faulty

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2671]
Title, putting a new battery into any mech fucks it up.

**Comment by Gandalf2k15** [comment]
This is only for Protolathe. Mech fabs are not faulty.

**Comment by ArcLumin** [comment]
Not an issue; mech fabricators always make items with 100 reliability, and protolathes make variable reliability

**Comment by ArcLumin** [comment]
Well, it IS an issue, but not a bug, a balancing issue

**Comment by Kokojos** [comment]
@ArcLumin This means that this isin't always the case then?

**Comment by ArcLumin** [comment]
If a battery has a reliability of less than 100, it will short circuit in a mech. Protolathes only make batteries with reliabilities under 100 unless they're like, stupid basic and you're upgraded. however, mech fabs, autolathes, pretty much any other ways of getting a battery are 100 reliability, so it won't short circuit.
