### ISSUE TITLE
Plastic flaps block atmospherics

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2673]
I mean, they're plastic flaps. With tons of space in them. But they completely block all atmospherics. 

More of a nitpick than an issue, just seems weird that tiny strips of plastic block all air.

**Comment by Spacedong** [comment]
they're airtight, just not in pronounced in the name, other servers they're called "airtight plastic flaps" its a feature since they were added

**Comment by Carbonhell** [comment]
Not a bug,it's a feature, therefore discuss it on the forum if ya want it removed for some weird reason
