### ISSUE TITLE
Exosuit Fabricator has an unnamed misc entry that will endlessly produce nothing when queued

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#2677]
![](http://image.prntscr.com/image/a468997690eb4beabad3277fdfd0f7af.png)

What the title says. The machine will be unavailable as it will be stuck making nothing.

**Comment by ghost** [comment]
https://github.com/HippieStationCode/HippieStation13/issues/2561
Same issue.

**Comment by McHatters** [comment]
whoops
