### ISSUE TITLE
glitch with oxygen tanks

### ISSUE THREAD

**Issue by desertofunknown** [HippieStationArchive/HippieStation13-1#2683]
I had a nearly full oxygen tank a normal mask and a normal space suit from eva and it was working fine for 5~ minutes and then all of a sudden with 506kpa left in the tank i couldnt breath i was an antag at the time had all objectives complete so it was pretty upsetting when it happened

**Comment by ghost** [comment]
Was it one of the reddish ones?

**Comment by desertofunknown** [comment]
large blue one with a line through

**Comment by ghost** [comment]
You didn't have any smaller tanks in pockets, belt slots or whatever either?

**Comment by desertofunknown** [comment]
I also had it on my back

**Comment by desertofunknown** [comment]
Nope it was the only one I did have a jetpack but i dropped it several times to see if that was it while i was dying and disabled/re enabled the mask but it didnt fix it i guess it could have been somehow the jetpack glitched as being in the slot im not sure

**Comment by ghost** [comment]
I would imagine that could be the case. Still a bug if you're breathing a jetpack that you dropped and picked up again though.

**Comment by ArcLumin** [comment]
You actually need to walk a few tiles away for a dropped breathing item to stop being used by your internals, which IS a bug

**Comment by ArcLumin** [comment]
Could not reproduce

**Comment by Pyko1** [comment]
Closing, as cannot be reproduced. If problem persists make a new issue or reopen.
