### ISSUE TITLE
You can die but your screen will still say you're at full health, and you'll have deepcrit vision

### ISSUE THREAD

**Issue by doobiedoo23** [HippieStationArchive/HippieStation13-1#2690]
Reported by a player. 
ADMINHELP: Carlarc/(Carlarc) (?) (PP) (VV) (SM) (TP) (FLW) (R): alright. so what happened was I was running from beepsky with strained muscles, decided to turn off said thing, and suddenly fell unconscious. or at least I thought I was unconscious, apparently I was dead. it had all the signs of being unconscious, (black screen minus my character) but when examined I was dead

**Comment by carlarc** [comment]
also, you could hear my apparent corpse coughing.

**Comment by ArcLumin** [comment]
Fixed via https://github.com/HippieStationCode/HippieStation13/pull/2785

**Comment by ArcLumin** [comment]
This is fixed, please close
