### ISSUE TITLE
Xenobiology chemicals bug.

### ISSUE THREAD

**Issue by kaptem** [HippieStationArchive/HippieStation13-1#2692]
Xenobio chemicals do not apply effects when shot out of a  Odysseus medical mech syringe gun.

**Comment by ghost** [comment]
Do you mean like slime cores?

**Comment by kaptem** [comment]
Advanced Mutation Toxin and Mutation Toxin are chemicals that can be extracted from slime cores, as well as others on the wiki I am not currently aware of.

**Comment by GenericGoose** [comment]
did you shoot them at slimes? or people? is it a problem with chemicals or the target?
most likely slimes just aren't affected by syringes

**Comment by Carbonhell** [comment]
I remember shooting people with advanced mutation toxin and making everyone a slime,you sure it doesn't work?Did you wait for the reagent dispenser to reload?

**Comment by kaptem** [comment]
Nevermind, I was mistaken, this post is false, I tested it myself and found it actually does work, my bad.
