### ISSUE TITLE
If X pulls Y, Y can't pull Z at the same time

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#2708]
if we fix this we can make trains of pulled people,which is amazing in my opinion

**Comment by TDcoolguy300** [comment]
This is due on how the pull action works, it only does the pulling when Person X or Y moves using the keys, but should Y be forcefully moved to another tile, it doesn't trigger the same process as moving with said keys.

**Comment by TDcoolguy300** [comment]
Also, this is intended so that air and shit can push your shit around

**Comment by ArcLumin** [comment]
I figured admins would already know how to make trains of dudes pulling because they make trains of dudes pushing it in all the time

**Comment by JohnGinnane** [comment]
I tried this a while ago and found it difficult to implement due to all the places pulling is checked and handled. Would be fantastic to have a chain of prisoners though

**Comment by ghost** [comment]
Does this mean you cant snatch shit from people in hallways?

**Comment by TDcoolguy300** [comment]
Yes and no Mithrandalf, the checks whether the item being pulled or not is adjacent is still a thing. So if you were to just push the guy to the side, he would still be grabbing it, but if you were to push him down and then grab the crate, you would have it.

**Comment by TDcoolguy300** [comment]
Also, @ArcLumin It's not possible for admins to it like that in the game, BUT i think Rollerchair carting is a thing.

**Comment by ghost** [comment]
Can't people use grabs and the front guy just drags to achieve a similar effect? With mobs anyway.

**Comment by TDcoolguy300** [comment]
No, as moving someone via a grab is considered a forced movement, therefore the guy being dragged loses HIS drag.

**Comment by GenericGoose** [comment]
how would I stop someone from following me if he pulls me and I move

**Comment by JohnGinnane** [comment]
Pulling is one way only

**Comment by TDcoolguy300** [comment]
^

**Comment by ArcLumin** [comment]
I didn't figure you'd easily be able to make pull code into trains, but maybe you could make grabcode into chains? Like, chained together handcuffs, to make prisoners walk in a single file. Simply make each person grab another? Would still require a bit of work to grabcode, dunno if it'd be more viable or the same

**Comment by JohnGinnane** [comment]
I think it'll require a lot of the pull-code to be rewritten or heavily modified

**Comment by Kokojos** [comment]
Working as intended.
