### ISSUE TITLE
Captain's gloves are borked

### ISSUE THREAD

**Issue by doobiedoo23** [HippieStationArchive/HippieStation13-1#2716]
no sprite and when you put them on all it does is fuck up your sprite

**Comment by ArcLumin** [comment]
I legit thought we had an issue on this already, but appears not

Been like this for a few weeks now.

**Comment by ArcLumin** [comment]
Fixed in https://github.com/HippieStationCode/HippieStation13/pull/2860

**Comment by ArcLumin** [comment]
Fixed, close this
