### ISSUE TITLE
Supermatter radiation is weird+radiation is bad in general, oh look this was fixed 2 years in the future rejoice

### ISSUE THREAD

**Issue by KayeArray** [HippieStationArchive/HippieStation13-1#2746]
So I was doing some testing and noticed that supermatter radioactivity (both shard and the big fat) works  in a very snowflakey way that doesn't conform to other radiation sources, it doesn't pulse radiation normally like say the nuke core for example (no messages in admin log) and the Geiger counter doesn't detect shit even if you stand next to it, also the radius of the radiation it pulses is really small yet the pulse is really strong (this doesn't make sense imo it should be a much bigger radius but a weaker pulse), also it no longer spreads radiation from inside mechs anymore which is ;(. 

Another thing to note is how weak radiation is in general, I pumped someone full of radium and mutagen and they had over a 100 rads constantly for several minutes and yet they survived with only 40 toxin damage, wtf lads. Plus uranium is useless and gives you like 1 rad maximum, IMO you guys need to make supermatter great again and buff all radiation and uranium to not be total trash tier, hell allowing radiation to spread through the air like gas and irradiate the station would be nice too.

**Comment by KayeArray** [comment]
someone tag this with bad feature please .

**Comment by Spacedong** [comment]
are you suggesting introducing an entirely new type of gas to the atmos system because that'd be ridiculously hard considering someone would have to mess with atmos code from  like 2011 lmao

**Comment by Pyko1** [comment]
The whole radiation system is a bit bad to be honest.

One solution to fixing it up altogether would be to code it work same way as light.
Where radiation sources "light up" tiles around them with radiation sameway as lamps work.
Of course this radiation "light" would be invisible, except when using some kind of scanners.

Most of the ground work is already done in the lightning code, and beakers with radium and shit could just work like flashlights adding the radiation around you like lamps add light.
Then we just need to make a system that translates this radiation "light" in to rads in people.

**Comment by KayeArray** [comment]
That sounds like a decent idea, and have all radiation sources have a massive radius with strength decreasing exponentially with distance and possibly the ability to 'contaminate' objects and food which are exposed for long enough.

**Comment by GenericGoose** [comment]
is suggested 'light' system different from the way radiation works now? doesn't it just pulse radiation every tick?

**Comment by KayeArray** [comment]
Well rather than just pulsing in a small radius it would instead be a giant invisible field of constant radiation of varying strength and it would also allow stuff like beakers of radium to work as hazards as well like pyko suggested.

**Comment by danhibiki** [comment]
Issue tracker isn't a place to make suggestions

**Comment by KayeArray** [comment]
Which is why I'm stating that supermatter snowflakeyness + radiation being garbage is an issue that needs to be fixed.

**Comment by danhibiki** [comment]
Except what you are listing isn't a bug, its working as intended, its just not the effect you want or think should happen.

**Comment by KayeArray** [comment]
Well there is a bad feature tag for a reason.

**Comment by Pyko1** [comment]
Even tho its not really a bug, i do recall we had some issues how shitty the current radiation system is before as well.

At least I do see some merit in keeping this open for now just for discussion as the current system is pretty much snowflakes for every rad source.

**Comment by GenericGoose** [comment]
then light-based radiation sounds good
wouldnt a shitton of giant fields that vary in strength kill performance tho?

**Comment by KayeArray** [comment]
Lights don't really seem to affect performance much so I don't think so?

**Comment by GenericGoose** [comment]
well i dunno 
using commands that break all lights / repair them seems to lag server somewhat, though it is a massive change, it's not too bad

**Comment by danhibiki** [comment]
@banthebantz thats because tags are shared between issue and pull requests. All your doing is adding one more issue, which already skews the tasks we have to tackle.
