### ISSUE TITLE
Rolling over broken glass in a wheelchair counts a stepping on it

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#2749]
Basically the title. If you go over broken glass in a wheelchair and you don't have shoes, it will act like you are stepping in it normally. Not sure if it works if you have both legs blown off.

**Comment by ArcLumin** [comment]
Fixed in https://github.com/HippieStationCode/HippieStation13/issues/2762

**Comment by ArcLumin** [comment]
This is fixed, as I posted above. Please close this
