### ISSUE TITLE
Quartermaster's Cloak deleting objects.

### ISSUE THREAD

**Issue by Chewierulz** [HippieStationArchive/HippieStation13-1#2751]
Problem Description: Holding the Quartermaster's cloak in the active hand and clicking on items like jumpsuits or PDAs deletes them.

What did you expect to happen: I expected to have the cloak on the jumpsuit.
What happened instead: Deleted several items I clicked on.

Why is this bad/What are the consequences: Deleting PDAs, IDs etc

Steps to reproduce the problem: Picked up the cloak from the QM's locker, held in left hand and tried to equip.

Server: Hippie

Revision: https://github.com/HippieStationCode/HippieStation13//commit/0a9adaeb95bb09a8e50bec0df885bebd40f2ed80

**Comment by ghost** [comment]
The Quartermaster giveth, and The Quartermaster taketh away.

While hilarious how the fuck did this happen?

**Comment by Chewierulz** [comment]
Nevermind, turns out the CLOAK is a BACKPACK. I expected it to be worn like armour at least.

**Comment by JohnGinnane** [comment]
Does this mean you can put items in a cloak?

**Comment by Kierany9** [comment]
I'll just leave this here. Cloaks can be toggled to work as a backpack _or_ armour.

https://github.com/HippieStationCode/HippieStation13/pull/2357
