### ISSUE TITLE
Relic Issues

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2763]
All relics, save the spawner ones, seem to be broken.

The spawner ones, which normally need 2 people to chant the phrase to activate, you can do it with just one and a station bounced radio

**Comment by ArcLumin** [comment]
Also the food spawners can spawn burgers even though they're supposed to be blocked, and this includes roburgers

**Comment by Carbonhell** [comment]
they're not broken,they just activate if the requirements are met, for example the one which heals brute activates only if you're actually damaged

**Comment by ArcLumin** [comment]
they give no reaction to your phrase unless its a spawner, however

**Comment by Carbonhell** [comment]
they do..?are you 100% sure?when i pred them they were working,i tested all of them separately

**Comment by Carbonhell** [comment]
althrough the way to find what relic it is is horrible i have to admit. Why don't ya improve them?ayy

**Comment by ArcLumin** [comment]
I might just do that. Prolly something more along the lines of the experamentor items, as they give unique messages to each one that give away what kind of items they are

**Comment by Pyko1** [comment]
I think they are working, but just badly so closing.
