### ISSUE TITLE
Objects may randomly take up the entire tile, meaning you can't click on anything under it.

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#2764]
I don't know why this happens, but some items will randomly take up the entire tile and not let you select anything under them. Unless there is an object on top of it, you can only select that object even if you click somewhere else. The tile and objects look and act perfectly normal. It has happened to pens, crayons, boxes, wallets, jumpsuits, and medkits, along with a couple other things I forget.

**Comment by ArcLumin** [comment]
I've seen this a number of times, but I just alt clicked the tile it was on and was good. So I never thought much of it

**Comment by Carbonhell** [comment]
I know exactly why this happens and i'll deal with it. It's been too much time,we gotta fix this

**Comment by Carbonhell** [comment]
Uhh. I though the cause was another but i was wrong. By any chance do you know when this exactly happens?

**Comment by TrashFiend** [comment]
Not a clue. The items are always not in their original spots is all the info I can give

-------- Original message --------
