### ISSUE TITLE
Getting cloned changes your DNA for locking

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2770]
Title. If you have a dna locked mech, die and get revived, you'll have different DNA, and you'll be unable to enter your mech

**Comment by GenericGoose** [comment]
how is this a thing

**Comment by TDcoolguy300** [comment]
Because the cloner fucks with your genes randomly when you are cloned. Always take a SE injector of your original corpse if possible.

**Comment by GenericGoose** [comment]
wwhy does it do it

**Comment by TDcoolguy300** [comment]
It's why some people who get cloned get fucked eyes, Tourettes, or Strangeness mutations. Just remember to get your original SE from your corpse if you want to use the mech. It's just how RNGesus works.

**Comment by Pyko1** [comment]
I believe if you update the cloner to max it wont do it.

**Comment by Spacedong** [comment]
well if its a feature then fucking close it why is this here

**Comment by ghost** [comment]
My daily dose.
But intentional anyway.
