### ISSUE TITLE
The crate at  x = 140,  y = 167, z = 1 is a mimic crate.

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#2774]
@calibraptor You fucking idiot.

**Comment by Spacedong** [comment]
nice fucking job retard

**Comment by GenericGoose** [comment]
whats an mimic crate

**Comment by TDcoolguy300** [comment]
The default mimic mob, it's basically a mob with a crate sprite.

**Comment by GenericGoose** [comment]
just looked it up
lol what the fuk

**Comment by ArcLumin** [comment]
It's great, isn't it?

**Comment by calibraptor** [comment]
Hahaha holy shit.

Yeah sure I'll fix this in a sec.

**Comment by ArcLumin** [comment]
I actually like this

**Comment by calibraptor** [comment]
Fixed in #2776
