### ISSUE TITLE
Ice (Chem) Not working

### ISSUE THREAD

**Issue by Jsau7** [HippieStationArchive/HippieStation13-1#2820]
The Ice chemical one can find in Soda Dispensers and Vendors doesn't seem to be working the same as it used to. 
I commonly play chemist and I've been tinkering with finding a good healing combination to get out of bad situations, I've found that enough Ice + Cryox worked wonderfully since the Ice cooled you down for the Cryox to work, But recently it doesn't seem to do that anymore, I'm not exactly sure why though.

**Comment by Kierany9** [comment]
Feature, Cryoxadone's activation temperature was reduced from 270k to 230k.
