### ISSUE TITLE
Suggestion: Give librarian's desk a reinforced table

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2822]
It would make it easier to read ~~porn~~ space epics on, because nobody would be able to access the librarian's public study.

**Comment by Spacedong** [comment]
this area is not used for suggestions, also no.

**Comment by ghost** [comment]
then what the fuck is it used for also where do i suggest things

**Comment by ghost** [comment]
in the forums, in the suggestions section

**Comment by ghost** [comment]
okay how do i tag it with "bad feature" so everybody knows this wooden desk is not cutting it

**Comment by ArcLumin** [comment]
What's stopping people from climbing table or breaking the window? Plus, not hard to break rtables
