### ISSUE TITLE
Code wiki does not have a list of project heads

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2832]
I don't know who to call when something needs input, please fix.

**Comment by Spacedong** [comment]
>should

not an issue, close this

**Comment by danhibiki** [comment]
There really isn't a core organization for coding like that, except that Nalar is the head coder. I guess maybe a list of maintainer could be put there, but I'm pretty sure you can pull that up fairly easy too.

**Comment by ghost** [comment]
@Spacedong 

`downvoted`

@danhibiki If I could I would not  be making this, and I also wish to make a list of such maintainers to make sure everybody is on the same page

**Comment by Pyko1** [comment]
https://github.com/orgs/HippieStationCode/people

**Comment by ghost** [comment]
@Pyko1 Yes this is very good. It would be prudent to add in this information to the wiki, even as just a list.

**Comment by JohnGinnane** [comment]
http://wiki.hippiestation.com/index.php?title=Changelog is usually up to date and has a list of some coders
