### ISSUE TITLE
Bomb wrapped in package explodes as normal, keeps package intact

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2841]
Reproduction:
- Grab a bomb
- Prime it
- Use packaging wrapper on it
- Watch it explode
- Unwrap the package and witness the disappearing bomb

**Comment by ArcLumin** [comment]
This is true for many items, it doesn't qdel the outer shell/container. Package wrapper isn't the only issue, it's just one that isn't commonly blown up by the bomb
