### ISSUE TITLE
You can declare and land at the same time

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2846]
Title. If you're fast you can take the drop pod, have it charging up to go, and right before it leaves, declare. The pod will still drop and you'll have your 200 TC

**Comment by ghost** [comment]
if you want to go tits up you should get to keep your money

**Comment by ArcLumin** [comment]
I've never lost on max rush ops. In fact, I had a 3 minute nuke op round doing that. It's pretty easy to drop directly into the cap's office, snag the disk and the pinpointer, and destroy the pinpointer, kill the captain, and blend in. Or just set off the nuke

**Comment by ghost** [comment]
jesus i didn't know you were playing counter-strike
