### ISSUE TITLE
Syringe gun too weak

### ISSUE THREAD

**Issue by Jsau7** [HippieStationArchive/HippieStation13-1#2851]
Syringe guns only get ONE shot and besides that, Literally anyone who has ANY kind of Shield or ANY kind of hardsuit is auto-Immune to Syringes shot by the syringe gun. What makes it worse is that a majority of traitor/Ling antags always wear hardsuits and carry shields.
Considering Chem is steadily being run to the ground with all these consistent nerfs, It would be nice to atleast buff/balance something from it.

**Comment by TDcoolguy300** [comment]
There exists an upgrade to the Syringe gun that can be made in RnD, holds i believe 4 shots.

**Comment by ArcLumin** [comment]
there's also a rapid syringe gun that can be bought with tc or found in space. A ranged option for appling chems is already op; there are chems that WILL kill in less than 0.5u, and hell, even a syringe of 15u plasma is a quick death

**Comment by ghost** [comment]
Elaborate on the nerfs to chem? I think there's plenty of strong robusting options for chemists.

**Comment by danhibiki** [comment]
Hardsuit and shields block syringes yes, but nothing should be able to answer for any obstacle its presented. There is going to be defenses against anything, and I think making syringes penetrate all armor and having no direct counter mechanics is a bad idea.

**Comment by Pyko1** [comment]
I think its fairly good, to be honest I'm usually more afraid of chemist with syringe gun than some other scrub with tazer or egun.

**Comment by ghost** [comment]
Jesus no.

Chemistry is the second most OP department on the station. A syringe can kill you before you get to ctrl+s.

FUCK giving it a buff.

**Comment by ghost** [comment]
What the fuck no it isn't. Syringes can be one shot kills without even using traitor chems.
"Considering Chem is steadily being run to the ground with all these consistent nerfs, It would be nice to atleast buff/balance something from it."
Chem is literally the reason why stuns stopped being useful.

**Comment by Kierany9** [comment]
I don't think you understand how deadly a competent chemist is.

>Considering Chem is steadily being run to the ground with all these consistent nerfs

There have been no nerfs to the lethality of any toxic chemicals or any stun chemicals that can be applied via syringe.

**Comment by ghost** [comment]
BRING BACK TREKCHEM

**Comment by GenericGoose** [comment]
ITS NOT A WEAPON HOLY SHIT WHY CANT I KILL PEOPLE WITH IT??????????

**Comment by GenericGoose** [comment]
also 1 leporazine syringe or whatever that overpowered plasma chem that kills everyone instantly is enough

**Comment by myontasm** [comment]
What's with all these new names making controversial, gamechanging PRs as of late

**Comment by Kierany9** [comment]
@McBawbaggings 
**NO, I'LL MAKE CHEM GREAT AGAIN ONE STEP AT A TIME!!**

**Comment by GenericGoose** [comment]
solution is simple: git gud
also @Kierany9 stop breaking chem :-1:

**Comment by ghost** [comment]
Trying to make goofchem good is like trying to defib tim buckley's wean.

**Comment by Kierany9** [comment]
what have I broken goose

what?

@McBawbaggings 
### ONE STEP AT A TIME!!

**Comment by GenericGoose** [comment]
your changes succ

**Comment by Kierany9** [comment]
you succ

**Comment by GenericGoose** [comment]
no u

**Comment by trifornt-tinfornt** [comment]
just bring back trekchem

**Comment by ghost** [comment]
@Limed00d it's almost like this is an open platform where anyone can make suggestions

@Jsau7 it's easy to steal a syringe and a gun and a bottle of toxins and morphine, mix them together, and then kill your enemy while he's asleep and taking damage. a traitor chemist can make a plasma smoke bomb and a fire bomb and destroy an entire hallway.

**Comment by KayeArray** [comment]
Nah just git gud and l2 make syringes which crit people in seconds like me.

**Comment by Spacedong** [comment]
literally fucking subjective, close this

**Comment by ArcLumin** [comment]
> just git gud

can only git hub

**Comment by Jsau7** [comment]
Well, I see I must have overreacted thinking it would need a buff then I guess, my bad.
@Limed00d - I've been playing on Hippie for a bit now, But only recently made a account on Git to report some bug I found.

**Comment by GeneralGoose** [comment]
@ArcLumin dude if i could code you robustness i would

**Comment by Spacedong** [comment]
@jsau7 can you close this issue please
