### ISSUE TITLE
Person hiding in locker / box can't be shot by turrets

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#2857]
It's a feature, but it's a bad feature.

**Comment by Spacedong** [comment]
_yeah, just like, remove every wall on the station man, then they can't hide forever_

**Comment by ghost** [comment]
but its not even that

switch to lethal, it kills lockers, switch back to stun them

**Comment by blobbernaut** [comment]
This is not a bad feature

**Comment by Kokojos** [comment]
Totally working as intended.
