### ISSUE TITLE
Invisable Items

### ISSUE THREAD

**Issue by afausnett** [HippieStationArchive/HippieStation13-1#2881]
Skeleton heads are invisible but still clickable

Also, when you relic certain items as chaplain, that said item becomes invisible.

**Comment by ArcLumin** [comment]
Both of these have an issue

Also, skeleton heads (and similar ones, like abductor heads) aren't actually ENTIRELY invisible. Their eyes are still visible. Hard as fuck to see though

**Comment by ArcLumin** [comment]
For heads, https://github.com/HippieStationCode/HippieStation13/issues/2370

For relics, https://github.com/HippieStationCode/HippieStation13/issues/2793

https://github.com/HippieStationCode/HippieStation13/issues/2532

**Comment by afausnett** [comment]
Closing.
