### ISSUE TITLE
The roundstart microwaves in the kitchen don't have a matter bin in them.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStationArchive/HippieStation13-1#2895]
For whatever reason if you deconstruct either of the roundstart microwaves in the kitchen everything you need to make a microwave bar a matter bin will pop out.  This means if it gets deconstructed it cannot be rebuilt without bugging science for stuff.

Any microwaves that are constructed normally however do not suffer this issue. 

I'm not sure if microwaves elsewhere are also affected.

**Comment by ArcLumin** [comment]
I checked the code, it's a one line fix. I'll get to it.

Makes me wonder if this actually has been what's fucking with microwaves

And yes, all roundstart microwaves are affected

**Comment by ArcLumin** [comment]
Just checked, this isn't a new issue

This has existed for the history of hippiestation. THANKS /TG/

Gonna mess with microwave code later and make it more useful than it is now, as well as adding in the matter bin, and making the matter bin actually do something to it.

**Comment by GuyonBroadway** [comment]
Perhaps have each tier of matter bin be able to process multiple items. for example if I put one meat, one salt and one pepper in a microwave I get a steak. if I put three meat, three salt and three pepper i get a burned mess.

If it could make three steaks from this (or 6/9 depending on the level of microlaser) with say, a super matter bin. Then that would make cheffing much more fun.

**Comment by Spacedong** [comment]
@arclumin upgrading microwaves already gives you more meals from making a recipe, for example, using an upgraded microwave and making a recipe for one burger will give you 2-3

**Comment by GuyonBroadway** [comment]
@Spacedong Exactly, so perhaps upgraded matter bins should allow you to do more recipes at once. For example putting in three donk pockets will return three donk pockets worth of warm donk pockets as opposed to a burned mess.

**Comment by ArcLumin** [comment]
@Spacedong You might misunderstand something about upgrading parts

Each part normally increases a SPECIFIC thing. Like power usage, efficiency, etc. In the case before, upgrading the laser will increase the amount produced

As for matterbins, doing more recipes at once like @GuyonBroadway said, while it's a good idea it would take MASSIVE amounts of work to make it work for multiple reasons. Just think; so many recipes use the same stuff but different amounts. It'd be difficult to make multiple of one thing rather than something else. A good idea, but a shitton of work to get it done, prolly needing an overhaul of recipes as a whole

**Comment by GuyonBroadway** [comment]
@ArcLumin That's always the way, I imagine recipes work by checking ingredients vs a list of known recipes, if it matches, return product, else return burnt mess. 

The only way I can see it working is if you find a way to check the ingredients for a recipe, subtract them from the list and then run the check vs the result, repeat for however many times as set by the tech level of the matter bin. 

Another way you could do it is to have the microwaves have several "chambers" that you can add to. and each performs a recipe check much like a second or third "internal" microwave.  

That is assuming matter bins even need to be a requirement, an even easier and far less headache inducing fix is to just remove the matter bins from microwaves in general  because shoehorning a feature into them feels like we're trying to re-invent the wheel, it already does what it should do good enough, there's no need for this extra layer of stuff. Like really I've sat down and though of five or six "ideas" that could be neat but would be retarded in practise. Really the matter bins add nothing of value whatsoever, I'm not even sure what /tg/ was getting at when they added it.

**Comment by ArcLumin** [comment]
I agree. I simply can't think of any thing to really make matter bins affect that would be good in practice. It'd be far simpler to just remove the matter bin req all together

And yes, that is how it works
