### ISSUE TITLE
Leporazine doesn't Provide unprotected EVA

### ISSUE THREAD

**Issue by Jsau7** [HippieStationArchive/HippieStation13-1#2898]
It says it provides unprotected EVA as in letting you survive in space without damage (Except Oxygen) but I still recieve damage in space even after consuming 90u of it.

**Comment by ArcLumin** [comment]
"description = "Leporazine will effectively regulate a patient's body temperature, ensuring it never leaves safe levels.""

where are you reading it will provide completely let you survive in space? You'll still take pressure damage.
