### ISSUE TITLE
Changeling monkey genome farming

### ISSUE THREAD

**Issue by LuisReyesX** [HippieStationArchive/HippieStation13-1#2930]
So basically, you can farm genomes from monkeys using dismembered player heads, since it makes the monkey’s body a player’s body.

This allowed a changeling nerd to get a shitton of genomes using almost zero effort and was really annoying to see as a ghost.

[http://imgur.com/iq354m7](url) Beheaded humanfied monkey bodies plus a head with green hair (from a player).

[http://imgur.com/R5koLHD](url) Changeling puts the player head in the monkey body.

[http://imgur.com/dfglhul](url) Changeling absorbs the monkey body only to behead him again and absorb another monkey.

As you can see this is pretty bullshitty and we can totally blame @Crystalwarrior

**Comment by blobbernaut** [comment]
better than taking 6 people out of the round permanently tbh

also that was me

**Comment by LuisReyesX** [comment]
this is pretty much bypassing the humanized monkeys fix

**Comment by blobbernaut** [comment]
which is glitchy anyway

**Comment by ArcLumin** [comment]
I have already documented and made an issue for this, https://github.com/HippieStationCode/HippieStation13/issues/2772 . This is not directly tied to dismemberment. The game checks if they have an associated ckey in thier mind. So any brain with a player still connected will work.

**Comment by Pyko1** [comment]
the whole human monkeys were not an issue to begin with,  a genetist eating monkeys is a piss easy to caught by decent people, just count the monkeys.

**Comment by ghost** [comment]
Lings eating monkeys is against the flow of a game of an antag that gets insanely power with lots of DNA.

**Comment by ArcLumin** [comment]
geneticists have science access. Just go into xenobio and steal the monkey cube boxes

**Comment by Pyko1** [comment]
easy genome, easy to spot tho, lasering the shit up is solution no matter how many genes.

**Comment by ghost** [comment]
They could just you know, space the bodies from xenobio?
As said, it goes against an antag who is meant to get more powerful after each kill to get easy free farm kills.

**Comment by ArcLumin** [comment]
I typically grab a boxfull of the dna injectors, grab a monkey cube box and a circ saw, take out a brain from like, robotics, then go to the sci outpost, go to a private room and start the succ olympics.

**Comment by ArcLumin** [comment]
bonus points for hiding all the bodies inside a mech or spacing em out the sci outpost airlock

**Comment by Pyko1** [comment]
same as https://github.com/HippieStationCode/HippieStation13/issues/2772
