### ISSUE TITLE
Milk cream gives you cream

### ISSUE THREAD

**Issue by LuisReyesX** [HippieStationArchive/HippieStation13-1#2931]
GAMEBREAKING

**Comment by Spacedong** [comment]
elaborate or close this

**Comment by ArcLumin** [comment]
he means milk cream is actually the chem cream.

not an issue

next there will be an issue where soda machines give lemon lime instead of orange

**Comment by Kokojos** [comment]
STOP THE PRESSES

**Comment by doobiedoo23** [comment]
I wanted milk-cream. It gave me cream.

**Comment by ArcLumin** [comment]
Not an issue, please close
