### ISSUE TITLE
Create nations wizard event create antags with no objective.

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#294]
Need to add objectives?

**Comment by Jaygriff** [comment]
they are separatists. I think their objective is just to do as much damage as possible

**Comment by TDcoolguy300** [comment]
More than likely a TG oversight, still has the same effect as summon guns, just without the guns.

**Comment by WhiteFox08** [comment]
Yea its supposed to be departmental uprising but it is worded kinda wierd.
