### ISSUE TITLE
Admin pm sometimes do not show up

### ISSUE THREAD

**Issue by lcass** [HippieStationArchive/HippieStation13-1#295]
On the admin side of the ahelp when sent sometimes it does not show up for the admin. 
http://i.gyazo.com/8caf131776eebe319461b540f90d6e06.png

**Comment by nalarmg** [comment]
Seems to be a BYOND issue. This sometimes happens with things unrelated to PMs entirely, such as IC say messages, emotes, and even OOC messages. Unable to replicate locally.

**Comment by Jaygriff** [comment]
its not even at byonds level. Its packet loss due to congestion (assumed). All communication works perfectly at the beginning but as more and more stuff happens to create more networking traffic, rates skyrocket. Networking issues mang... Cant do anything about it.

**Comment by nalarmg** [comment]
Networking is primarily handled by BYOND, so it's a BYOND level issue.
