### ISSUE TITLE
Lethal Syringes are refillable

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2974]
You can refill a lethal syringe with 50u of any reagent. And it injects it all in one go. And it's op as fuck.

**Comment by KayeArray** [comment]
The station only starts with a few right?

**Comment by ArcLumin** [comment]
5 on station, more can be found in space

**Comment by blobbernaut** [comment]
Not a bug?

**Comment by ArcLumin** [comment]
Was under the impression that they weren't designed to be reused, but I guess that's more of a interpretation of the original coder's idea. It's at least a balancing issue. I think it's at least an oversight.

**Comment by JohnGinnane** [comment]
Not a bug, and there's only 5 at round-start

https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/modules/reagents/reagent_containers/syringes.dm#L243
