### ISSUE TITLE
Chem temperature significantly buffs/nerfs pyrotechnics

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2978]
Heating chems that are supposed to cause fires SIGNIFICANTLY increases the fire stacks when used in smoke. The opposite is true when it's cooled.

Not 100% sure if it's a bug but not entirely sure. It's certainly something to keep in mind if you're testing CLF3 with admin commands or something, since admin commands spawn it at 300K temp rather than the 1000K temp it's naturally made with.

**Comment by Pyko1** [comment]
I think its an intended feature so closing this.
