### ISSUE TITLE
You can reach centcom using bloodcrawl

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2979]
Use bloodcrawl while on a shuttle in transit. Make sure you have an RPD and tools. Go south to the wizard ship and get out of the blood on the wizard ship. Use the RPD to build piping allowing you to escape the wizship from the east. Use piping to break into centcom, the syndie ship, wherever.

**Comment by KayeArray** [comment]
Isn't this more fucking disposal pipe memes?

**Comment by ArcLumin** [comment]
Yup. But bloodcrawl + pipe memes

**Comment by Pyko1** [comment]
Maybe put moving space in its own level, and add checks to spells and RPD and whatever so that they wont work on z2.

**Comment by ArcLumin** [comment]
but I love my centcom traveling bugs

**Comment by Pyko1** [comment]
or just surround the moving space with instant gib area or something.

**Comment by ArcLumin** [comment]
That sounds like a challenge

Thinking of all the broken bugs I can make by abusing areas that instagib
