### ISSUE TITLE
Slings in a Mech take no light damage

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#2993]
Title. Slings being in a mech means they take no damage. They don't heal either, but hey. Really robust if done right.

**Comment by GuyonBroadway** [comment]
Can they convert or use powers? if not it seems like a valid tradeoff to me.

**Comment by ArcLumin** [comment]
They can't while in a mech. However, easily able to pop out and quickly do it, then pop right back in. More of an oversight than anything, it's a pretty viable setup.

**Comment by GuyonBroadway** [comment]
Not sure it's even an oversight, one could argue any shadowling would dim the mechs cockpit lights before entry. Perhaps a coincidence at worst but I don't think it was so much unintentional so as to be so minor as to not even be worth considering. 

Now to roll Shadowling shaft miner and go on a mad mech rampage like I always wanted.

**Comment by ArcLumin** [comment]
I've done shadowling shaft miner, it's great. Mechs are the shadowling's worst enemy (blocks off hallways, unremovable light source) and their best friend (stealthily immune to light)

**Comment by Spacedong** [comment]
yeah I assume lore-wise he'd just darken the cockpit's interior lights or smash them tbh, close it, non-issue @arclumin
