### ISSUE TITLE
Locker Attackby() Proc

### ISSUE THREAD

**Issue by trevorKirkby** [HippieStationArchive/HippieStation13-1#2997]
This is pretty minor, but I figure I should mention to you that lockers aren't correctly handling welders in their attackby() proc.

When you try to place an unlit welder inside of an open locker, I would imagine the intended result should be that the welder is placed into the locker. Instead it does not do anything...

I would speculate that it probably just needs a "..()" instead of a "return" somewhere.

**Comment by ArcLumin** [comment]
Can confirm

**Comment by ArcLumin** [comment]
Fixed in https://github.com/HippieStationCode/HippieStation13/pull/3007
