### ISSUE TITLE
You seem to be unable to wear shoes if you lose an arm

### ISSUE THREAD

**Issue by TrashFiend** [HippieStationArchive/HippieStation13-1#3001]
Got a mentorhelp from a CMO who lost his arm from an explosion. Suddenly he isn't able to put on shoes without them falling off. Multiple pairs of shoes did this and I saw it when I tracked him.

I'm guessing there was a check to see if he was missing ANY limbs, rather than just legs. Never saw this happen before.

**Comment by ghost** [comment]
Old issue, still hasn't been fixed. Honestly, I don't mind it since it keeps people from lopping their arms off to avoid being cuffed.

**Comment by ArcLumin** [comment]
Old issue, already has an issue up for it;

https://github.com/HippieStationCode/HippieStation13/issues/2662
