### ISSUE TITLE
Xeno Surgery

### ISSUE THREAD

**Issue by kaptem** [HippieStationArchive/HippieStation13-1#3009]
Xeno Surgery does not work at all, when trying to put surgical drapes on a xeno it does not work, nor does hitting them with surgical tools, you cannot preform any kind of surgery on them.

**Comment by ArcLumin** [comment]
double check that its a human xeno and not a simple mob xeno

I'll run some tests on human xenos to be sure

**Comment by LuisReyesX** [comment]
I think it might be because recent features, since like 5 months ago the surgery worked in every alien but queen

**Comment by Pyko1** [comment]
same as https://github.com/HippieStationCode/HippieStation13/issues/2669 also tells the cause.
