### ISSUE TITLE
The new cooking system seems VERY bugged.

### ISSUE THREAD

**Issue by Axolotl123** [HippieStationArchive/HippieStation13-1#3017]
I usually play Chef on Hippie and the whole new cooking system has thrown me off and into a pit of eternal damnation. Basically I can't cook anymore. I tried the new recipe for meatbread, putting 15 flour, 3 meat, and 3 cheese wedges into the microwave and it comes out as a burnt mess. I've tried other recipes and they all come out as burnt messes except grilled cheese.

**Comment by ArcLumin** [comment]
Yeah, spacedong fucked up cooking when he tried to do a different cooking system. I don't think anyone has bothered fixing it since "It'll be fixed in the rebase!", but we'll see.

**Comment by ghost** [comment]
My fault to some degree as well, although you're not mixing different types of meat together (monkey, human, other species) right? That's always been an issue on this system.

**Comment by Axolotl123** [comment]
I didn't mix any different types of meat, all the same "Meat" from the chef locker.

**Comment by ghost** [comment]
It's because the meat in the fridge is meat/monkey and some the recipes use meat/human
It's an easy fix.

**Comment by ghost** [comment]
Doing a fix right now, lemme know about other recipes.

**Comment by Axolotl123** [comment]
I'm pretty sure most recipes involving meat seemed to be bugged.

**Comment by ghost** [comment]
Fixed meatbread and meat pizza, I'll do a sweep to find any others.

**Comment by ArcLumin** [comment]
Prolly comes from the fact that it was a port from atlas' cooking

**Comment by ghost** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/3018 contains a fix to the meatloaf in particular. I tidied up the meat recipes, although it doesn't appear to be meat that is breaking them except for meatloafs.

**Comment by ghost** [comment]
Keep this open for a while to make sure we haven't missed anything.
