### ISSUE TITLE
You can't pick up items if you have no legs

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#3027]
Title. Having no legs puts you in a crawl mode, making you unable to hold any items

**Comment by ghost** [comment]
Kinda intentional since of how crit works?

**Comment by ArcLumin** [comment]
Well, not so much for dismemberment. Basically it makes you identical to crit movement, which is fine, but even when you're not moving you can't pick up items, which doesn't make any sense.

**Comment by JohnGinnane** [comment]
Closing as lying on the ground (either willing or not) means you cannot hold items in your hand is intentional
