### ISSUE TITLE
''Duplicate'' error in compiling.

### ISSUE THREAD

**Issue by ChosenIsHere** [HippieStationArchive/HippieStation13-1#3030]
Everytime i try to compile it i get this error: code\modules\admin\verbs\fps.dm:2:error: fps: duplicate definition (conflicts with built-in proc)

**Comment by TDcoolguy300** [comment]
Switch to the STABLE build of BYOND, they made FPS a BYOND proc in the beta builds.

**Comment by ChosenIsHere** [comment]
I will try it, thanks.

**Comment by TDcoolguy300** [comment]
Assuming this worked, closing.
