### ISSUE TITLE
Green Bear doesn't have any Booze Power/Missing Line

### ISSUE THREAD

**Issue by Rom546346** [HippieStationArchive/HippieStation13-1#3047]
https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/modules/reagents/Chemistry-Reagents/Consumable-Reagents/Drink-Reagents/Alcohols.dm

Line 72 requires: boozepwr = 55

**Comment by ArcLumin** [comment]
Uh, no. That's not how the code works. It's a child of beer, so it inherits all properties of beer it doesn't manually change. Beer has a boozepwr of 55 already. This is not an issue

**Comment by Rom546346** [comment]
My bad.
