### ISSUE TITLE
DISPOSALS IS BROKEN

### ISSUE THREAD

**Issue by Rom546346** [HippieStationArchive/HippieStation13-1#3058]
Problem Description: Recently tried to mess around with disposals and found out it's completely broken. 

What did you expect to happen: Working pipes.

What happened instead: "Old pipes" (preconsructed by map) cannot be deconstructed. New pipes can be constructed, but are bugged on spawning. Instead of being spawned with the correct name (i.e a junction pipe having the name junction pipe) it just says "disposals pipe." This is true for the one pipe that connects bins and chutes as well, making wrenching them impossible, since the under pipe is misidentified even though the sprite is correct. New pipes also don't connect to each other like old pipes.

Why is this bad/What are the consequences: No more fun gimmicks with chutes.

Steps to reproduce the problem: 1). Take RPD 2). Switch to disposals 3). Try to make anything

Server: Hippie 13

Revision: Current

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Send help.

**Comment by ArcLumin** [comment]
This was prolly closed because he didn't realize he had to wrench then weld

**Comment by Rom546346** [comment]
I was a fool.

**Comment by ArcLumin** [comment]
At least you know

And knowing is half the battle
