### ISSUE TITLE
You can rename the clown planet coords with hrefs

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#3075]
![oh shit](https://puu.sh/sBteb.png)

**Comment by JohnGinnane** [comment]
How did you do that?

**Comment by ArcLumin** [comment]
right click, rename. It's not sanitized either AAAAAAA

**Comment by ArcLumin** [comment]
![memes](https://puu.sh/sBw05.png)

pretty fun tbh

**Comment by Spacedong** [comment]
jesus mother of fuck

**Comment by Spacedong** [comment]
how could you let this happen
