### ISSUE TITLE
ak 922 mags  in russian station is broken

### ISSUE THREAD

**Issue by shlomogoldberg** [HippieStationArchive/HippieStation13-1#311]
the mags cant be refilled with the ammo boxes or bullets

**Comment by shlomogoldberg** [comment]
pls fix

**Comment by Jaygriff** [comment]
Is it just the mags on that station or the mags everywhere?

**Comment by shlomogoldberg** [comment]
everywhere

**Comment by shlomogoldberg** [comment]
i mean the mags from that station dont work everywhere

**Comment by Jaygriff** [comment]
Confirmed. You cannot reload bullets into the mag via either of the methods (box and by hand one at a time)

**Comment by Weisyl** [comment]
I'll look into this.

**Comment by Weisyl** [comment]
Welp I've wasted a few hours trying to solve this and I've not been able to figure out the issue.

**Comment by Carbonhell** [comment]
Fixed in #633
