### ISSUE TITLE
Administration - Mass modifying screams breaks screaming

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStationArchive/HippieStation13-1#3120]
When screaming sound effects are mass modified with a file, screams are **disabled** and **cannot be fixed** to their default state. Don't really understand why it does it.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Why do people keep trying this.

It is caused because the variable is a list() and mass editing does not allow you to add to said list, instead overriding it and by doing so, breaking it.
