### ISSUE TITLE
SS13 Hippie Station 13 "Loading..." Bug

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#3127]
#So, I got this issue where the cryos, chem dispensers etc HUDs doesnt work for me...

They just keep like this:

http://prntscr.com/dm7i0q

Please, Help

**Comment by ghost** [comment]
Update internet explorer I think

**Comment by ghost** [comment]
I think it is already updated

**Comment by Pyko1** [comment]
You are using stable version of byond as well?

**Comment by ghost** [comment]
I resarted it many times , I reinstalled byond many times, already tried to update the internet explorer, the problem just keeps in

**Comment by ArcLumin** [comment]
I've had this issue. Alter your IE privacy and safety settings. NanoUI fucks up if you set it too high.

**Comment by ghost** [comment]
ArcLumin,I just tried that , the problem stills :(

**Comment by Pyko1** [comment]
Most likely caused by some IE settings or possibly addons that block some byound features.

Codewise we cant really do anything, but you could try disabling IE addons and changing security settings.

**Comment by ghost** [comment]
I reseted the IE settings and IT WORKED!! Thanks you all!!

**Comment by TDcoolguy300** [comment]
I suppose we can close this now
