### ISSUE TITLE
Chaplain and Mime aren't in Job Preferences

### ISSUE THREAD

**Issue by TheOneAndOnlyCreeperJoe** [HippieStationArchive/HippieStation13-1#3142]
Priority reeeee
![image](https://cloud.githubusercontent.com/assets/17836851/21468176/a70d0b8c-ca06-11e6-99e8-8688a1a0bdd3.png)

**Comment by ghost** [comment]
FUCK

**Comment by ghost** [comment]
NO MIME EITHER

**Comment by TheOneAndOnlyCreeperJoe** [comment]
FUCK EVERYBODY PANIC

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Nevermind they're back?

**Comment by ghost** [comment]
Okay, weird.

**Comment by yobob591** [comment]
HOLY SHIT WHAT

**Comment by yobob591** [comment]
nevermind?
