### ISSUE TITLE
Engineers can't unlock air alarms to fix air in rooms

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStationArchive/HippieStation13-1#3190]
Right now you need atmos access but if an engineer is repairing a large hull breach and needs access to the air alarm to refill the room with air he can't unlock it. Can we give them access to the air alarm?

This might make atmos as a role even more irrelevant but even just this one item would be engineering OR atmos access. Thoughts?

**Comment by ArcLumin** [comment]
It's been around for forever, but it's not as big of a deal, as, say, engineers not getting APC access. You can hack both the air alarm and the atmos alarms, but fixing APC's is far more common for engies

**Comment by ghost** [comment]
Just hack the air alarm? You just need a multitool.

**Comment by JohnGinnane** [comment]
Oh shit, I didn't even realise you could hack it. Cool!

**Comment by JohnGinnane** [comment]
Thank you

**Comment by ArcLumin** [comment]
Protip; wire a signaller to the fire alarms and scrubbers of everything on the station set to voice command. Block sec at every path!

**Comment by JohnGinnane** [comment]
Interesting...
