### ISSUE TITLE
Changelings can absorb monkey humans again

### ISSUE THREAD

**Issue by TheOneAndOnlyCreeperJoe** [HippieStationArchive/HippieStation13-1#3204]
Yay we get to thank dismemberment for this.

How to reproduce it:
-Get a monkey, turn it human, remove it's head.
-Get a player controlled human's head and absorb the body of the monkey now turned human
-Cut off the player controlled-head again, reattach it to another monkey turned human, rinse and repeat.

**Comment by Vievioora** [comment]
Creeper, how can you get it wrong after I explain it twice.
You absorb a human, remove his head/brain, attach it to a humanized monkey, then you absorb the humanized monkey with head/brain of a real human. Then you remove the real human bean head/brain and move it to another humanized monkey and so on and on

**Comment by TheOneAndOnlyCreeperJoe** [comment]
what this dude said, I'm not a morning person.

**Comment by Pyko1** [comment]
same as https://github.com/HippieStationCode/HippieStation13/issues/2772 and https://github.com/HippieStationCode/HippieStation13/issues/2930
