### ISSUE TITLE
Stand Arrow doesn't husk people

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#3208]
standu spamu
Just get a guy with a defib to revive you over and over and you can keep using the stand arrow until you get a stand.
fix dis

**Comment by oprayx77** [comment]
fuk off this is brilliant reeee but yeah its not working as intented i think

**Comment by Spacedong** [comment]
or just make it do enough damage to not be able to defib????? like anything over 200 damage guarantees you won't be defibbed.

**Comment by yobob591** [comment]
it does 1000000000 toxin it shouldnt let you defib

**Comment by Spacedong** [comment]
defib bypasses toxin, it only cares about burn and brute yuo FUCK

**Comment by yobob591** [comment]
ill make it husko

**Comment by KayeArray** [comment]
why the fuck does it do a shit ton of toxin damage instead of just calling death() anyway what the fuck.

**Comment by gumner** [comment]
@banthebantz because of the reasons stated above you fuck,you not supposed to keep being defibilled

**Comment by Pyko1** [comment]
should be fixed
