### ISSUE TITLE
If you're deaf ICly, you're deaf in dsay/deathchat too,as an admin

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#322]
Pratically,if you become deaf in game due to a bomb or genetics, you cannot hear deathchat nor read what you write in it with dsay. Weird.

**Comment by TDcoolguy300** [comment]
This could be the fact that the Say verb uses both Deadchat and normal live chat, so when deafness is applied, it ignores shit from that verb or something, i have not looked at the code yet

**Comment by lcass** [comment]
This one will be a bitch to fix , this is some core code which aint gonna be fun.
