### ISSUE TITLE
"Set Pressure" does nothing for Supply Control computer in Atmos

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStationArchive/HippieStation13-1#3222]
![image](https://cloud.githubusercontent.com/assets/3355198/21577891/b0b0303a-cf63-11e6-864b-a0710c3c5354.png)

I wonder if runtimes are being thrown up

**Comment by ghost** [comment]
It does, the computers suffer the same issue as microwaves in which they update then run code. If you back out and click on the computer again, it will show the changes.
