### ISSUE TITLE
Flask of holy water gets bigger when you break it

### ISSUE THREAD

**Issue by ArcLumin** [HippieStationArchive/HippieStation13-1#3229]
You can normally put the flask of holy water in your pockets or bible, when it breaks, it gets bigger, and you can't

**Comment by ghost** [comment]
It gets bigger when I pull on it.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/15840795/21579546/f0ddd554-cfae-11e6-8fd0-666e4c8b56f6.png)

**Comment by Spacedong** [comment]
Not a bug, this is the same with all bottles that are broken. You wouldn't realistically put a giant spiky bottle in your pocket anyway. Close this bawg.
