### ISSUE TITLE
Stand arrow should check for candidates first instead of killing

### ISSUE THREAD

**Issue by Cameron-The-Raven** [HippieStationArchive/HippieStation13-1#3239]
Currently, the stand arrow doesn't  check for candidates first, instead rolling the death chance, then candidates, then returns the "Try again later" if there is none and you got lucky with the 40% chance

If you then try again later, the same thing can happen or it can just flat out kill you before checking for candidates again.

It should check for candidates first, then roll the kill % chance

Ex:
Use strand arrow, death roll passes, it checks for candidates then tells you to try again.

Try again, instantly die because death roll failed this time around and you had to do it again instead of straight up telling you "Nobody wants to be a stand, try again later" the first time around.

**Comment by Spacedong** [comment]
lmao what whyy does this exist

**Comment by Cameron-The-Raven** [comment]
nevermind there's already a PR up to do exactly this
