### ISSUE TITLE
You can't weld disposal pipes in place

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#329]
You can unweld them but when you attempt to reweld them into place it just gives you the message that you've started and never finishes.

Tested by Hutchens, me, and NoscopeToolbox.

**Comment by Tomeno** [comment]
Alright I fixed this now I just need to beat up Github into submission so it lets me make a branch and commit it to it

**Comment by Kokojos** [comment]
Close because fixed.
