### ISSUE TITLE
Ka-Nada Boxed S.S.F Hockey Set Bugs: Set Horribly Crippled

### ISSUE THREAD

**Issue by WallaceShark** [HippieStationArchive/HippieStation13-1#3301]
Costs 20 TC to buy. Two bugs of note that critically hinder its usefulness.

>The suit is advertised as being environment-proof. It can survive the vacuum of space, but not the freezing cold of space. You wont die of pressure but WILL die of temperature. And since you can't take it off, no space acess ever.

>The mask cannot be removed, meaning you can never eat after putting the mask on. And once hunger sets in, the hockey skate's speed boost won't take effect. You become critically slowed and easy to outrun and kill.

**Comment by GuyonBroadway** [comment]
Yeah I noticed the lack of spaceworthiness and food-eating-ness last night, was going to get a fix up but it was 3am and I was drunk and in a rare case of being fucking sensible I decided bed first was probably a better idea.
