### ISSUE TITLE
Atmospherics Maint by sec is no longer connected to the loop

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#331]
http://i.imgur.com/QPnax1s.png should have a connector port down near it, for some reason it doesnt.

Compare it to the viro one: http://i.imgur.com/nbBxYch.png

**Comment by Nokington** [comment]
That wasn't me. I swear.

**Comment by Nokington** [comment]
I don't wanna fuck it up so i'm gonna let @Kokojos do it.

**Comment by Chronitonity** [comment]
Alright, whatever you say

**Comment by Jaygriff** [comment]
This has been issue since before the split.. Just now being actually noticed. Really you could route it from the other side and use the n2 closet
