### ISSUE TITLE
c4 bug?

### ISSUE THREAD

**Issue by Anderbergst** [HippieStationArchive/HippieStation13-1#3320]
So something weird just happened, so first i bought 2 c4s and then, I planted a c4 on the gravity engine rwall then backed out, i looked at it and waited for it to blow up, but then it exploded on me instead of exploding at the rwall that i planted it to. Is it because i bought 2 c4s at the same time or something? weird.

**Comment by ArcLumin** [comment]
We already have an issue for this, https://github.com/HippieStationCode/HippieStation13/issues/2885
