### ISSUE TITLE
Thermals and xray vs lockers and disposal bins

### ISSUE THREAD

**Issue by JohnMcLaime** [HippieStationArchive/HippieStation13-1#3375]
Make so if you have thermal vision or xray vision, examining a locker/disposal bin or some other container where humans can hide would produce a message that there is someone, just a message at least. Maybe make a delay/progress bar for this.
Since anti stuns were removed, people can hide in lockers for days fishing for antag, while disposal bins have a light on it if they are occupied, not so much for lockers.

**Comment by PopNotes** [comment]
lockers have anti-x-ray polymer shells, it's deepest lore

**Comment by JohnMcLaime** [comment]
Fuck lore, a lazy excuse to prevent muh impulsions from being ruined.

**Comment by PopNotes** [comment]
what is humor

**Comment by JohnMcLaime** [comment]
How the fuck would i know over the internet.

**Comment by PopNotes** [comment]
> deepest lore

**Comment by gumner** [comment]
what the fuck dude,if you can see people inside lockers,you're essentially not only a killing machine but a killing machine that tracks people,thermal is ok the way it is rn,dont change it

**Comment by Kierany9** [comment]
Let's address the real issue here

Thermals work in plasma fires

**Comment by ArcLumin** [comment]
Let's not because these aren't issues. We handle coding issues here, like "The experimentor spawns a coffee machine instead of coffee" not "add this I want my immershuns please". If you want to post what we "Should add" do it on the forums.
