### ISSUE TITLE
missing pipe where the cargo bay's clock is

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#3382]
**Problem Description**: One of the pipes on the Delivery chute in Disposals is missing, where the clock in Cargo Bay is

**What did you expect to happen**: I expected there to be a pipe, not a clock

**What happened instead**: I got spat out where the clock is because a pipe is missing

**Why is this bad/What are the consequences**: It's not so much bad but just an inconvenience to go down the chute expecting to go to delivery only to be stopped by a lack of piping instead. It does some minor brute damage too I think which I guess is bad but it's so minor you'd probably have to be in crit for it to matter.

**Steps to reproduce the problem**: Go to Disposals, put something (or yourself) into the Delivery chute, and then watch as it stops you right where the clock is

**Server**: Hippie Station 13

**Revision**: the 2017-01-18 one

**Comment by JohnMcLaime** [comment]
Needs a clock isssue tag.

**Comment by Spacedong** [comment]
clocks were reverted, close this

**Comment by ghost** [comment]
clocks haven't been reverted yet as far as I can tell

I performed the same steps and again found myself at am impasse with the formidable clock

ed: unless you mean reverted in the code and not pushed to the server yet, in which case excuse me i'm probably retarded

**Comment by ArcLumin** [comment]
Nobody has done the server !update, that's why

**Comment by ArcLumin** [comment]
Should be gone now though
