### ISSUE TITLE
the saxophone does the thing sound effects do of changing pitch despite playing music

### ISSUE THREAD

**Issue by cacogen** [HippieStationArchive/HippieStation13-1#3398]
if you haven't noticed, sound effects pick a random pitch when they play so that when the same sound effect repeats each one sounds unique

but this extends to the saxophone which plays saxophone clips from pop songs and this results in the songs played being randomly sped up or slowed down

would be better if by default they played at regular speed and there was an option to play them back at a different tempo if you wanted

**Comment by yobob591** [comment]
It does this on goon too

**Comment by ArcLumin** [comment]
This is fine, it's a feature

**Comment by cacogen** [comment]
is it a feature? i think it's an unintended side effect of the way the playsound() proc works

i can understand if you don't think it's worth doing anything about, but at least say that

**edit:**
actually i think it's just from copy and pasting the playsound proc (most of the time it's used with the volume at 50 and pitch varying on), you'd just have to set the vary value to 0 [here](https://github.com/HippieStationCode/HippieStation13/blob/c0f40c5b47c053f967b121eeb946025623ffe854/code/game/objects/items/weapons/clown_items.dm#L147) as per [the proc definition](https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/game/sound.dm#L1)

**Comment by ArcLumin** [comment]
I dunno if it's a feature or not, but it certainly makes stuff more fun, as it's not the same sound effect every time, it feels less spammy.

**Comment by cacogen** [comment]
i don't care enough
