### ISSUE TITLE
Can't observe the SM

### ISSUE THREAD

**Issue by Nokington** [HippieStationArchive/HippieStation13-1#341]
It would be nice if in the observe button there was a way to find the SM. Right now I can observe the singulo and nuke disk but not the SM. For example of when this would be needed. Someone ejected the SM and said it was about to blow, being able to find the SM and VVing it would be nice to know if it was about to blow.

**Comment by TDcoolguy300** [comment]
Workin on it

**Comment by Nokington** [comment]
yay its done and merged
