### ISSUE TITLE
Medical Cyborg Beaker

### ISSUE THREAD

**Issue by Podgehodge** [HippieStationArchive/HippieStation13-1#350]
I believe this is related to issue #136. 

Basically, the medical cyborg's beaker is a buggy mess and can cause problems for players other than the medical cyborg. 

As I understand it, when the cyborg beaker is ejected from a machine, it exist as an instance on the map. Herein lies the problem because other players can interact with it. Thus, issue #136 where the cyborg's beaker glues itself to a player's hand and becomes irremovable.

A few interesting things I've noticed: After a player has picked up the cyborg's beaker, the cyborg's  module slot which held the beaker becomes empty, but can still be selected. If the cyborg then stores the "empty" module, the player's hand which was holding the beaker becomes empty and the beaker returns to the cyborg's module storage. However, the game still recognizes that the player is holding the beaker. It's as if the human's hand is replaced by the cyborg's beaker module and they're sharing it between them.

A few related issues:
1.) The medical cyborg's beaker can't be inserted into chemical dispensers. Maybe this is intentional, but I would think this would be the beaker's primary purpose.
3.) While the beaker is inserted into a machine, the borg can store the module, re-select it, and insert it into additional machines. The beaker is then shared between those multiple machines simultaneously. 
2.) The beaker module sometimes ceases to function (I.e. its icon becomes non-selectable in the borg module storage) for reasons I can't discern. I've tried a bunch of different stuff to recreate this (like moving to different z-levels) and, as near as I can tell, the beaker module just stops functioning when it feels like it. It's a mystery.

To be frank, instead of fixing this turd, it may just be easier to replace it with something simpler like a beaker that synthesizes chems without the need to insert it anywhere. Just my $0.02. 
Anyhow, hope this helps.

**Comment by Jaygriff** [comment]
Nice catch @Podgehodge. Excuse my ignorance but where can you use the cyborg beaker at anyway?

**Comment by Podgehodge** [comment]
The cyborg beaker works with the chem master, the booze & soda dispensers, cryo tubes, the virology pandemic thingamajig, and possibly other things. Really, as far as I can tell, the only thing it _doesn't_ work on as opposed to a normal beaker is the chem dispenser.
