### ISSUE TITLE
Centcomm is not up to code

### ISSUE THREAD

**Issue by Nebyab** [HippieStationArchive/HippieStation13-1#351]
There's a hole in the floor between the magic mirror chamber and the security dock in Centcomm.

http://i.imgur.com/ZxQEl4c.png

pls fix

**Comment by Nokington** [comment]
this is so minor that it will probably never be fixed.

**Comment by Nokington** [comment]
Or @Kokojos could just be a cuck and fix it quickly.

**Comment by Kokojos** [comment]
Centcom needs some love.

**Comment by Weisyl** [comment]
I can fix this in a bit with a polishing update.

**Comment by Nokington** [comment]
It was already fixed in koko's PR

**Comment by Weisyl** [comment]
This should be closed then.

**Comment by Nokington** [comment]
It hasnt been merged, thats why it isnt closed

**Comment by Kokojos** [comment]
And the new commit fucked it up. Il have to do it later.
