### ISSUE TITLE
Testing Lab Mapping Issues

### ISSUE THREAD

**Issue by Podgehodge** [HippieStationArchive/HippieStation13-1#352]
Two issues with the science testing lab.
First image is pretty self-explanatory:
![Testing Lab Disposals](http://i.imgur.com/Nq6DG5w.png)
When you fix this, be mindful that the closest disposal pipes go to space rather than cargo.

Second problem involves the atmos piping for the heater/cooler in the upper right part of the testing lab. Apparently, there's a manual valve that's disguised itself as a normal pipe. If you mouse over it, it even says it's a manual valve, and I believe it even behaves like a manual valve. But until you unwrench it, it just appears to be a regular pipe. Kinda confusing.

![Testing Lab Cooler/Heater](http://i.imgur.com/DZOoynk.png)

**Comment by WhiteFox08** [comment]
I'll see what I can do, thanks @Podgehodge

**Comment by Nokington** [comment]
Ayy for once it wasn't my fault.

**Comment by Kokojos** [comment]
Can't believe we never spotted that before!

**Comment by WhiteFox08** [comment]
Fixed in #355
