### ISSUE TITLE
mapping issues

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#356]
all arcade machines, shuttle console on syndie ship in asteroid belt z level.
cant be moved/deconned

**Comment by Kokojos** [comment]
Tested, can't reproduce.
First of all there's no arcade on the asteroid belt z-level
And I was able to deconstruct all the things in the z-level, but not move them because there's no gravity.

Gonna close unless you have specifications.

**Comment by ghost** [comment]
i'm talking about the solar controller console on the asteroid belt station, if you screwdriver it you get no message and it then dissapears if you wrench it
