### ISSUE TITLE
Atmos supply control computers

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#358]
The Atmos Supply control has two Nitrous Oxide computers. The one in the middle is supposed to be a Toxins computer. Not a recent bug.

**Comment by Chronitonity** [comment]
Confirmed, I showed this to Kokojo yesterday(?).

**Comment by Kokojos** [comment]
Done in https://github.com/HippieStationCode/HippieStation13/pull/368
