### ISSUE TITLE
Mass drivering something puts it on the other side of the station

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#359]
Dunno if random z levels in space are enabled, but if you mass driver something it lands near arrivals. 

This is kind of a huge issue seeing how you mass driver things out of the chapel you expect them to be somewhere in deep space, not on the other side of the station.

**Comment by Nokington** [comment]
Pretty sure you just have bad luck.

**Comment by Kokojos** [comment]
Bad luck, approx 1/4 chance

**Comment by Chronitonity** [comment]
Happened 100% of the time I tested it. Tested it multiple times in multiple rounds with @TDcoolguy300

**Comment by Chronitonity** [comment]
Also tested with Nalar, happens literally 100% of the time. If you try and go back to the mass driver and push off to the left of the station, you always end up on the asteroid.

**Comment by nalarmg** [comment]
Yep, tested and confirmed. This is a consistent thing. Legitimate issue.

**Comment by Kokojos** [comment]
Ah, I think I know why. It's when I changed the size of the z-levels - I moved some things around. I think it's z-level 3 that needs something to stop the mass-driver from looping around.

**Comment by Kokojos** [comment]
Actually I tested it again today and your 100% chance dosen't match with my result. Still, il ''nerf'' the rate of returns.
