### ISSUE TITLE
Atmos Piping Disappearing

### ISSUE THREAD

**Issue by Podgehodge** [HippieStationArchive/HippieStation13-1#362]
Un-wrench a pipe? Fine.
Wrench it down again? Fine.
Un-wrench it again? Fine.
Wrench it down a second time? **POOF!** GONE.

I thought this might be a layering problem, but I pulled up the tile and deconstructed the floor and the pipe is completely gone. Also, gas doesn't flow through the vanished pipe, so there's no phantom invisible pipe existing behind the scenes. Atmos pipes just self-delete after they've been wrenched down a second time. This issue extends to all types of pipes, valves, pumps, scrubbers, vents, basically anything that attaches to atmos piping. The only exception being the gas meter.

Several other issues that might be related:
1.) The sprite for wrenched-down bent pipes incorrectly displays as a horizontal straight pipe if it's not connected to anything.
2.) Connected pipes sometimes have a gap between them. This gap isn't just graphical, it also prevents gas flow and is extremely annoying. I'm not sure what causes this.
![1](http://i.imgur.com/IrZ6PSP.png)
3.) Some pipe sprites display incorrectly if they're wrenched down on plating rather than the floor. I've seen volume pumps sink into the plating, the port for connectors disappearing, and other strangeness. 
![2](http://i.imgur.com/Qa0sRD6.png)
4.) Four-way manifolds immediately self-delete when wrenched down, making them useless. Even worse, digital valves turn into invisible phantom pipes when wrenched down and prevents other pipes from occupying the same tile. If the tile is examined, the invisible digital valve is actually something called "the machinery". 

Anyway, the more I mess with this stuff, the more problems I find, so I'm calling it quits here.
:poop::thumbsup: Good luck fixing this heap.

**Comment by Jaygriff** [comment]
@kokojos probably going to just port the entirety of tgstation atmos sometime this week. This will resolve a ton of issues

**Comment by SplergeBucket** [comment]
This needs to be fixed, there hasn't been one delivered yet.

**Comment by WhiteFox08** [comment]
Last I've heard @Crystalwarrior  was going to take on this.

**Comment by Crystalwarrior** [comment]
what the hell? I've no idea how to fix this. Atmos is probably the least explored aspect of SS13 for me.

**Comment by Jaygriff** [comment]
Im the one working on it. Need to freeze map changes while i put it together though.

**Comment by nalarmg** [comment]
Has this been fixed yet?

**Comment by Chronitonity** [comment]
I'm certain that this got fixed with the RPD revert, someone mind closing it?

**Comment by WhiteFox08** [comment]
Reverted
