### ISSUE TITLE
Goodcurity Achievement doesn't  carry on to seperate rounds

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#365]
Tested several times, giving someone goodcurity lasts for one round then disables itself

**Comment by Nokington** [comment]
This has been broken and is/was being worked on by @nalarmg Also achievements are off.

**Comment by nalarmg** [comment]
Still being worked on, had other priorities lately that's distracted me however.

**Comment by Chronitonity** [comment]
@nalarmg please fix bby

**Comment by nalarmg** [comment]
Technically not a bug. Pending further discussion with head admins

**Comment by ghost** [comment]
it's a bug, the initial shitcurity achievement required the hub settings to be set, so the server could grant medals.
