### ISSUE TITLE
Smokable Drugs Are Ineffective

### ISSUE THREAD

**Issue by Podgehodge** [HippieStationArchive/HippieStation13-1#370]
You can smoke a max potency ambrosia rollie and it'll never trigger the trippy status effect.

I believe the reason for this is because smokables transfer a max of 0.2u of chemicals per tick. And, after some testing, I'm pretty sure a dose needs to be >= 0.1u for it to have any effect. Thus, the only way a chemical can be effective in a smokable is if it exceeds 50% of the total chemical content of whatever you're smoking.

For example, a cigar allows 20u of drugs. If you dip a cigar into 5u tricord, 5u anti-tox, 5u bicardine, and 5u dermaline, that cigar will heal 0 damage because none of those drug amounts exceed a percentage of 50% of the cigar's total contents. Yet, if you dip a cigar into 10u tricord and 10u bicardine, it'll heal damage just fine.

A max potency rollie has 50u of different chems in it and only 14u of those are space drugs. Therefore, no tripping balls. :thumbsdown:

**Comment by collinxchu** [comment]
I've never had this issue, but will test.

Confirmed. Not sure why, but the issue does indeed occur even with varedited ambrosia.
