### ISSUE TITLE
Golem's "shoes" don't protect them from glass shards lying on the floor.

### ISSUE THREAD

**Issue by Weisyl** [HippieStationArchive/HippieStation13-1#371]
Exactly as the title says, golems who walk over glass shards still run the risk of being stunned by them and a chance of the shard embedding.

**Comment by Chronitonity** [comment]
Think TG had something that fixed this, would be great to implement

**Comment by Carbonhell** [comment]
https://github.com/tgstation/-tg-station/commit/1fb8dcecd17776198ed359bb5f2ca220bb465570
There!

**Comment by WhiteFox08** [comment]
Fixed in #437
