### ISSUE TITLE
C-90's grenade launcher doesn't fire.

### ISSUE THREAD

**Issue by Weisyl** [HippieStationArchive/HippieStation13-1#400]
The C-90's grenade launcher can be switched to via the firemode button, and can be loaded / unloaded, but clicking on anything never fires it.

**Comment by Jaygriff** [comment]
Bit more information on this, you can load and unload the nades but cannot fire.

**Comment by Carbonhell** [comment]
Fixed in #634

**Comment by Carbonhell** [comment]
CLOSE
