### ISSUE TITLE
SS13 Sign outside the Brig

### ISSUE THREAD

**Issue by SplergeBucket** [HippieStationArchive/HippieStation13-1#401]
It's mistakenly labelled as "Space Station 13" when in reality it should be "Retard Zone". This is an atrocity and should be fixed immediately.

**Comment by Jaygriff** [comment]
Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy Hoy

**Comment by TDcoolguy300** [comment]
Unable to reproduce, give exact instructions

**Comment by Kokojos** [comment]
Use Wd-40

**Comment by Kokojos** [comment]
Issue closed because Ipsum.
