### ISSUE TITLE
Fireaxe can't dislodge girders

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#402]
It can force open doors like a crowbar (for good reason) but can't dislodge girders? Dunno if you would count this as a bug but its a really weird absence of feature I guess.

**Comment by TDcoolguy300** [comment]
Might be a feature actually, needs to be discussed

**Comment by Jaygriff** [comment]
You can bash them down.. But dislodging requires a screwdriver and a axe isnt a screwdriver...

**Comment by Chronitonity** [comment]
Dislodging requires a crowbar boi

**Comment by Jaygriff** [comment]
Sheet. Mixup on my end. Yes it should behave like a crowbar.

**Comment by WhiteFox08** [comment]
@danhibiki @SplergeBucket @Nebyab please review

**Comment by SplergeBucket** [comment]
Yeah, I'd say this is what could be considered a missing feature, i'd be for the changes here.

**Comment by lcass** [comment]
pull request made.

**Comment by WhiteFox08** [comment]
Fixed a #477
