### ISSUE TITLE
Shuttle temperature just keeps fucking climbing

### ISSUE THREAD

**Issue by collinxchu** [HippieStationArchive/HippieStation13-1#405]
If there's even a single bit of fire on the shuttle, even if it goes out ,the entire shuttle heats up and doesn't stop climbing in temperature.

**Comment by WhiteFox08** [comment]
https://dl.dropboxusercontent.com/u/20521740/ShareX/2015/08/2015-08-13_21-20-44.mp4

no temp change at all, at the current moment escape shuttle turf is unsim'ed.
