### ISSUE TITLE
Lethal Injection Syringes don't kill those who are injected with it

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#407]
Found by spacedong. This is either because the syringes that hold the Chloral are only 15u now for some reason, or that Chloral got nerfed for some other reason.

Or its just not metabolizing for some reason.

**Comment by TDcoolguy300** [comment]
From in-game testing, the Lethal syringes hold 50 units of Choral, well over the lethal limit of 15 units. But there seems to be a calculation issue when it comes to actually making it kill the person it had injected.

**Comment by TDcoolguy300** [comment]
Nevermind me, the lethal injection syringes are working as intended, not sure how you manage to get someone to survive 50 units of Choral hydrate, unless they have an extreme toxin filter from Virology
