### ISSUE TITLE
Supermatter respawn bug

### ISSUE THREAD

**Issue by TDcoolguy300** [HippieStationArchive/HippieStation13-1#408]
If you were to throw a locker which contains a person into the Supermatter, the person's body AND Ghost will delete, causing their client to crash, allowing them to rejoin as a new character. I have done a test with Kruor to confirm this

**Comment by WhiteFox08** [comment]
Yea, SM doesn't check for occupants and just deletes it along with the locker.

**Comment by Jaygriff** [comment]
Fixed
