### ISSUE TITLE
Medbay doesn't have a Sec Checkpoint.

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#409]
Which leaves it as the only department on board without one

**Comment by WhiteFox08** [comment]
Yea medbay needs a checkpoint to keep retards out

**Comment by collinxchu** [comment]
I would be okay for this if we did a proper remapping of medical to incorporate it, rather than just sticking it at the entrance and calling it a day.

**Comment by Jaygriff** [comment]
medbay rework is a WIP.

**Comment by Chronitonity** [comment]
Waiting room at the front has that weird wooden floored area that is the exact size of a checkpoint, would be as good of place as any to put one imo

**Comment by collinxchu** [comment]
Cept literally every other checkpoint is more central - not everything going on in medbay is right at the entrance, plus it means any sec officers are at very real danger in that room rather than it being a safe haven.

If anything I'd move cloning there since geneticists 9 out of 10 times don't give a shit about cloning people, and put the sec room in that general area.

**Comment by Jaygriff** [comment]
_breathes heavily_ the sec checkpoint in cargo is literally connected to the hall. Engineering is damn close.

**Comment by collinxchu** [comment]
Well then you've got one, and almost another.

Still shouldn't just tack things in place. I mean if it's the best option, sure, but I'd like a little consistency.

**Comment by lcass** [comment]
Re add departmential guards. They were useful and it sorts out a lot of tresspassing issues.

**Comment by Foosili** [comment]
Why not stick it where cryo is and put cryo in the spot where the weird lobby waiting room thing is if you want it to be more central?

Both are 4x6, it'd be as easy as rotating it.

**Comment by Chronitonity** [comment]
Departmental guards have been in since before you came here, they were removed and readded a loooooooooooooooooooooooooooooooooooooooong time ago

**Comment by collinxchu** [comment]
@Foosili I'm down for that, actually.

**Comment by ghost** [comment]
this. just make a door poke out the bottom so the gaurd can just walk directly out and be in middle of medbay

**Comment by Kokojos** [comment]
Well since Nok + hippie added the lobby im not touching anything till a head tells me to.

Having cryo outside medbay is a no no, however, beakers will get stolen 24/7.

**Comment by SplergeBucket** [comment]
The map that Fronk made was agreed upon and was to be merged, but a more pressing map change took priority and Fronk didn't update his old one. Go with what he did before.
