### ISSUE TITLE
Jelly people cannot suicide.

### ISSUE THREAD

**Issue by collinxchu** [HippieStationArchive/HippieStation13-1#415]
http://puu.sh/jxAsN.png

**Comment by WhiteFox08** [comment]
![sarhl2j](https://cloud.githubusercontent.com/assets/2702850/9265311/16ab10fe-41f7-11e5-9c1a-4ab18442d51f.jpg)
I was able to suicide, did you force a Species change through VV? Or did you inject yourself?

**Comment by Kokojos** [comment]
Was it a wizard round?

**Comment by AliiTea** [comment]
You sure you weren't using the admin body?

It's invincible..
