### ISSUE TITLE
The station is barely up to code

### ISSUE THREAD

**Issue by Nebyab** [HippieStationArchive/HippieStation13-1#416]
What is this? 

There isn't a complete wall here, it'd be a good idea to have one if only for aesthetics.

http://i.imgur.com/1o2SsxU.png

**Comment by Kokojos** [comment]
I blame the belgians.

**Comment by Weisyl** [comment]
Could use more examples of issues like this before it really becomes a priority.

**Comment by Jaygriff** [comment]
fixed in #422
