### ISSUE TITLE
Roboticists have access to science's chem laboratory 

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#420]
Why.

**Comment by Jaygriff** [comment]
because science

**Comment by Chronitonity** [comment]
Terrible please fix no one wants fuckin 6 people in there

**Comment by WhiteFox08** [comment]
@danhibiki @SplergeBucket @Nebyab please discuss.

**Comment by Jaygriff** [comment]
Its just 'OMG NEW PLAS NEED 2 EXPLORE' syndrome. People just break in every round anyway.

**Comment by Chronitonity** [comment]
Theres no reason for them to have access to a science department though

**Comment by Jaygriff** [comment]
Got a fix in the works.

**Comment by lcass** [comment]
put the fix onto the lcass-chem-patch branch. Makes it a bit neater and everything can be merged in bulk.

**Comment by Jaygriff** [comment]
fixed
