### ISSUE TITLE
SQL error causing the chat frame to jump to the bottom (SERIOUSLY)

### ISSUE THREAD

**Issue by Jaygriff** [HippieStationArchive/HippieStation13-1#423]
SQL ERROR during death reporting. Error : [Unknown column 'toxloss' in 'field list']

**Comment by Crystalwarrior** [comment]
wait. THAT'S why the fucking chat frame jumps to the bottom of the screen all the goddamn time?
Holy FUCK that error existed forever. Can anyone with knowledge of SQL fix this?

**Comment by blobbernaut** [comment]
So every time that happens, somebody died?

**Comment by Jaygriff** [comment]
pretty much.

**Comment by Jaygriff** [comment]
also caused by a few different things. But i dont know the actual application of the death reporting as ive never seen it ingame.

**Comment by blobbernaut** [comment]
SQL needs some cleaning up in general.

**Comment by nalarmg** [comment]
@blobbernaut your problem doesn't sound SQL related at all.
