### ISSUE TITLE
Plasma tiles create infinite plasma

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#434]
Title.

Creating plasma tiles(which is very easy) and lighting them creates an eternal flame.

**Comment by Chronitonity** [comment]
Confirmed, the amount of plasma they released should be nerfed, probably to 1/4th of what a bar of plasma that is grinded gives off when dumped.

**Comment by WhiteFox08** [comment]
Fixed in #467
