### ISSUE TITLE
Constructing tiny tank breaks the exosuit fabricator.

### ISSUE THREAD

**Issue by Norzonion** [HippieStationArchive/HippieStation13-1#44]
Fabricator window gets stuck on "Fabricating tiny tank" even after completing the build.

Requires disassembly and reassembly of the fabricator to go away.

**Comment by AliiTea** [comment]
I am fixing this right now - 

Still working on it.

**Comment by AliiTea** [comment]
Still borken

**Comment by AliiTea** [comment]
They aren't in the Mech Fabricator anymore so this issue is obsolete now..
