### ISSUE TITLE
Medi-Borg large beakers do not work still.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#458]
You can't apply your beaker onto a chem dispenser, however Chem Master 3000s DO work. 
You can then just eject the beaker from the chemmaster, and have a human fill it up. Storing the beaker module then teleports the beaker into you, so you can use the chems inside. You can't make your own chems right now, sadly.

**Comment by Jaygriff** [comment]
This is a intended feature so borgs cant mix their own chems. Ill see about changing it.

**Comment by Chronitonity** [comment]
Problem is anyone who picks up that beaker is stuck with it in their hands because of the NODROP flag

**Comment by Jaygriff** [comment]
Yeah im not sure that this has even been addressed in bay or TG either so im not sure how to go about it.

**Comment by ghost** [comment]
two solutions here.
- give cyborg beakers their own path, and only allow cyborgs to remove that path
- open a input() as list with all chems for cyborgs to try to interact with it, and let them select one chem to be added to the beaker

**Comment by Jaygriff** [comment]
@Chnkr I think the hypospray kind of does the second one already.. I dont exactly know the point of giving cyborgs a beaker and not letting them use it on everything a regular beaker can be used on. Probably was a balance issue earlier on but needs to be revisited.

**Comment by ghost** [comment]
can't we just move the odysseus chem synthesizer into the mediborg? that'd be tight af

**Comment by Jaygriff** [comment]
Hmm maybe

**Comment by ghost** [comment]
also ( offtopic ) you cant scan sarin or any newchems with odysseus for that matter.
