### ISSUE TITLE
Missing power cable on one of the new science lab door tiles

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#462]
There is a wire missing between the station power grid and the new science lab.

Is an easy fix, except that people who don't know about it will run out of power and be unable to make any new chems.

**Comment by Jaygriff** [comment]
It was removed in a recent revert. Ill redo it tonight

**Comment by WhiteFox08** [comment]
same ol C Jay

**Comment by Jaygriff** [comment]
Also disposals in that area is fucked. Just so i have a note

**Comment by Jaygriff** [comment]
fixed
