### ISSUE TITLE
Unloaded technological shell recipe: Pulse slug and Meteorshot shells

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#48]
They can't be made, you can make the dragonbreath kind of shell(put the UTS and a beaker with 5 units of pyrosium or whatever it was, screwdriver,drag table on you,click and wait), this is a bug present  on all tg servers.

**Comment by AliiTea** [comment]
Will look into this.

**Comment by AliiTea** [comment]
Not a bug
