### ISSUE TITLE
Welding pipe " Trunks " Doesn't work

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#482]
allows you to weld it at first, but never actually finishes.

**Comment by Chronitonity** [comment]
this was fixed in a prior pr, if its broken again its because it got an accidental revert

**Comment by ghost** [comment]
fuck

**Comment by Chronitonity** [comment]
Alright heres the PR that fixed it. It was reverted because it made disposal pipes randomly rotate when welded in. @whitefox08 can tell you more. Without further ado
https://github.com/HippieStationCode/HippieStation13/pull/334

**Comment by ghost** [comment]
ripripip, dmin PM from-Brawzki: No weld vars.
Click on the administrator's name to reply.

**Comment by Jaygriff** [comment]
Part of https://github.com/HippieStationCode/HippieStation13/issues/362

**Comment by Chronitonity** [comment]
Uh no its not

**Comment by Jaygriff** [comment]
Wops

**Comment by ghost** [comment]
WHOEVER SAID TWO HEADS WHERE BETTER THAN ONE!

**Comment by Jaygriff** [comment]
7 science facts

**Comment by ghost** [comment]
also, you cant weld any pipes for that matter... lol

**Comment by Pyko1** [comment]
Disposals pipes are still broken, cant weld them down after wrenching.

**Comment by WhiteFox08** [comment]
Reverted
