### ISSUE TITLE
Catwalk issues

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#489]
Can't place wires on intersections, but you can on straights.
http://i.imgur.com/SLHqtfQ.png

mesons don't detect catwalks or lattices(intended?)
http://i.imgur.com/EqVnWIk.png

**Comment by WhiteFox08** [comment]
![iifrxv3](https://cloud.githubusercontent.com/assets/2702850/9561116/fa36a984-4dfd-11e5-9120-82ddf35d9fb6.jpg)
It's been fixed at #488 . No one has bothered updating the server
Mesons don't work with objects as intended.
