### ISSUE TITLE
Borgs missing metal rods

### ISSUE THREAD

**Issue by Kirbyroth** [HippieStationArchive/HippieStation13-1#49]

**Comment by WhiteFox08** [comment]
Taking a look into this!

**Comment by Memendia** [comment]
Whitefox is too fucking slow, will have this fixed!

**Comment by lcass** [comment]
Fixed , spriting issue with setting the number. Look at pull request.

**Comment by AliiTea** [comment]
Har Har Har 10/10

**Comment by ghost** [comment]
still not resolved.

**Comment by lcass** [comment]
I fixed it within the pull request I made , it's in there somewhere.  if check to see if it's a cyborg , if it is use default rod sprite not rod-number. I checked the code , should have worked

Edit: Definately fixed
