### ISSUE TITLE
More gamemodes available with lower playercounts

### ISSUE THREAD

**Issue by TheMocheeze** [HippieStationArchive/HippieStation13-1#492]
Yeah this is miserable, with 30 players, we only see Traitor or changeling (Maybe nuke ops once in a blue moon) and it's unbelievably stale. Lower the player requirements for the other gamemodes! We don't get 80 a day anymore.

**Comment by WhiteFox08** [comment]
@danhibiki @nalarmg @SplergeBucket @danhibiki 

Please discuss

**Comment by blobbernaut** [comment]
I agree. Maybe we need to have multiple maps. A smaller station we can switch to on low pop.
