### ISSUE TITLE
No Slip shoes, traitor item

### ISSUE THREAD

**Issue by Xenotas** [HippieStationArchive/HippieStation13-1#499]
I was playing on a nuke ops round and had only four points left, decided to buy the no slips incase of lube.. but soon behold they do not save you from the fucking lube, can the shoes be fixed so they are immune to lube or can they be renamed to half-ass no slips, because they really don't do the job against lube either lube is to op or no slips just suck

**Comment by blobbernaut** [comment]
turn off gravity and get magboots

**Comment by WhiteFox08** [comment]
This is more of a balancing issue, having the shoes null basicly everything that is slippery would make it kinda over the top. however we could make lube harder to make.

**Comment by Pyko1** [comment]
Harder lube would be a really welcome change, hardly no round goes on without at least once slipping on lube.

Would be neat if was something like 1 part Bananium, 1 part Silicon, 1 part Water.

**Comment by blobbernaut** [comment]
That's much too hard. It might as well be removed. Maybe reduce the output value so it takes more chemicals to make the same amount

**Comment by TheMocheeze** [comment]
I agree with @blobbernaut, if we made lube turn out 10:1 then they could easily burn out the chem machine but still have enough to get a spray or two of it. Currently it's like 90 units is made with 3 presses of the chems.

**Comment by Jaygriff** [comment]
my vote is to make a effect over the lubed floor so its at least noticeable.

**Comment by ghost** [comment]
lolno.

**Comment by Jaygriff** [comment]
what do you suggest then @Chnkr

**Comment by ghost** [comment]
leave it as is.

**Comment by Jaygriff** [comment]
and even leave the no slip shoes able to be slipped?

**Comment by Pyko1** [comment]
Imho 4TC is a cheap price to be protected from water, even if you don't actively use it as an advantage.
Also, aren't they slightly faster than normal shoes?

**Comment by Jaygriff** [comment]
Only advantage is no slipping on water.

**Comment by Pyko1** [comment]
Still, well worth the 4tc if you can get spesscleaner bottle and fill it with water.

**Comment by Jaygriff** [comment]
i dont think even spraying water from a spray bottle makes the floors slippy dippy anymore.

**Comment by Jaygriff** [comment]
Then again, im not a shitler so i dont slip the floors regularly.

**Comment by Pyko1** [comment]
uh oh, you are right

**Comment by ghost** [comment]
> i dont think even spraying water from a spray bottle makes the floors slippy dippy anymore.

It does, attack_self using the spray while having it in a active hand, or click on it

**Comment by lcass** [comment]
Depending on views I can move this into lcass chem and make it moderately hard with bi products etc.
I don't think no slip shoes should be able to stop you slipping because you are basically walking on pure lube.

**Comment by TheMocheeze** [comment]
What if we treated it like slipping in space without magboots? The no-slip shoes will keep the person who walked over it upright but will launch them in their direction of travel an extra tile or two.

**Comment by TheMocheeze** [comment]
*Or a random direction

**Comment by Pyko1** [comment]
In that case they should at least drop items in hand, just to make it at least slightly harder to use lube for murderboning.

**Comment by blobbernaut** [comment]
No slips also stop banana peels and clown pdas.

**Comment by Chronitonity** [comment]
Theres no good reason for lube to slip people wearing No-Slips.

**Comment by nalarmg** [comment]
As far as my opinion goes, no slips should actually function as the name suggests and stop you from slipping. Yes, this includes lube. The object serves little purpose otherwise, realistically.

**Comment by Kokojos** [comment]
Fixed in PR #613
