### ISSUE TITLE
AI law 0 not synching with starting borg

### ISSUE THREAD

**Issue by Kirbyroth** [HippieStationArchive/HippieStation13-1#50]
Bug details: When AI becomes traitor (Law 0) the starting borg wont get the law 0 but still get notice that supposed to have one. This is very confusing as the notice you get make it seem you are separate traitor from the AI yet no objectives are given or a Law 0.

---
## How to reproduce: AI has to be a traitor then review your laws when your the starting borg.

Notes: ![confused](https://cloud.githubusercontent.com/assets/8416510/7100308/dd6b55b2-dfde-11e4-9455-215a659153c9.png)

---

**Comment by lcass** [comment]
Believe this one has been fixed , just tried to reproduce it.

**Comment by SplergeBucket** [comment]
Re-open if it isn't, i'm pretty sure it was.
