### ISSUE TITLE
Using help intent with a wrasslin belt after knocking a mob/person out breaks the belts attacks

### ISSUE THREAD

**Issue by Jaygriff** [HippieStationArchive/HippieStation13-1#500]
Tested and confirmed.

Also appears to stop working on monkeys specifically after using help intent on them? Jesus this issue is complex.

After you help one monkey up you cant do wrasslin moves on any monkeys but you can still do it on other players sometimes.

**Comment by Kokojos** [comment]
Also seems to affect PLASMA FIST scroll.
