### ISSUE TITLE
Gold slimes extract can spawn Ak-922 wielding russian.

### ISSUE THREAD

**Issue by Carbonhell** [HippieStationArchive/HippieStation13-1#501]
As the title says,i don't think it should be able to spawn human enemies like syndicate or soviets. And it could be used to make an ak-922 farm..oh jesus.

**Comment by Chronitonity** [comment]
Simple fix, whoever added in the AK russians forgot to put them into the blacklist for gold slimes. Should take 10 seconds so i'll yell at @whitefox08

**Comment by lcass** [comment]
nah mang , feature.

**Comment by WhiteFox08** [comment]
Fixed in #523
