### ISSUE TITLE
New Toxins + Compacted Chem Lab

### ISSUE THREAD

**Issue by TheMocheeze** [HippieStationArchive/HippieStation13-1#506]
Inb4 chronitonity gives me a (Y) also everything else is the same. 

http://i.hizliresim.com/B0GNLv.png

**Comment by Chronitonity** [comment]
:+1:

**Comment by TDcoolguy300** [comment]
:100:

**Comment by Chronitonity** [comment]
holy shit you made this an issue jesus christ more cheese
