### ISSUE TITLE
Can't make meth

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#516]
Current Meth recipe calls for Dimethlymine, Ethanol, and Ammonia. However, Diethylamine, the plant fertilizer, is made up of Ethanol and Ammonia. As a result, trying to combine all of these result in a beaker full of Dimethlymine and Diethylamine, which cannot be used to create Meth.

**Comment by lcass** [comment]
This issue has been resolved in an earlier pull request.
