### ISSUE TITLE
You can't place wires on catwalk intersections at the south west solars.

### ISSUE THREAD

**Issue by Dagtin** [HippieStationArchive/HippieStation13-1#529]
Wiring the south west solars isn't possible anymore, since you can't lay cable on the catwalk intersection.
(Adding lattice and a floor tile aparently solves the problem)
![picture](https://cloud.githubusercontent.com/assets/14149119/9704462/f0f96842-54a7-11e5-8e8a-f3a8972db57d.jpg)
![picture2](https://cloud.githubusercontent.com/assets/14149119/9704536/76e875a8-54ab-11e5-8f89-707ba19caf27.jpg)

**Comment by Dagtin** [comment]
Ok, after further testing it appears to be a problem that happens just for the sw solars.

**Comment by Pyko1** [comment]
Fixed on my PR.

**Comment by WhiteFox08** [comment]
Fixed at #530

**Comment by Pyko1** [comment]
did the server compile? as its not fixed on live

**Comment by Jaygriff** [comment]
Server is compiling. Not sure about the fix.
