### ISSUE TITLE
Can't jobban Shadowlings

### ISSUE THREAD

**Issue by SplergeBucket** [HippieStationArchive/HippieStation13-1#533]
National travesty, it is necessary that an admin has the power and ability to kill all and any fun people may be experiencing in this game. Rectify immediately.

**Comment by Chronitonity** [comment]
You can do this neither in the Job-Ban Panel http://puu.sh/k2P1F/83802f2634.png or in the Banning Panel http://puu.sh/k2P2K/760fd6f9cc.png
