### ISSUE TITLE
AI Fixer Sprite bug

### ISSUE THREAD

**Issue by AliiTea** [HippieStationArchive/HippieStation13-1#535]
![](http://i.imgur.com/y9ZYBhN.png)
Should be as easy as switching console sprites again to something more appealing.

**Comment by Chronitonity** [comment]
Switch them to those fucking cyborg ass sci fi ones we had Foos knows what im talking about

**Comment by AliiTea** [comment]
The holo screens?

**Comment by Chronitonity** [comment]
yes

**Comment by AliiTea** [comment]
Dhoohohohho those sexy motherfuckers 

gotta go find em now!

EDIT: Found em!

**Comment by Memendia** [comment]
Found em!

**Comment by Jaygriff** [comment]
not a bug, its coded in like that.

**Comment by AliiTea** [comment]
are.... are you fucking kidding me?

**Comment by AliiTea** [comment]
Remove this man from repo at once.. I don't trust him at all!

**Comment by Jaygriff** [comment]
It is. So you can see when the AI is restored and whatnot.

**Comment by Jaygriff** [comment]
makes a AI trapped in the restorer more noticeable.

**Comment by AliiTea** [comment]
ya I am fixing these right now holy shit

**Comment by ghost** [comment]
> not a bug, its coded in like that.

Get out, it's a bug.

**Comment by Chronitonity** [comment]
It's a bug, how could you think thats a feature

**Comment by ghost** [comment]
ask @JustinBNewton that guy likes to mark things as a feature, and port things from /tg/ in the hopes of fixing said bug.

**Comment by AliiTea** [comment]
Can someone remove the stupid feature tag?

**Comment by Jaygriff** [comment]
@chnkr i dint even port this over and its quite clearly intentional if you look at the code and sprites.

**Comment by lcass** [comment]
I understand the confusion but a bug is present with the way that the sprite works , it shouldn't be there on the rotated console.
