### ISSUE TITLE
Cigar sprites do not show up on monkeys.

### ISSUE THREAD

**Issue by Daundra** [HippieStationArchive/HippieStation13-1#54]
(For reference, I am Zack ingame, if that matters.)

Title states as the issue is. Cigarrette sprites work fine, both lit and unlit, however, attempting to put a cigar on a monkey will work, but the cigar will be invisible, lit or unlit.

**Comment by Crystalwarrior** [comment]
Gotta rework the way monkeys handle clothes to only offset human versions instead of having multiple versions.
