### ISSUE TITLE
Technological Shells are automatically "spent" when created at a protolathe, making them unusable.

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#542]
http://puu.sh/k49ZU/58a7b82463.png

http://puu.sh/k4a36/08c3fa1ed1.png

**Comment by AliiTea** [comment]
Did ya try putting something in them?

**Comment by Chronitonity** [comment]
Tablecrafting doesn't seem to want to work for anything so thats not possible either.

Also the sprite shows the "used shotgun shell" sprite, so either way everythings busted.

**Comment by AliiTea** [comment]
Why not just remove em?

I have **NEVER** seen someone use them

**Comment by Chronitonity** [comment]
Honestly I agree because all of R&D is poorly implemented, most of its "cool" stuff is never made.

**Comment by Carbonhell** [comment]
Tech shells work, but you can only make dragonsbreath currently. Meteor and Pulse slugs cannot be crafted,i don't know why. They NEVER get used because they CANNOT be made....

**Comment by Carbonhell** [comment]
Actually,just tested ingame,ALL the recipes work. The problem is,the wiki was wrong because you need 2 capacitors/2 manipulators, not just 1. I guess this issue can be closed then

**Comment by AliiTea** [comment]
oi chron close it - nothing is borken

**Comment by Chronitonity** [comment]
fuck you
