### ISSUE TITLE
Flashlights and lamps will act like they're not on if you put them in your bag and take them out.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#553]
![shit don t luminate](https://cloud.githubusercontent.com/assets/11933001/9777416/26945fa2-5732-11e5-8315-7fbf52a000e5.gif)
This only happens when you have another light source already on, such as your PDA, another flashlight/lamp etc.

**Comment by Jaygriff** [comment]
part of #478
