### ISSUE TITLE
Rev round ended (code broke?)

### ISSUE THREAD

**Issue by killer653** [HippieStationArchive/HippieStation13-1#56]
So, basically, the game said the code broke and to report it, so here you go.

The heads of staff were killed or exiled! The revolutionaries win! Round-end code broke! Please report this and its circumstances on GitHub at https://github.com/tgstation/-tg-station/issues Command's Approval Rating: 70.8% 

The head revolutionaries were: Mon0 was Landon Fryer (survived the revolution) Caxxo was Chad Griffiths (died) Michaelgudgeon was Harmony Snyder (survived the revolution) 

The revolutionaries were: DaWhatTheFox was Sue Bowchief (survived the revolution) Villeri was Honksy (survived the revolution) Super Jockey was Ayyy Lamia (survived the revolution) Dungeonbones was Lupe'an Nascero (survived the revolution) ZodTheZod was Braxton Hale (survived the revolution) Mrisump was Rick Mouthers (survived the revolution) Theonlydkdreng was Emil Stabil (died) Speakercity was Russel Rader (died) Emoriamor was Braylon Sutton (survived the revolution) Jake mate was Jake Fartaway (survived the revolution) Superdead was Goodwin Mcintosh (survived the revolution) Mgoodmanm was Jake Haynes (survived the revolution) CptCrunchie was Manley Mueller (survived the revolution) Rui55best was Theodore Hunam (survived the revolution) 

The heads of staff were: Cookiepopo was Colten Moore (died) _RandomDoge_ was Elizabeth Quinn (survived the revolution) Grigga was San Holo (died) Wizard1012 was Vinny Potter (body destroyed) Robotumus was Okeiri (body destroyed)

Apparantly, the HoS walked onto the cargo shuttle to grab a shipment of loyalty implants, which completely broke the code(??)

**Comment by WhiteFox08** [comment]
/datum/game_mode/proc/auto_declare_completion_shadowling() is calling for literately no reason. 
code/game/gamemodes/changeling/darkling.dm

**Comment by WhiteFox08** [comment]
Fixed in #73
