### ISSUE TITLE
Tanks still exist

### ISSUE THREAD

**Issue by SplergeBucket** [HippieStationArchive/HippieStation13-1#561]
http://puu.sh/k6Xw1/f5dafdea61.png
http://puu.sh/k6XzN/01c721a7bd.png

I say we remove them all, opinions?

**Comment by Chronitonity** [comment]
:+1:

**Comment by AliiTea** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/562

**Comment by WhiteFox08** [comment]
@SplergeBucket @nalarmg @danhibiki Status on this?

**Comment by danhibiki** [comment]
I'm pretty sure its agreed that we all want tanks removed

**Comment by Jaygriff** [comment]
removed entirely or just removed from standard player creation?

**Comment by lcass** [comment]
removing player creation would be good , I like the idea of them being spawnable.

**Comment by Jaygriff** [comment]
Thats what I was thinking. I hate hard removing stuff when the data for the objects just costs us a few kb in downloads.

**Comment by AliiTea** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/575

There we go
