### ISSUE TITLE
You can't mail things to the HoS' office

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#567]
Someone fucked up the piping near security so that it never gets routed there. @TheMocheeze @Kokojos @Pyko1 @whitefox08 one of you mapped this

**Comment by Pyko1** [comment]
Ill make a fix for it

**Comment by Pyko1** [comment]
Not too familiar how disposals and sorters work, but this should fix it.
![capture](https://cloud.githubusercontent.com/assets/12048747/9831497/1bfbabf8-5963-11e5-9e16-dcea766a74a3.PNG)
Now if i just can get my things sorted so i can make a PR.

**Comment by WhiteFox08** [comment]
@Pyko1 status?

**Comment by Pyko1** [comment]
just about to playtest, should be done in 10 mins if it works.

**Comment by Pyko1** [comment]
Had to remake the disposals piping around sec, it was broken on couple different occasions and sec lobby wasn't really compatible with mail (or thrash) going through there either after the normal flow was restored. playtesting more and making PR soon.

**Comment by Pyko1** [comment]
What the hell, half of the disposals mailing is fucked up.

ie. chapel leads to superslam, theater junction has duplicate straight pipe in top of it. will take a bit longer.

**Comment by Pyko1** [comment]
all fixes now

**Comment by Pyko1** [comment]
Can be closed, the fix is live
