### ISSUE TITLE
Remove the NukeOp shuttle turrets

### ISSUE THREAD

**Issue by AliiTea** [HippieStationArchive/HippieStation13-1#568]
If you manage to not die and get to the shuttle after they have all died you should be rewarded with a cool ass shuttle and not death :-1:

**Comment by danhibiki** [comment]
No way

**Comment by Chronitonity** [comment]
Pretty sure this was there so no one bum rushed their shuttle and stole the nuke in less than 5 minutes, making the round basically unwinnable.

**Comment by Chronitonity** [comment]
Although they do have a bug where they shoot PAIs that the nuke ops get at the start

**Comment by AliiTea** [comment]
Another "Gitgud" if you are ops and you don't bring the nuke with you, you deserve that good ole redtext

**Comment by Chronitonity** [comment]
gitgud and don't go near a syndicate shuttle as a crewmember

**Comment by AliiTea** [comment]
Gitgud squad who was defeated and left emags and agent ID's AND AN AFK mookop on shuttle

**Comment by WhiteFox08** [comment]
:-1:

**Comment by TheMocheeze** [comment]
:-1: because I think it's pretty shitty and meta-gamey for crew to seek out the shuttle when they know it's a nuke ops round.
