### ISSUE TITLE
Replace that fucking repulsive scream for catpeople

### ISSUE THREAD

**Issue by TheMocheeze** [HippieStationArchive/HippieStation13-1#572]
I am going to fucking die if I hear that fucking ear-piercing scream one more fucking time

**Comment by Jaygriff** [comment]
feature you dumb idiot

**Comment by AliiTea** [comment]
No.

**Comment by Chronitonity** [comment]
:-1:

**Comment by SplergeBucket** [comment]
It's a feature. No.

**Comment by Nebyab** [comment]
This is a feature. Why would you even think of removing the main reason to hunt down and kill catbeasts?

**Comment by lcass** [comment]
Two heads have said noperinio. I also say noperinio.

**Comment by WhiteFox08** [comment]
Over all :-1:
