### ISSUE TITLE
Blocking " Bolt of Death " still causes death.

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#573]
Davis Wheeler (as Kazuhira Miller) blocks the bolt of death with the cursed katana!
Davis Wheeler (as Kazuhira Miller) seizes up and falls limp, his eyes dead and lifeless...

that doesnt make sense

**Comment by Chronitonity** [comment]
Blocking bolts with katanas doesn't make sense

**Comment by ghost** [comment]
why do we have the verb blocking with it anyway, then

**Comment by AliiTea** [comment]
https://www.youtube.com/watch?v=QXtKlnLLLRQ

Totally makes sense

**Comment by TDcoolguy300** [comment]
This is purely something with projectile code, with bolts being classified as projectiles and the Katana having a projectile block chance it causes this message when a projectile hits you and you do block it, but bolts have effects and blocking only negates damages and not effects.

**Comment by nalarmg** [comment]
Unintended behavior. If you block a bolt, you, ironically,  shouldn't magically take on the effects anyway.
