### ISSUE TITLE
Blob core don't dissapear.

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#590]
http://s16.postimg.org/rom60x1w4/blobdontdie.jpg

They die but don't dissapear from the map. Deleting them won't work.

**Comment by Carbonhell** [comment]
Once the blob dies this happens:
runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
To avoid this safety check, set world.loop_checks=0.
proc name: qdel (/proc/qdel)
  usr: Admin (/mob/living/carbon/human/dummy)
  src: null
  call stack:
qdel(/datum/hud (/datum/hud))
Blob Overmind (868) (/mob/camera/blob): Destroy()
Blob Overmind (868) (/mob/camera/blob): Destroy()
qdel(Blob Overmind (868) (/mob/camera/blob))
Blob Overmind (868) (/mob/camera/blob): Destroy()
qdel(Blob Overmind (868) (/mob/camera/blob))
Blob Overmind (868) (/mob/camera/blob): Destroy()
qdel(Blob Overmind (868) (/mob/camera/blob))
Blob Overmind (868) (/mob/camera/blob): Destroy()
qdel(Blob Overmind (868) (/mob/camera/blob))
...
qdel(Blob Overmind (868) (/mob/camera/blob))
qdel(Blob Overmind (868) (/mob/camera/blob))
qdel(Blob Overmind (868) (/mob/camera/blob))
qdel(Blob Overmind (868) (/mob/camera/blob))
qdel(Blob Overmind (868) (/mob/camera/blob))
qdel(Blob Overmind (868) (/mob/camera/blob))
qdel(the blob core (/obj/effect/blob/core))
the blob core (/obj/effect/blob/core): attackby(the plasma cutter (/obj/item/weapon/pickaxe/plasmacutter), Admin (/mob/living/carbon/human/dummy), "icon-x=21;icon-y=23;left=1;scr...")
the blob core (/obj/effect/blob/core): Click(the floor (115,75,1) (/turf/simulated/floor/plasteel), "mapwindow.map", "icon-x=21;icon-y=23;left=1;scr...")

**Comment by WhiteFox08** [comment]
Fixed at #598
