### ISSUE TITLE
Optimise singularity so it doesn't lag the server to shit

### ISSUE THREAD

**Issue by WhiteFox08** [HippieStationArchive/HippieStation13-1#6]
Getting goon master controller certainly helped with the lag, however, let's face it, singularity is still calling too many goddamn procs for it to even be managable.
I suggest that the singularity is greatly optimized - maybe reduced speed, maybe remove the deconstruction of everything, SOMETHING to reduce it's laggy nature.

**Comment by SpaceStationCoder** [comment]
We could do the following things.
- Remove the `goonstation` master controller, and switch it for the `-tg-station` master controller.
- Disable all powernet, and atmos calculations if the singularity grows to a certain size.
- Get a better host.

**Comment by SpaceStationCoder** [comment]
Besides that, it's not only the `singularity` causing server lag, it's been getting worse the last few weeks.

**Comment by AliiTea** [comment]
No
Denied
Never
Ever
Happening

**Comment by Redswandir** [comment]
l m a o

**Comment by j-mie** [comment]
"Remove the goonstation master controller, and switch it for the -tg-station master controller." - How about no.

**Comment by ghost** [comment]
`How about no.`

Why not? It could boost performance even more, since the goon MC is clearly not performing well, and causes issues, such as atmos randomly going to idle for no reason.

**Comment by j-mie** [comment]
What evidence do you have to suggest that the Goon MC is the issue?

**Comment by Iamgoofball** [comment]
haha you guys don't want the tg MC

tg MC is kind of shit

go with the goon process scheduler

**Comment by AliiTea** [comment]
Fixed it!
