### ISSUE TITLE
mussle doesnt stop screaming

### ISSUE THREAD

**Issue by Kokojos** [HippieStationArchive/HippieStation13-1#62]
Self-explanatory

**Comment by Chronitonity** [comment]
mussle

**Comment by Crystalwarrior** [comment]
mussle?

**Comment by WhiteFox08** [comment]
mussle!

**Comment by AliiTea** [comment]
Kokojo can you explain

**Comment by Kokojos** [comment]
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by Crystalwarrior** [comment]
Fixed nuzzles allowing you to scream on Atlas station. Also fixed silence variable not having the same effect. Check my pr's on atlas, currently on phone.

**Comment by AliiTea** [comment]
Then close the damn issue you cucklord D:

**Comment by ghost** [comment]
This is not atlas, still not fixed.

**Comment by AliiTea** [comment]
Then maybe you should get off ur ass and take our fix for it D:
