### ISSUE TITLE
Research Division APC not wired to the grid

### ISSUE THREAD

**Issue by fireinthedisco** [HippieStationArchive/HippieStation13-1#620]
I'm assuming this is the map bug since I've seen it in two shifts so far. The "Research Division APC" on power management/alert consoles, which in person is labeled as "Misc Research APC", and which is located in the main Research Division hallway right next to the door to the Toxins Storage, isn't wired into the grid. There a square away from it so, easily fixed.

**Comment by Carbonhell** [comment]
Already reported in #612

**Comment by fireinthedisco** [comment]
Oops, my bad.

**Comment by Chronitonity** [comment]
No worries, this is a better bug report anywhoo

**Comment by Carbonhell** [comment]
Fixed in #627

**Comment by whitefox08** [comment]
Fixed in #627
