### ISSUE TITLE
Fore Starboard solar computer does not have a proper icon

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#635]
Simply put, not sure what the issue is. It doesn't seem to be an icon state issue, but its the only thing that would make sense. Instead, its just blank space.

http://i.imgur.com/hH5nXu9.png

http://i.imgur.com/pJh1CgO.png

**Comment by danhibiki** [comment]
Very odd, just checked in game this round and the console itself is totally fine. Not sure what happened.

**Comment by Pyko1** [comment]
on the picture it is computer frame, someone has dismantled it?

**Comment by danhibiki** [comment]
Not sure to be honest, someone just ahelped about it. I'll try to test it

**Comment by Pyko1** [comment]
its wrong icon stage after you screwdriver the glass, should be pc4, but it is jsut 4

**Comment by Pyko1** [comment]
The issue seems to be on all solar computers.
