### ISSUE TITLE
Stun batons with plasma batteries after exploding result in infinite charge stun baton.

### ISSUE THREAD

**Issue by Jaygriff** [HippieStationArchive/HippieStation13-1#649]
Yeeeeeeeeeep

**Comment by calibraptor** [comment]
I was the guy who discovered this in-game. Can reproduce by getting a plasma battery baton, and throwing it at someone until it stuns them and explodes, the result will be a hull breach and a baton with infinite charge. It has no power source if examined and will revert to a useless baton if you switch it off.

I only tested it by throwing it at braindead people, don't know if directly stunning someone with a plasma baton will work.

EDIT: Just tested, it also works if you stun someone directly with it.

**Comment by yacobm8** [comment]
Made a pull request for this :)

**Comment by Carbonhell** [comment]
Fixed in #676
