### ISSUE TITLE
Forum button links to a dead page

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#66]
Instead of linking to the current site: http://www.hippie-station-13.com/forums/index.php it links to http://www.hippie-station-13.com/index.php

**Comment by WhiteFox08** [comment]
Fixed with #65

**Comment by AliiTea** [comment]
Don't close shit without testing.. He is correct

**Comment by AliiTea** [comment]
Now it is fixed

**Comment by WhiteFox08** [comment]
Whoops closed the wrong one
