### ISSUE TITLE
Humans that are on their sides (From being in crit, tabled, ect) stay that when when Meat Spiked

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#668]
http://puu.sh/kl13a/3a2e24a5b1.png

Compare the guy on the left to the guy on the right, he shouldn't be on his side but he is.

It's not a huge issue and I have no idea how to fix it, but its something with rotations im sure.

**Comment by blobbernaut** [comment]
it's this line I think.

var/matrix/m120 = matrix()
m120.Turn(180)  <---------------
...
H.dir = 2

If a person is right side up, it flips them over, but if they're on their side it just makes them go to the other side.

**Comment by Pyko1** [comment]
I actually like how they are sideways, if anything make everyone have random rotation when meat spiked.

**Comment by Carbonhell** [comment]
So,bug or feature?

**Comment by Chronitonity** [comment]
bug still

**Comment by lcass** [comment]
The sprite is changed aswell I believe , unless it has been updated of course.
