### ISSUE TITLE
files in wrong folder doesn't allow people to add themselves to admins.txt for use with a private server for testing.

### ISSUE THREAD

**Issue by yacobm8** [HippieStationArchive/HippieStation13-1#675]
Steps to reproduce:
1: Download hippie station source code
2: Compile code
3: Run dream daemon and host private server
4: You will get errors in the dream daemon log saying that the files inside 
"\HippieStation13-master\config\initial_config" are not found. So admins.txt, admin_ranks.txt, mentors.txt etc wont be run.
Here is a screenshot of the problem:  http://imgur.com/dvYnryw
![adminsnotworking](https://cloud.githubusercontent.com/assets/7037839/10096673/992f2bba-639d-11e5-8dbe-918bd52087ed.png)

TO fix:
Simply move all files inside the "initial_config" folder into the "config" folder. 

I found this as I wanted to try and fix a issue in the code. When I tried to setup a private server with me as a admin it wasn't working and cost me a hour finding the problem. I'm not sure if this is supposed to be this way but I think it's a big hassle for anybody wanting to test and work on bugs in the code.

**Comment by nalarmg** [comment]
Non issue. You have to move the files from initial config to the actual config folder on setup. This is intended. The readme does need updating to reflect.
