### ISSUE TITLE
Disassembling Rwalls gives bonus rods

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#683]
As much as we love bonus rods, currently disassembling an rwall will leave 2 more over.

Reply PM from-RyanBlazuh/(Jack Brown): When I disassemble a reinforced wall, I stop at the reinforced girder. I place the plasteel at the reinforced girder, and you can have the 2 rods. You can make infinite rods using this glitch.

Basically, just removing those two rods from spawning or removing one metal sheet would fix this issue.

**Comment by Pyko1** [comment]
Also you wont get as much plasteel as it takes to make the wall, intended?

**Comment by lcass** [comment]
I think you lack metal when you disassemble a wall aswell.

**Comment by AliiTea** [comment]
:+1: keep it :o
