### ISSUE TITLE
Cyborgs' guns do not recharge

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#686]
Yeah, this is detrimental to Syndiborgs and Detective Borgs, and also emagged Standard Borgs because their lightsaber strangely says that they have no power left.

An entire Nuke Ops round was ruined due to this.

**Comment by TDcoolguy300** [comment]
Right, what could be happening is that they are either not referencing the cyborg cell correctly or trying to access an internal battery for whatever reason. These guns do not typically hold a charge, but rather draw on the borgs internal cell. If you had no power, these things would not work.

**Comment by trifornt-tinfornt** [comment]
I had full charge. If I had absolutely no power I wouldn't be able to use the thing at all, either way.

**Comment by TDcoolguy300** [comment]
Then it's having an issue pulling from your cell, i'll check it out when i can.

**Comment by trifornt-tinfornt** [comment]
Engineering Borg's RCD also suddenly stopped working for me today, and I presume it's the same issue.
