### ISSUE TITLE
Guardian Spirit's heal mode doesn't work.

### ISSUE THREAD

**Issue by trifornt-tinfornt** [HippieStationArchive/HippieStation13-1#687]
It doesn't seem to heal anyone I attempt to heal. Which is a problem thanks to the chat filter issue.

**Comment by Chronitonity** [comment]
This is probably because I do it the same way artificers do. You're /probably/ getting muted due to that bug not being fixed (which I thought it was.) If theres a better way to do this lemme know and we can implement it, but for now just ahelp an admin asking to unmute you I guess.
