### ISSUE TITLE
Turrets on syndie shuttle attack guardians spawned by syndies

### ISSUE THREAD

**Issue by Jaygriff** [HippieStationArchive/HippieStation13-1#690]
Thats pretty much it.

**Comment by TDcoolguy300** [comment]
Just how it's managed, really nothing we can do about it unless we also want Guardians from the station to kill the syndies on the shuttle.

**Comment by Jaygriff** [comment]
There wouldent be guardians on the station if it were syndies though..

**Comment by Jaygriff** [comment]
And we could make it inherit the spawners faction, that would solve that.

**Comment by TDcoolguy300** [comment]
Maybe, will need to be looked into though. Also there are Guardian spawners in space now, so that + Telescience = Crew-owned guardians

**Comment by Jaygriff** [comment]
Did we not just take all of the antag shit off of zlevels? Sorry ive been absent, i don't know why wed add this after removing the rest of the crap.

**Comment by TDcoolguy300** [comment]
Chron removed most Syndicate-only guns and crap from those Z-levels, and in their place some gimmicky stuff and a few of those guardian things.

**Comment by TDcoolguy300** [comment]
At #689

**Comment by Jaygriff** [comment]
Makes sense, i think the guardians inheriting the faction of the spawner would do the trick to fix this issue.
