### ISSUE TITLE
Brains wrongly named when gibbed while wearing another's ID

### ISSUE THREAD

**Issue by KillingTorcher** [HippieStationArchive/HippieStation13-1#709]
I was Slippery McHonkers, the Clown. So I had some issues with security and I ended up kidnapping the detective and stealing his everything. Anywho, I was wearing his ID and trenchcoat. My name (appeared name) was Sethanon (the Detective's name).

I got plasma fisted by some random person and my brain was named Sethanon's brain. I suspect this is because gibbing uses the name variable instead of real_name.

**Comment by TDcoolguy300** [comment]
Good eye, i'll check out the gibbing code and see if your fix could do it

**Comment by TDcoolguy300** [comment]
And now that it think of it, this could be the cause of the brain objective not working correctly.

**Comment by TDcoolguy300** [comment]
Fixed in #710
