### ISSUE TITLE
Janitor jumpsuit fucks up if you wear it casually

### ISSUE THREAD

**Issue by calibraptor** [HippieStationArchive/HippieStation13-1#718]
Saw it while observing a round, makes you look naked with text floating behind your head. Fix it.

**Comment by Weisyl** [comment]
Sounds like the icon for when it's worn casually isn't named correctly or doesn't exist (and the code doesn't stop it from being worn casually). Should be an E-Z fix.

**Comment by Weisyl** [comment]
Fixed in PR #706
