### ISSUE TITLE
OOC is automatically muted for returning players

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#728]

**Comment by Chronitonity** [comment]
Elaborate on this?

**Comment by danhibiki** [comment]
The preference is automatically set for OOC to be off, at least for several returning players.

**Comment by Chronitonity** [comment]
in the prefs tab ooc is automatically turned off. No idea how to fix that

**Comment by Chronitonity** [comment]
Fixed in #758
