### ISSUE TITLE
LCass' chemistry lab is missing

### ISSUE THREAD

**Issue by splat1125** [HippieStationArchive/HippieStation13-1#729]
This needs a 'feature request' label.
My precious chemistry lab in science is gone! How will I ever do science again?

**Comment by Chronitonity** [comment]
We already have a second chemistry system, we really don't need a third, or a chem lab in science

**Comment by DarkYew** [comment]
This is a feature only missing because of the /tg/ map merge. Please add it back in.

**Comment by TDcoolguy300** [comment]
Lcass chem needs to be ported first

**Comment by Cafaling** [comment]
I think Lcass chem is kill.

This probbaly won't get re-added.
