### ISSUE TITLE
R&D doesn't have access to genetics

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#732]

**Comment by Chronitonity** [comment]
I think he only has access to half genetics, and if so, this is intended.

**Comment by danhibiki** [comment]
I was told he couldn't get into genetics thru science, which shouldn't be intended. It should be noted I didn't check this first hand.

**Comment by theonlydkdreng** [comment]
This is partially true. The RD has access from science into genetics, but because of the new map he cant go from genetics into medbay, not even into the cloning room which he could before

**Comment by Chronitonity** [comment]
He was never supposed to, that was a mapping error. He was only supposed to have access to his side of genetics, the part that did science on bodies, not bring them to life.

Closing this as its a non issue then.
