### ISSUE TITLE
Teleport has random garbled text

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#735]
http://i.imgur.com/RU3LNN5.png

From "ghost" tab teleport, accesibly by anyone dead. Gives an error.

**Comment by Carbonhello** [comment]
Cannot find that. What did you do to reproduce this issue?

**Comment by Cafaling** [comment]
Only time I've seen the garbled text pop up was during a gang round when the dominator was placed. That doesn't seem to cause it though.

**Comment by Carbonhell** [comment]
Cannot be fixed, issue is linked with \improper which is a byond thing, and some ascii formatting weird stuff.It's not important anyway and it only happens very rarely seems.
