### ISSUE TITLE
Wrestling belt doesn't seem to function

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#744]

**Comment by Chronitonity** [comment]
Wrestling belt in the vault isnt the /wrestling type, this is why.

**Comment by Weisyl** [comment]
Ehhh nothing of value was lost.

**Comment by Chronitonity** [comment]
Still a bug, i'll try and fix it tomorrow

**Comment by Cafaling** [comment]
RIP wrestling belts?

**Comment by Pyko1** [comment]
Sure has been a lot peaceful with out em, can even walk past a table without getting powerbombed twice.

**Comment by Cafaling** [comment]
Yeah. It's actually kind of nice tbh

**Comment by danhibiki** [comment]
Lets get this shitty griffy item back into our lives.

**Comment by Chronitonity** [comment]
Trello.
