### ISSUE TITLE
Adminhelp UI is bizzare

### ISSUE THREAD

**Issue by Nebyab** [HippieStationArchive/HippieStation13-1#747]
(?) (PP) (VV) (SM) (FLW) (TP) (REJT):

Is a terrible UI layout. Not only is the button that's most likely to be used (FLW) not at the end of the row, but what is at the end of the row is the "Reject Adminhelp" button, which serves no functional purpose. We might as well excise that code and switch the order of FLW and TP. (Why was this moved, JMP used to be at the end of the row).

**Comment by Carbonhello** [comment]
fixed in #762
