### ISSUE TITLE
Non-humans in heads of staff positions

### ISSUE THREAD

**Issue by danhibiki** [HippieStationArchive/HippieStation13-1#748]
Just saw an IPC spawn in as captain.

**Comment by TDcoolguy300** [comment]
I only set that shit up for Cats right now. I'll fix it.

**Comment by Cafaling** [comment]
Has this been fixed? I can't stand the thought of a Ligger Cap.

**Comment by Carbonhell** [comment]
OOC: KallMor: You can also play as a non-human head if you set the job before switching races. just so we know how to reproduce the bug

**Comment by danhibiki** [comment]
Did we officially fix this?

**Comment by Carbonhell** [comment]
It's not about fixing,it's about not being able to reproduce it.How did it happen?I tried doing what kallmor said but it didn't work.

**Comment by danhibiki** [comment]
Step 1) set race as human
Step 2) set command positions
Step 3) Change race

The preview will still display non-human heads of staff.

**Comment by Carbonhell** [comment]
Oh yea it does but once you spawn ingame you will just roll as an accepted role. Pratically not a game breaking bug but an aesthetic bug, can't look into this personally tho i already got 2-3 other things to fix/add

**Comment by danhibiki** [comment]
Dont sweat it then, its just cosmetics.

**Comment by danhibiki** [comment]
We'll get to this later, low priority
