### ISSUE TITLE
Escape Wing Air Alarm

### ISSUE THREAD

**Issue by FatalEYES** [HippieStationArchive/HippieStation13-1#750]
So the air alarm in the escape wing now, by default, is siphoning the area. I can literally find no way to fix it in-game aside from welding the vent immediately.
![60tjpbw](https://cloud.githubusercontent.com/assets/14989902/10300095/471758a4-6ba7-11e5-8d80-2049fac61d2f.png)
![e3m9ool](https://cloud.githubusercontent.com/assets/14989902/10300097/49a7e9ee-6ba7-11e5-9e8b-645d7187d1ff.png)

**Comment by Chronitonity** [comment]
Fixed in #755

Thanks for giving letting us know!
