### ISSUE TITLE
Secway Issues

### ISSUE THREAD

**Issue by Cassord** [HippieStationArchive/HippieStation13-1#76]
few glitches with secways
1. Right clicking and selecting "Pick Up" when next to an item when on a secway doesn't work, however pulling, examining, and even just left clicking to pick it up instead works.
2. Pulling someone in handcuffs while on a secway does not restrain them, they can run out of your pull.
3. When on a secway, dialog menus like when filling up an air tank from an air canister glitch out and close and open and do a bunch of weird stuff. I have only tested this with the air canister menu.

**Comment by Crystalwarrior** [comment]
Most of these seem like an issue with Adjacent() proc, it doesn't realise that the person on a secway is actually close to what he's trying to interact with.
