### ISSUE TITLE
Abductors still fail despite meeting Victory conditions

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#775]
Byond doesn't wanna give Ayyliens the recognition they deserve

![ayy lmao iens](https://cloud.githubusercontent.com/assets/7012237/10345396/f192ff26-6d5b-11e5-926a-09aca755f018.PNG)

**Comment by Carbonhello** [comment]
From the screenshot you gave, only 3 abductees survived. Maybe you need 6 alive humans?

**Comment by McHatters** [comment]
wwhhaaatt you gotta keep your humies alive too agagag

**Comment by Carbonhello** [comment]
So can this be closed?

**Comment by Carbonhello** [comment]
Will test today to see if it's a bug or not

**Comment by TDcoolguy300** [comment]
Anything on this?

**Comment by Carbonhell** [comment]
The abductors were:
carbonhell was Kayden Burkett the Assistant and survived
Objective # 1: Experiment on 6 humans. Success!
Just tested. Abductees must be alive otherwise you'll lose. Close?
