### ISSUE TITLE
RIPLEY missing from mining base

### ISSUE THREAD

**Issue by SpinnerMaster** [HippieStationArchive/HippieStation13-1#776]
It was sitting in the mech bay recharging station in mining. It is no longer there.

**Comment by Chronitonity** [comment]
Will look into this and #781 tonight

**Comment by Chronitonity** [comment]
and by look into i mean just add the fucking ripley back in

**Comment by SpinnerMaster** [comment]
Thanks mane

**Comment by Weisyl** [comment]
Looks like Chron fixed this, closing.
