### ISSUE TITLE
derelict mapping issue

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#782]
https://gyazo.com/12833d054d2993a93e31fc5fad4b37de looks queer, i can walk inside the first window but not the second

**Comment by Spacedong** [comment]
ag you're queer :^) weird

**Comment by Cafaling** [comment]
Gonna see if I can do some fixes to the Derelict today.

**Comment by Chronitonity** [comment]
Derelict is gone, hail new derelict
