### ISSUE TITLE
mob description fix

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#784]
https://gyazo.com/80500e4ed6686b91637ad4957cfb25be
wtf agaga

**Comment by McHatters** [comment]
tears n swet

**Comment by TDcoolguy300** [comment]
So? He's powered by Tears and the Solar Wind Energy?

**Comment by Weisyl** [comment]
Maybe it's a joke? Actually knowing /tg/ we'll probably never know.

**Comment by Cafaling** [comment]
It's a joke. An obscure one, but a joke.

**Comment by Carbonhello** [comment]
yep it's a prank bro,look, the camera on the wall,it's a prank
no really it's a joke not an issue, it's there since years

**Comment by Chronitonity** [comment]
No its actually a joke
