### ISSUE TITLE
Cult engraved floors look like regular floors.

### ISSUE THREAD

**Issue by Weisyl** [HippieStationArchive/HippieStation13-1#788]
http://puu.sh/kCoVA/438382fd80.png

**Comment by TDcoolguy300** [comment]
This wasnt an issue eariler, weird

**Comment by blobbernaut** [comment]
it makes a normal cult floor when on top of space tiles though

**Comment by Carbonhell** [comment]
Known TG issue, they should be fixing it so i'm waiting for them, it's due to some change for the ss13 floor tiles in front of bridge

**Comment by Carbonhell** [comment]
Fixed in #996

**Comment by Carbonhell** [comment]
Close
