### ISSUE TITLE
Mulligan rounds don't seem to work

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#791]
Rounds always end when the antags die, doesn't matter what round type it is, meaning that we have to manually set the round to not do this every round.

**Comment by Cafaling** [comment]
Are continuous rounds enabled for them in the config?

**Comment by Chronitonity** [comment]
Yeah, looks like it.

**Comment by Cafaling** [comment]
RIP

Should be in config.txt

**Comment by nalarmg** [comment]
Should be fixed.
