### ISSUE TITLE
Vault Sec Checkpoint is a vaccum

### ISSUE THREAD

**Issue by Kirbyroth** [HippieStationArchive/HippieStation13-1#793]
No Air and No pressure it slowly sucks it in from the hall. Someone forgot to add a air alarm to it as well.

**Comment by Chronitonity** [comment]
10/10 this is on me so I'll fix it

**Comment by Spacedong** [comment]
can confirm what the fuck aaaaaa

**Comment by Weisyl** [comment]
Looks like Chron fixed this, closing.
