### ISSUE TITLE
Cats can be antags

### ISSUE THREAD

**Issue by Chronitonity** [HippieStationArchive/HippieStation13-1#795]

**Comment by AliiTea** [comment]
how is this a problem?

**Comment by Chronitonity** [comment]
Because the punishment only race shouldn't be taking antag slots away from players we actually want to have it, and the fact that someone who got catbanned was able to play antag is kinda terrible?

**Comment by AliiTea** [comment]
But it ruins the "All cats can't fight back" thing and it's hilarious when a cat DUNKS the entire station

EDIT:

If someone is catbanned why are they able to be ANTAG in the first place?
ban them from antags aswell REEEE

**Comment by danhibiki** [comment]
I see no problem with letting cats still roll antag, if we really wanted someone to not antag roll we just ban them from it. Catban is just a cruel way to punish someone, and if they roll antag, good on them.

**Comment by blobbernaut** [comment]
cats are clumsy like clowns though even as traitors

**Comment by Carbonhell** [comment]
So,since it's fine,close?
