### ISSUE TITLE
Electrified Grilles shock to infinity when standing on a table

### ISSUE THREAD

**Issue by McHatters** [HippieStationArchive/HippieStation13-1#796]
Thought this was the AI doing this until it shocked me well into death until roundend. In addition, I had a security hardsuit on.

![yep](https://cloud.githubusercontent.com/assets/7012237/10373613/28625a40-6e21-11e5-9100-1796dffdfdc3.png)

**Comment by Chronitonity** [comment]
Due to spacewind, closing
