### ISSUE TITLE
Syndicate shuttle doesnt have turrets 

### ISSUE THREAD

**Issue by WhiteFox08** [HippieStationArchive/HippieStation13-1#8]
This is a bug because basically every round the nuke has been stolen, someone re-add these fucks.

**Comment by AliiTea** [comment]
Or.. you know.. 
- Don't leave shutters open
- Don't bring the PDA with you
- Gib yourself before they get your ID
- Don't bring the Nuke Code with you

**Comment by SpaceStationCoder** [comment]
I don't need.
- The PDA
- The ID
- The Shutters
- The Nuke code

to get onto their shuttle, all i need is a `cyborg` or `telescience` or an `emag` honk

**Comment by AliiTea** [comment]
Fixed
