### ISSUE TITLE
please fix lighting issue

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#804]
https://gyazo.com/77482d1326d61679f181b12d9c7c49be god watfdasda
happens after ya take a suit off with lights in it

**Comment by blobbernaut** [comment]
There's also some stuff that goes on when you use a seclight on a taser and a helmet at the same time, they're very buggy and sometimes deactivate both if you deactivate one.

**Comment by danhibiki** [comment]
I think this was fixed?
