### ISSUE TITLE
Medbay Mapping Issues

### ISSUE THREAD

**Issue by Cassord** [HippieStationArchive/HippieStation13-1#81]
1. Mebay Storage is surrounded by rwalls but the windows aren't electrified. this should be a thing.
2. Chemistry doesn't have any lights in it and it gets REALLY dark when the light outside it gets broken.

**Comment by Chronitonity** [comment]
Alright ill tell @whitefox08 to fix this

**Comment by Cassord** [comment]
The windows should be electrified should be a thing, rather.

**Comment by Kokojos** [comment]
Apparently, wires were not added and no I personnaly find it a no-no.
