### ISSUE TITLE
Stun shots from an E-gun seem to use too much energy.

### ISSUE THREAD

**Issue by Weisyl** [HippieStationArchive/HippieStation13-1#850]
Firing stun shots with the E-gun seems to drain a whole bar per shot of energy. This allows only 5 shots compared to pre-rebase's 10 shots. IIRC the drain value for the electrode projectile is 100, so changing it to 50 should fix this.

**Comment by Pyko1** [comment]
Less stuns might not be entirely a bad thing tho.

**Comment by Weisyl** [comment]
It seems like lasers also only give it 5 shots. If we port E-pistols then we should probably double the max charge of E-guns.

**Comment by blobbernaut** [comment]
This gives energy guns the same shots as a taser. Doubling the number of tasers it can shoot seems like a buff energy guns do NOT need.

**Comment by Jaygriff** [comment]
The taser has many nore disabler shots than taser bolts, which was a feature of the update to encourage disabler use over tase. However the egun doesnt have a disable setting so you are SOL there.
