### ISSUE TITLE
PDA doesn't open if dragged onto tiles you can't see

### ISSUE THREAD

**Issue by Voratius** [HippieStationArchive/HippieStation13-1#852]
http://i.imgur.com/Ih6CNCt.jpg

In the picture, If I click and drag the PDA sprite onto any of the tiles in my view range(the ones to my left and right)(even the darkest ones), the PDA opens.
However, If I try to click and drag it onto a tile in the bridge(which I can not see, as it's blocked by the blast doors), it doesn't open.

IIRC pre-codebaseupdoot it opened no matter where you dragged it.

**Comment by Cafaling** [comment]
So that's why I've been having issues opening my PDA.

Pls fix

**Comment by TDcoolguy300** [comment]
I've checked out the method for the dragging for the PDA, it's no different than the old code, i'll continue to look into this later on

**Comment by danhibiki** [comment]
Has this been looked into?
