### ISSUE TITLE
No Radiation Suits in the Grav-Gen entry room.

### ISSUE THREAD

**Issue by Cafaling** [HippieStationArchive/HippieStation13-1#857]
The Gravity Generator gives off radiation when starting up and possibly while running, so it's generally a good idea to don a radiation suit while working with it. Two closets should be more than enough.

![Please help our Engineers](https://cloud.githubusercontent.com/assets/12205380/10414273/471455fa-6f99-11e5-9e2d-65c65f8350c3.png)

**Comment by Chronitonity** [comment]
This was fixed in some Pyko commit
