### ISSUE TITLE
Rev's can deconvert eachother

### ISSUE THREAD

**Issue by Nebyab** [HippieStationArchive/HippieStation13-1#858]
I can't believe I forgot to make this issue report (and to my knowledge this hasn't been changed since this issue came up (I really hope it wasn't changed so I don't look like an idiot)).

During a fight or due to a misclick, revs can hit eachother (by mistake I'm sure) and then deconvert each other. Not only is this an iffy thing gamemodewise, its something that really fucks up players rounds, especially when revs decide to get their valids on the non-rev in their midst.

**Comment by Cafaling** [comment]
This only happens when you target the head. Wearing helmets or hardhats negates the chances of being deconverted by your fellows.

**Comment by TDcoolguy300** [comment]
Been a thing before the rebase, as Cafaling said above it's intended for normal crew members to de-rev revolutionaries.

**Comment by Nebyab** [comment]
I understand the intent (I mean its a fundamental facet of the gamemode nobody seems to understand) but there's no advantage to allowing revs to deconvert each other. Why resolve something with specific rules and policy, when we can just remove it from the game since it adds nothing.

**Comment by Cafaling** [comment]
This is easily dealt with if Revs wear something to protect their head. Shit like this happens in fights. Sometimes you click on your buddies. Furthermore, being smacked on the head doesn't guarantee a deconvert. My 2 cents is leave it be.

**Comment by ghost** [comment]
kinda had it coming honestly, such a small chance + just flash his ass again.
