### ISSUE TITLE
Minor (and extremely easy) Map fixes

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#87]
1) Arcade Maintenance door is named "Garden Maintenance"
2) Wooden Table inside the Bar to the very left is missing a chair to the south, makes it look out of place. (muh ocd)
3) Abandoned lab should be renamed to Abandoned Lab

I can do all three of these fixes but I have no idea how to commit or put the fixes into effect, I'll need someone to teach me.

**Comment by AliiTea** [comment]
I had them fixed but my copy of the code got fucked.. Will go in and fix them.

**Comment by Kokojos** [comment]
I think those have all been resolved.
