### ISSUE TITLE
Becoming a shade problem

### ISSUE THREAD

**Issue by Angelx113** [HippieStationArchive/HippieStation13-1#875]
So as a succesfull cult member i stole caps id, shared full acess, we killed all freaking red-ass people in brig, then some guy explodet and sended me to whine in deadchat.
Some requests to become a shade poped up, i smashed dat fucking YES button so hard, but only got teleporter to people which were trying to summon a shade, my name changed to Shade of %username%, i got same obj. 
But i didn't spawn. I just didn't. I reportes sis shit in ah, an admin by the name Pyko after a conversation turned me into a shade manualy and it did a thing for him, but it didn't for me
![2015-10-12 22 09 15](https://cloud.githubusercontent.com/assets/15094529/10436337/701d9736-712e-11e5-9605-f3d8f337e84a.png)
ps, sry for my english, I'm actually not a native speaker

**Comment by Pyko1** [comment]
Also he was listed as shade antag, even tho he was a ghost.

**Comment by Pyko1** [comment]
Also apparently he had 2 ghosts associated to him, since all this time i was working on his "ghost" at sec.

**Comment by Carbonhello** [comment]
Cannot reproduce, it works fine in local.

**Comment by Angelx113** [comment]
I had the same problem now.
apparently i can't become a shade after i died as a cultist or something
