### ISSUE TITLE
No oxygen damage

### ISSUE THREAD

**Issue by PingyTalk** [HippieStationArchive/HippieStation13-1#878]
I left myself in a small, 3x1 area in engineering with no oxygen. The pressure was fine, and the temperature, but I drained all the oxygen from it using space. I never took any damage after 5 minutes in a locker, and another 5 out of it.

This doesn't seem to apply to taking in CO2 through a mask, or toxins. I haven't tested an empty canister.

**Comment by Carbonhello** [comment]
Confirmed TG issue,they're looking into it

**Comment by Carbonhello** [comment]
Fixed in #915 please close
