### ISSUE TITLE
Round probabilities seem faulty

### ISSUE THREAD

**Issue by nalarmg** [HippieStationArchive/HippieStation13-1#896]
Putting here for future reference; there have been instances of one round-type spanning across up to four or more rounds without fail. This doesn't seem right for secret weighting. Possibly faulty code, or faulty config.

**Comment by danhibiki** [comment]
Just to clarify, this is above low pop round rotation, I assume?

**Comment by Carbonhello** [comment]
I think it's due to config settings, since code seems fine and it happens randomly. Maybe all the gamemode possibilities should be lowered or no clue

**Comment by nalarmg** [comment]
Will do live testing with equal round probabilities to test this theory.

**Comment by Carbonhell** [comment]
News on this?

**Comment by nalarmg** [comment]
I've not seen any further complaints/comments about it, so I assume this isn't an issue anymore.

**Comment by nalarmg** [comment]
Closing as the lack of further information indicates this is no longer a concern.
