### ISSUE TITLE
Player Reported: Can play as a job you're job-banned from

### ISSUE THREAD

**Issue by Weisyl** [HippieStationArchive/HippieStation13-1#935]
> OOC: Dingdog7: theres a glitch where if you saved your job as the one yo where banned from you can sitll be that job

**Comment by TDcoolguy300** [comment]
Not sure how to fix this entirely yet, apply occasional temp bans if you see someone negating a jobban like usual.

**Comment by Pyko1** [comment]
Maybe make have a check when the player is created if his he is jobbanned from the job he is.
And if he is jobbanned change his job to "Toilet Sanitation Technician" With no access and make him a cat.

**Comment by TDcoolguy300** [comment]
The check already exists

**Comment by Carbonhell** [comment]
I tested it ingame and the bug wasn't here...???

**Comment by Chronitonity** [comment]
Be nice if someone could confirm this.

**Comment by danhibiki** [comment]
Gonna say this isn't an issue with actual system, more of a graphical error.

**Comment by Chronitonity** [comment]
Aye. This can be reopened if shit is broken.
