### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by j-mie** [HippieStationArchive/HippieStation13-1#97]
8:56 AM <JamieH> MrPerson: I kinda got it all working, 1 problem though
8:57 AM <JamieH> http://share.jamiehankins.co.uk/ShareX/2015/04/2015-04-21_08-35-02.png
8:57 AM <JamieH> Basically, I'm setting the color of the lighting object, but problem is, on the tile where my mouse is - the alpha is 0 so the colour does fuck all

this needs fixing - help :(

**Comment by Crystalwarrior** [comment]
huh, it can be solved by clamping the alpha var for colored objects so it never goes beyond specific alpha.
I wonder if it's possible to use blend_mode, too.
