### ISSUE TITLE
Server rules are currently down, need someone with box access to change it to the new host

### ISSUE THREAD

**Issue by TDcoolguy300** [HippieStationArchive/HippieStation13-1#987]
https://3ea2bb3284f0c3cb4c3e4dd1cf148414a2acb92a-www.googledrive.com/host/0B2SMUFxCxguaU25fM0dvUlROTFk/DARULES.htm New Host URL

**Comment by nalarmg** [comment]
My bad. I forgot to upload the rules properly when we moved over. Rules link updated, new rules location for the server's here - http://hippiestation.com/misc/darules.html
Forum rules here - http://hippiestation.com/misc/daforumrules.html

**Comment by danhibiki** [comment]
Shit, I actually already changed this in the config file for the server rules
