### ISSUE TITLE
making makeshift shotshell don't work

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-1#997]
https://i.gyazo.com/48038d1785ddef292270213f36e95e3c.png
ive got screwdriver inhand, and PLACED the items on the table. all correct, tryed with a beaker, a large beaker, etc

**Comment by AliiTea** [comment]
Where is the metal?

![capture](https://cloud.githubusercontent.com/assets/11639828/10700192/ef8e87ce-7970-11e5-8b1f-69b37fd69699.PNG)

**Comment by ghost** [comment]
oh cuck im autismo
